import {Button,Image,Text,View} from '@tarojs/components'
import {useEffect,useRef,useState} from 'react'
import {H5StillCamera,type CameraDiagnosticCapture,type CameraGeometryInventory} from '../platform/runtime'
import type {CameraStreamProfile} from '../platform/captureViewport'
import {createRecipe,renderPixels,setAdjustment,type AdjustmentParameter,type SourceImage} from '../fineTune/core'
import {controlledMaskAudit,diagnosticSource,localRegionAudit,rangeClassification,simulateLatestSlotScheduler,traceRange} from './fineTuneDiagnostics'
import './rootCauseDiagnostic.css'

type Stats={p50:number;p95:number;max:number;fps:number;longTaskCount:number;longTaskMax:number;renderCount:number;samples:number}
type Mode='UI_ONLY'|'CURRENT'|'RENDERER_MAIN'|'WORKER_DIAGNOSTIC'
type BenchParameter=Extract<AdjustmentParameter,'BRIGHTNESS'|'WARMTH'|'SATURATION'>
type ProfileCapture={profile:CameraStreamProfile;item:CameraDiagnosticCapture;previewFps:number|null}
const cameraProfiles:CameraStreamProfile[]=['MAIN_CURRENT','LIVE_LIKE','RELAXED']
const percentile=(items:number[],p:number)=>{const sorted=[...items].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor(sorted.length*p))]||0}
const nextFrame=()=>new Promise<number>(resolve=>requestAnimationFrame(resolve))
const toStats=(times:number[],elapsed:number,longTaskCount:number,longTaskMax:number,renderCount:number):Stats=>({p50:percentile(times,.5),p95:percentile(times,.95),max:Math.max(0,...times),fps:times.length*1000/Math.max(1,elapsed),longTaskCount,longTaskMax,renderCount,samples:times.length})

export function RootCauseDiagnostic(){
 const camera=useRef(new H5StillCamera()),[cameraOpen,setCameraOpen]=useState(false),[cameraProfile,setCameraProfile]=useState<CameraStreamProfile>('MAIN_CURRENT'),[inventory,setInventory]=useState<CameraGeometryInventory|null>(null),[captures,setCaptures]=useState<ProfileCapture[]>([]),capturesRef=useRef<ProfileCapture[]>([]),[profileFps,setProfileFps]=useState<number|null>(null),[error,setError]=useState(''),[running,setRunning]=useState<Mode|null>(null),[parameter,setParameter]=useState<BenchParameter>('BRIGHTNESS'),[results,setResults]=useState<Record<string,Stats>>({}),[value,setValue]=useState(0),renderCount=useRef(0)
 renderCount.current++
 useEffect(()=>{capturesRef.current=captures},[captures])
 useEffect(()=>()=>{camera.current.close();capturesRef.current.flatMap(({item})=>[item.intrinsicVideoUrl,item.visibleCoverUrl,item.centerThreeFourUrl,item.nativeStillUrl]).forEach(URL.revokeObjectURL)},[])
 const openProfile=async(profile:CameraStreamProfile)=>{setError('');setProfileFps(null);camera.current.setFacingMode('environment');const result=await camera.current.openDiagnosticProfile('diagnostic-camera-host',profile);if(!result.ok){setCameraOpen(false);setError(result.message||result.code);return}setCameraProfile(profile);setCameraOpen(true);setInventory(await camera.current.diagnosticInventory('diagnostic-camera-host'));const fps=await camera.current.measurePreviewFps();setProfileFps(fps)}
 const capture=async()=>{try{const item=await camera.current.diagnosticCapture('diagnostic-camera-host'),fps=profileFps??await camera.current.measurePreviewFps();setCaptures(current=>{const previous=current.find(entry=>entry.profile===cameraProfile);if(previous)[previous.item.intrinsicVideoUrl,previous.item.visibleCoverUrl,previous.item.centerThreeFourUrl,previous.item.nativeStillUrl].forEach(URL.revokeObjectURL);return [...current.filter(entry=>entry.profile!==cameraProfile),{profile:cameraProfile,item,previewFps:fps}]});setInventory(item.inventory)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const resetCameraAB=()=>{camera.current.close();camera.current.resetDiagnosticCameraPin();captures.flatMap(({item})=>[item.intrinsicVideoUrl,item.visibleCoverUrl,item.centerThreeFourUrl,item.nativeStillUrl]).forEach(URL.revokeObjectURL);setCaptures([]);setInventory(null);setCameraOpen(false);setProfileFps(null)}
 const source=useRef<SourceImage>(diagnosticSource(360,480))
 const canvasCommit=(data:Uint8ClampedArray)=>{const canvas=document.getElementById('diagnostic-fine-tune-canvas') as HTMLCanvasElement|null;if(!canvas)return;canvas.width=source.current.width;canvas.height=source.current.height;canvas.getContext('2d',{alpha:false})?.putImageData(new ImageData(new Uint8ClampedArray(Array.from(data)),source.current.width,source.current.height),0,0)}
 const workerRender=(recipe:ReturnType<typeof createRecipe>)=>new Promise<{total:number;data:Uint8ClampedArray}>((resolve,reject)=>{
  // @ts-ignore Taro/Webpack consumes this worker URL while repository typecheck targets CommonJS.
  const worker=new Worker(new URL('./diagnostic.worker.ts',import.meta.url),{type:'module'}),started=performance.now();worker.onerror=e=>{worker.terminate();reject(new Error(e.message))};worker.onmessage=e=>{const total=performance.now()-started;worker.terminate();resolve({total,data:new Uint8ClampedArray(e.data.data)})};const copy={...source.current,data:new Uint8ClampedArray(source.current.data)};worker.postMessage({id:1,source:copy,recipe},[copy.data.buffer])})
 const run=async(mode:Mode)=>{setRunning(mode);setError('');const times:number[]=[],start=performance.now(),renderStart=renderCount.current;let longTaskCount=0,longTaskMax=0;let observer:PerformanceObserver|undefined;try{observer=new PerformanceObserver(list=>{for(const entry of list.getEntries()){longTaskCount++;longTaskMax=Math.max(longTaskMax,entry.duration)}});observer.observe({entryTypes:['longtask']})}catch{}
  try{for(let index=0;index<20;index++){const raw=-100+(index%20)*(200/19),recipe=setAdjustment(createRecipe('diagnostic','diagnostic-source'),'ALL',parameter,raw/100),started=performance.now();if(mode==='UI_ONLY'){setValue(raw);await nextFrame();await nextFrame()}else if(mode==='RENDERER_MAIN'){renderPixels(source.current,recipe);await nextFrame()}else if(mode==='WORKER_DIAGNOSTIC'){const rendered=await workerRender(recipe);canvasCommit(rendered.data)}else{setValue(raw);await nextFrame();const rendered=renderPixels(source.current,recipe);canvasCommit(rendered.data);await nextFrame()}times.push(performance.now()-started)}await new Promise(resolve=>setTimeout(resolve,80));setResults(current=>({...current,[`${parameter}:${mode}`]:toStats(times,performance.now()-start,longTaskCount,longTaskMax,renderCount.current-renderStart)}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{observer?.disconnect();setRunning(null)}}
 const mask=controlledMaskAudit(),local=localRegionAudit(),scheduler=simulateLatestSlotScheduler(40,Array.from({length:40},(_,i)=>i*5),Array.from({length:40},()=>80)),range=[-100,-30,0,30,100].map(raw=>traceRange(raw))
 return <View className='diagnosticRoot'>
  <Text className='diagnosticEyebrow'>DEV ONLY · ROOT CAUSE ISOLATION</Text><Text className='diagnosticTitle'>OPPO Camera / Fine Tune A/B</Text><Text className='diagnosticWarning'>不上传诊断图像；不改变生产相机、滑杆或渲染行为。</Text>
  {error&&<View className='diagnosticError'>{error}</View>}
  <View className='diagnosticPanel'><Text className='diagnosticHeading'>Camera Stream Constraint / FOV A/B</Text><Text className='diagnosticLine'>固定手机和场景；依次打开 A、拍摄，再打开 B、拍摄。首次后摄 identity 会在本诊断会话内固定；页面只显示哈希。诊断预览使用 contain，不引入软件裁切。</Text><View className='diagnosticButtons'>{cameraProfiles.map(profile=><Button key={profile} className={cameraProfile===profile?'active':''} onClick={()=>openProfile(profile)}>{profile==='MAIN_CURRENT'?'A MAIN CURRENT':profile==='LIVE_LIKE'?'B LIVE LIKE':'C RELAXED'}</Button>)}</View><View id='diagnostic-camera-host' className='diagnosticCamera'/>{cameraOpen&&<Button onClick={capture}>拍摄当前 Profile 的 Native Still</Button>}<Button onClick={resetCameraAB}>重置 A/B 与 Camera Pin</Button>{inventory&&<Text className='diagnosticJson'>{JSON.stringify({profile:inventory.profile,requested:inventory.requested,actual:inventory.actual,startupLatencyMs:inventory.startupLatencyMs,previewFps:profileFps,video:inventory.video,container:inventory.container,orientation:inventory.screen.orientation,capabilities:inventory.track.capabilities,photoCapabilities:inventory.imageCapture.photoCapabilities,devices:inventory.devices,samePhysicalCamera:captures.length<2?'UNKNOWN':new Set(captures.map(entry=>entry.item.inventory.actual.deviceIdHash).filter(Boolean)).size===1?'YES':'NO'},null,2)}</Text>}</View>
  {captures.map(({profile,item,previewFps},index)=><View className='diagnosticPanel' key={item.nativeStillUrl}><Text className='diagnosticHeading'>{profile} · Stationary Capture {index+1}</Text><Text className='diagnosticLine'>REQUEST {JSON.stringify(item.inventory.requested)}</Text><Text className='diagnosticLine'>ACTUAL {JSON.stringify(item.inventory.actual)} · FPS {previewFps?.toFixed(1)||'unsupported'}</Text><View className='diagnosticGrid'><View><Text>1 CURRENT COVER</Text><Image mode='aspectFit' src={item.visibleCoverUrl}/></View><View><Text>2 INTRINSIC CONTAIN</Text><Image mode='aspectFit' src={item.intrinsicVideoUrl}/></View><View><Text>3 CENTER 3:4 REFERENCE</Text><Image mode='aspectFit' src={item.centerThreeFourUrl}/></View><View><Text>4 NATIVE STILL</Text><Image mode='aspectFit' src={item.nativeStillUrl}/></View></View><Text>{item.nativeStill.width}×{item.nativeStill.height} · {item.nativeStill.bytes} bytes · {item.nativeStill.mimeType}</Text><Text className='diagnosticJson'>transform: {JSON.stringify(item.estimatedPreviewToStillTransform)}</Text></View>)}
  <View className='diagnosticPanel'><Text className='diagnosticHeading'>Fine Tune Performance · 360×480 · 20 steps</Text><View className='diagnosticButtons'>{(['BRIGHTNESS','WARMTH','SATURATION'] as BenchParameter[]).map(item=><Button key={item} disabled={Boolean(running)} className={parameter===item?'active':''} onClick={()=>setParameter(item)}>{item}</Button>)}</View><canvas id='diagnostic-fine-tune-canvas' className='diagnosticCanvas'/><Text>numeric value: {value.toFixed(1)}</Text><View className='diagnosticButtons'>{(['UI_ONLY','CURRENT','RENDERER_MAIN','WORKER_DIAGNOSTIC'] as Mode[]).map(mode=><Button key={mode} disabled={Boolean(running)} onClick={()=>run(mode)}>{running===mode?'RUNNING':mode}</Button>)}</View>{Object.entries(results).map(([mode,stats])=><Text className='diagnosticLine' key={mode}>{mode}: p50 {stats.p50.toFixed(1)} / p95 {stats.p95.toFixed(1)} / max {stats.max.toFixed(1)}ms · throughput {stats.fps.toFixed(1)}/s · long {stats.longTaskCount}/{stats.longTaskMax.toFixed(1)}ms · renders {stats.renderCount}</Text>)}<Text className='diagnosticLine'>Plain H5 is served as a separate DEV-only page/tunnel to avoid Taro/React lifecycle.</Text></View>
  <View className='diagnosticPanel'><Text className='diagnosticHeading'>Capability / Range Static Audit</Text><Text className='diagnosticJson'>{JSON.stringify({local,mask,rangeClassification:rangeClassification(),range,scheduler},null,2)}</Text></View>
 </View>
}
