import assert from 'node:assert/strict'; import test from 'node:test';
import { CLOSED_LOOP_TRAJECTORIES, frame } from '../fixtures/closed-loop/trajectories.js';
import { CLOSED_LOOP_CONFIG, DEFAULT_TARGET } from '../closed-loop/config.js';
import { actionForIssue, canonicalDirectionTransform, computeDelta, LocalClosedLoopEngine, rankIssues } from '../closed-loop/engine.js';
import { replayScalarStates, ScalarTraceRecorder } from '../closed-loop/trace.js';
const run=(name:keyof typeof CLOSED_LOOP_TRAJECTORIES,armed=true)=>{const e=new LocalClosedLoopEngine();if(armed)e.armTrial(0);return CLOSED_LOOP_TRAJECTORIES[name].map(s=>e.update(s));};
const last=(name:keyof typeof CLOSED_LOOP_TRAJECTORIES)=>run(name).at(-1)!;
const terminal=(name:keyof typeof CLOSED_LOOP_TRAJECTORIES)=>[...run(name)].reverse().find(o=>o.episode?.terminal_outcome)?.episode?.terminal_outcome;

test('all recalibration and human-servo fixtures exist',()=>assert.ok(Object.keys(CLOSED_LOOP_TRAJECTORIES).length>=42));
test('delta is signed target-current',()=>{assert.ok(computeDelta(frame(0,.2,.35),DEFAULT_TARGET).x.delta!>0);assert.ok(computeDelta(frame(0,.8,.35),DEFAULT_TARGET).x.delta!<0);});
test('deadband and missing values remain explicit',()=>{assert.equal(computeDelta(frame(0,.48,.35),DEFAULT_TARGET).x.status,'SATISFIED');assert.equal(computeDelta(frame(0,null,null),DEFAULT_TARGET).x.status,'MISSING');});
test('physical X mapping ignores preview mirroring',()=>{assert.equal(actionForIssue('X_POSITION',computeDelta(frame(0,.2,.35),DEFAULT_TARGET)),'MOVE_LEFT');assert.equal(actionForIssue('X_POSITION',computeDelta(frame(0,.8,.35),DEFAULT_TARGET)),'MOVE_RIGHT');});
test('scale mapping is directional',()=>{assert.equal(actionForIssue('SCALE',computeDelta(frame(0,.5,.1),DEFAULT_TARGET)),'MOVE_CLOSER');assert.equal(actionForIssue('SCALE',computeDelta(frame(0,.5,.7),DEFAULT_TARGET)),'MOVE_FARTHER');});
test('priority chooses X for combined large error',()=>assert.equal(rankIssues(frame(0,.2,.1),computeDelta(frame(0,.2,.1),DEFAULT_TARGET))[0].kind,'X_POSITION'));

for(const fixture of [
  {name:'rear physical left',action:'MOVE_LEFT',facing:'REAR',mirror:'NON_MIRRORED',canonical:1,display:1},
  {name:'rear physical right',action:'MOVE_RIGHT',facing:'REAR',mirror:'NON_MIRRORED',canonical:-1,display:-1},
  {name:'front mirrored physical left',action:'MOVE_LEFT',facing:'FRONT',mirror:'MIRRORED',canonical:1,display:-1},
  {name:'front mirrored physical right',action:'MOVE_RIGHT',facing:'FRONT',mirror:'MIRRORED',canonical:-1,display:1},
  {name:'front nonmirrored physical left',action:'MOVE_LEFT',facing:'FRONT',mirror:'NON_MIRRORED',canonical:1,display:1},
  {name:'front nonmirrored physical right',action:'MOVE_RIGHT',facing:'FRONT',mirror:'NON_MIRRORED',canonical:-1,display:-1},
  {name:'closer ignores mirror',action:'MOVE_CLOSER',facing:'FRONT',mirror:'MIRRORED',canonical:1,display:1},
  {name:'farther ignores mirror',action:'MOVE_FARTHER',facing:'REAR',mirror:'NON_MIRRORED',canonical:-1,display:-1},
] as const)test(`canonical direction transform: ${fixture.name}`,()=>assert.deepEqual(canonicalDirectionTransform(fixture.action,fixture.facing,fixture.mirror),{canonical_axis_sign:fixture.canonical,display_axis_sign:fixture.display}));

test('stale measurement suppresses ordinary issuance',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const stale={...frame(300,.2,.35),measurement_age_ms:300};const o=e.update(stale);assert.equal(o.instruction,null);assert.equal(o.control_observation.suppression_reason,'MEASUREMENT_STALE');assert.equal(o.metrics.stale_suppressed_count,1);});
test('stale decision suppresses ordinary issuance',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const o=e.update(frame(300,.2,.35),{decision_timestamp_ms:500});assert.equal(o.instruction,null);assert.equal(o.control_observation.suppression_reason,'DECISION_STALE');});
test('reacquisition first state is an instruction barrier',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const s={...frame(300,.2,.35),reacquisition_count:1};const o=e.update(s);assert.equal(o.instruction,null);assert.equal(o.control_observation.suppression_reason,'REACQUISITION_BARRIER');});
test('second fresh state after reacquisition may issue',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));e.update({...frame(300,.2,.35),reacquisition_count:1});const o=e.update({...frame(450,.2,.35),reacquisition_count:1});assert.equal(o.instruction?.action,'MOVE_LEFT');});
test('control epoch binds camera and mirror at issue',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const o=e.update(frame(300,.2,.35),{camera_facing:'FRONT',preview_mirror_state:'MIRRORED'});assert.equal(o.control_epoch?.camera_facing,'FRONT');assert.equal(o.control_epoch?.preview_mirror_state,'MIRRORED');assert.equal(o.control_epoch?.display_axis_sign,-1);});
test('control epoch snapshot is deeply immutable',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const epoch=e.update(frame(300,.2,.35)).control_epoch!;assert.ok(Object.isFrozen(epoch));assert.ok(Object.isFrozen(epoch.target_snapshot));assert.ok(Object.isFrozen(epoch.measurement_snapshot));assert.throws(()=>{(epoch.target_snapshot as {center_x:number}).center_x=.9;},TypeError);});
test('active control epoch never changes meaning with later state',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const a=e.update(frame(300,.2,.35),{camera_facing:'FRONT',preview_mirror_state:'MIRRORED'});const b=e.update(frame(700,.42,.2,false,.5,.3,.2),{camera_facing:'REAR',preview_mirror_state:'NON_MIRRORED'});assert.equal(a.control_epoch,b.control_epoch);assert.equal(b.control_epoch?.camera_facing,'FRONT');assert.equal(b.control_epoch?.axis,'X');});
test('trace v2 records causal fields without raw media',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35));const s=frame(300,.2,.35);const o=e.update(s,{camera_facing:'REAR',preview_mirror_state:'NON_MIRRORED'});const r=new ScalarTraceRecorder();r.append(s,o);const json=r.json();assert.match(json,/xfx-live-p2-scalar-trace-v2/);assert.match(json,/control_epoch/);assert.match(json,/measurement_age_ms/);assert.doesNotMatch(json,/landmark|image|video/i);});
test('direct trace download context includes scenario, device, and performance snapshot',()=>{const r=new ScalarTraceRecorder();const json=r.json({scenario_label:'S1_HEAD_SHOULDERS_STATIC',generated_at_iso:'2026-08-26T00:00:00.000Z',runtime_telemetry:{duration_ms:8000,preview_fps_avg:30,vision_target_hz:8,vision_hz_avg:8,state_hz_avg:7,inference_ms_current:60,inference_ms_p50:65,inference_ms_p95:90,scheduled_frames:64,processed_frames:63,skipped_busy_frames:1,subject_detected_ratio:1,subject_loss_count:0,reacquisition_count:0,measurement_age_ms:0,worker_mode:'WORKER',memory_mb:10,cpu_observation:'BROWSER_API_UNAVAILABLE',thermal_observation:'BROWSER_API_UNAVAILABLE',raw_video_upload:0,backend_per_frame_calls:0,luna_calls:0},session:{user_agent:'OPPO K11 test',viewport_width:1080,viewport_height:2400,orientation:'portrait-primary',camera_facing:'FRONT',preview_mirror_state:'MIRRORED',target_id:'center-medium',theme_id:'DEFAULT',vision_target_hz:8,scheduler:'rvfc'}});const parsed=JSON.parse(json);assert.equal(parsed.evidence_context.scenario_label,'S1_HEAD_SHOULDERS_STATIC');assert.equal(parsed.evidence_context.runtime_telemetry.inference_ms_p95,90);assert.equal(parsed.evidence_context.session.camera_facing,'FRONT');assert.equal(parsed.raw_media,false);});
test('control age distribution is explicit',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.35),{decision_timestamp_ms:10});const o=e.update({...frame(300,.2,.35),measurement_age_ms:20},{decision_timestamp_ms:330});assert.equal(o.metrics.control_observation_age_ms_max,50);assert.ok(o.metrics.control_observation_age_ms_p95>=10);});
test('terminal evaluation cannot replan on the same state version',()=>{const config={...CLOSED_LOOP_CONFIG,issue_persistence_ms:0,instruction_gap_ms:0,settled_window_ms:0};const e=new LocalClosedLoopEngine(DEFAULT_TARGET,config);e.armTrial(0);e.update(frame(0,.2,.12));e.update(frame(100,.2,.12));e.update(frame(500,.1,.12,false,.5,-.2));const terminal=e.update(frame(1000,.1,.12,true));const duplicate=e.update({...frame(1100,.5,.12,true),sequence:terminal.control_observation.state_version});assert.equal(duplicate.instruction,null);assert.equal(duplicate.metrics.post_terminal_suppressed_count,1);});
test('fresh version after terminal permits axis replan',()=>{const config={...CLOSED_LOOP_CONFIG,issue_persistence_ms:0,instruction_gap_ms:0,settled_window_ms:0};const e=new LocalClosedLoopEngine(DEFAULT_TARGET,config);e.armTrial(0);e.update(frame(0,.2,.12));e.update(frame(100,.2,.12));e.update(frame(500,.1,.12,false,.5,-.2));e.update(frame(1000,.1,.12,true));const o=e.update({...frame(1100,.5,.12,true),sequence:11});assert.equal(o.control_epoch?.axis,'SCALE');});
test('X remains committed while Scale ranking changes',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.2,.12));const a=e.update(frame(300,.2,.12));const b=e.update(frame(700,.25,.05,false));assert.equal(a.control_epoch?.axis,'X');assert.equal(b.control_epoch?.epoch_id,a.control_epoch?.epoch_id);});
test('Scale remains committed while X ranking changes',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);e.update(frame(0,.5,.1));const a=e.update(frame(300,.5,.1));const b=e.update(frame(700,.1,.12,false));assert.equal(a.control_epoch?.axis,'SCALE');assert.equal(b.control_epoch?.epoch_id,a.control_epoch?.epoch_id);});
test('trial stays armed before ordinary instruction',()=>assert.equal(run('correct-gradual-x')[0].trial_state,'ARMED'));
test('trial begins exactly at first ordinary instruction',()=>{const o=run('correct-gradual-x')[1];assert.equal(o.trial_state,'RUNNING');assert.equal(o.first_instruction_at,o.instruction?.timestamp_ms);});
test('engine initialization never starts trial timing',()=>{const o=new LocalClosedLoopEngine().update(frame(500,.5,.35,true));assert.equal(o.first_instruction_at,null);assert.equal(o.metrics.time_to_target_ms,null);});
test('DISARMED never emits ordinary instructions',()=>{const e=new LocalClosedLoopEngine();const out=[frame(0,.2,.1),frame(500,.2,.1),frame(5000,.8,.7,true)].map(s=>e.update(s));assert.ok(out.every(o=>o.runtime_state==='IDLE'&&o.instruction===null&&o.metrics.ordinary_instruction_count===0));});
test('DISARMED cannot reach passive READY',()=>{const e=new LocalClosedLoopEngine();const out=[frame(0,.5,.35,true),frame(1500,.5,.35,true),frame(5000,.5,.35,true)].map(s=>e.update(s));assert.ok(out.every(o=>o.ready===false&&o.trial_state==='DISARMED'));});
test('ordinary instruction creates one episode',()=>{const o=run('correct-gradual-x')[1];assert.equal(o.metrics.ordinary_instruction_count,1);assert.equal(o.metrics.episode_count,1);assert.equal(o.episode?.episode_id,1);});
test('eight render frames remain one instruction event',()=>{const o=last('eight-render-frames-one-instruction-event');assert.equal(o.metrics.ordinary_instruction_count,1);assert.equal(o.metrics.episode_count,1);});
test('HOLD is excluded from ordinary instruction count',()=>{const o=last('hold-not-counted-as-instruction');assert.equal(o.metrics.ordinary_instruction_count,0);assert.equal(o.metrics.hold_count,1);});
test('HOLD is one-shot',()=>{const out=run('hold-not-counted-as-instruction');assert.equal(out.filter(o=>o.instruction?.action==='HOLD').length,1);});
test('delayed response does not become premature NO_EFFECT',()=>{const out=run('delayed-user-response');assert.equal(out[2].episode?.terminal_outcome,null);assert.equal(terminal('delayed-user-response'),'SUCCESS');});
test('correct gradual X ends SUCCESS',()=>assert.equal(terminal('correct-gradual-x'),'SUCCESS'));
test('correct gradual scale ends SUCCESS',()=>assert.equal(terminal('correct-gradual-scale'),'SUCCESS'));
test('crossing into deadband ends SUCCESS',()=>assert.equal(terminal('target-cross-into-deadband'),'SUCCESS'));
test('overshoot outside deadband is not WRONG_DIRECTION',()=>{const out=run('target-overshoot-outside-deadband');const ep=[...out].reverse().find(o=>o.episode?.terminal_outcome)?.episode;assert.equal(ep?.terminal_outcome,'NO_EFFECT');assert.ok(ep?.warning_flags.includes('OVERSHOOT_OUTSIDE_DEADBAND'));});
test('true sustained wrong direction is terminal WRONG_DIRECTION',()=>assert.equal(terminal('true-wrong-direction'),'WRONG_DIRECTION'));
test('no motion becomes NO_EFFECT after grace and settled window',()=>assert.equal(terminal('no-motion'),'NO_EFFECT'));
test('jitter-only does not become WRONG_DIRECTION',()=>assert.equal(terminal('jitter-only'),'NO_EFFECT'));
test('IMPROVING is intermediate and absent from denominator',()=>{const out=run('correct-gradual-x');assert.ok(out.some(o=>o.verification==='IMPROVING'));assert.equal(out.find(o=>o.verification==='IMPROVING')?.metrics.terminal_episode_count,0);});
test('improving then stopping outside target is NO_EFFECT',()=>assert.equal(terminal('improving-then-stop'),'NO_EFFECT'));
test('improve then regress before settle is not false SUCCESS',()=>assert.notEqual(terminal('improve-then-regress-before-settle'),'SUCCESS'));
test('each episode has exactly one terminal count',()=>{const o=last('repeated-no-effect-reissue');assert.equal(o.metrics.terminal_episode_count,o.metrics.no_effect_count+o.metrics.wrong_direction_count+o.metrics.successful_corrections);});
test('reissue only follows terminal and gap',()=>{const out=run('repeated-no-effect-reissue');const events=out.filter(o=>o.instruction&&o.instruction.action!=='HOLD').map(o=>o.instruction!);assert.equal(events.length,2);assert.ok(events[1].timestamp_ms-events[0].timestamp_ms>=CLOSED_LOOP_CONFIG.instruction_gap_ms);});
test('same action retry count is explicit',()=>assert.equal(last('repeated-no-effect-reissue').episode?.reissue_count,1));
test('READY is blocked before episode terminal',()=>assert.equal(last('ready-blocked-before-terminal').ready,false));
test('READY follows successful episode and stable window',()=>assert.equal(last('ready-after-success').ready,true));
test('READY latches trial and blocks post-ready episode contamination until re-arm',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);const states=[...CLOSED_LOOP_TRAJECTORIES['ready-after-success'],frame(4000,.8,.1),frame(4400,.8,.1),frame(6000,.8,.1,true)];const out=states.map(s=>e.update(s));assert.equal(out.at(-1)?.trial_state,'READY_LATCHED');assert.equal(out.at(-1)?.metrics.ordinary_instruction_count,1);assert.equal(out.at(-1)?.metrics.terminal_episode_count,1);});
test('passive confirmation uses the same terminal READY latch',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);const out=[frame(0,.5,.35,true),frame(600,.5,.35,true),frame(1300,.5,.35,true)].map(s=>e.update(s));assert.equal(out.at(-1)?.trial_state,'READY_LATCHED');assert.equal(out.at(-1)?.ready_source,'PASSIVE_CONFIRMATION');});
test('passive READY plus target exit emits zero ordinary actions',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);const out=[frame(0,.5,.35,true),frame(1300,.5,.35,true),frame(1600,.8,.1,false),frame(2100,.8,.1,true),frame(5000,.8,.1,true)].map(s=>e.update(s));assert.equal(out[1].trial_state,'READY_LATCHED');assert.equal(out.at(-1)?.metrics.ordinary_instruction_count,0);assert.equal(out.at(-1)?.runtime_state,'READY');});
test('READY latch ignores unstable and long-running movement',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);const out=[frame(0,.5,.35,true),frame(1300,.5,.35,true),frame(2000,.8,.1,false),frame(10000,.8,.1,false),frame(30000,.2,.7,true)].map(s=>e.update(s));assert.ok(out.slice(2).every(s=>s.trial_state==='READY_LATCHED'&&s.instruction===null));assert.equal(out.at(-1)?.metrics.ordinary_instruction_count,0);});
test('explicit rearm creates monotonic trial and episode lifecycle',()=>{const e=new LocalClosedLoopEngine();e.armTrial(0);const first=CLOSED_LOOP_TRAJECTORIES['correct-gradual-x'].map(s=>e.update(s));const firstEpisode=first.find(s=>s.episode)?.episode?.episode_id;e.armTrial(4000);const second=[frame(4000,.8,.35),frame(4300,.8,.35)].map(s=>e.update(s));assert.equal(second.at(-1)?.trial_id,2);assert.equal(second.at(-1)?.episode?.trial_id,2);assert.ok(second.at(-1)?.episode?.episode_id!>firstEpisode!);assert.equal(second.at(-1)?.metrics.successful_corrections,1);});
test('time to target starts at first correction',()=>{const o=last('trial-timer-invariant');assert.equal(o.metrics.time_to_target_ms,o.ready_at!-o.first_instruction_at!);});
test('time-to-target respects observed instruction gaps',()=>{const o=last('trial-timer-invariant');assert.ok(o.metrics.time_to_target_ms!>=CLOSED_LOOP_CONFIG.instruction_gap_ms+CLOSED_LOOP_CONFIG.settled_window_ms);});
test('success-rate denominator uses terminal outcomes only',()=>{const o=last('correct-gradual-x');assert.equal(o.metrics.correction_success_rate,1);assert.equal(o.metrics.terminal_episode_count,1);});
test('temporary subject loss does not create another instruction',()=>{const o=last('temporary-subject-loss-during-episode');assert.equal(o.metrics.ordinary_instruction_count,1);});
test('X then Scale episodes remain sequential',()=>{const out=run('x-then-scale-sequential-corrections');const actions=out.flatMap(o=>o.instruction&&o.instruction.action!=='HOLD'?[o.instruction.action]:[]);assert.deepEqual(actions.slice(0,2),['MOVE_LEFT','MOVE_CLOSER']);});
test('no oscillation while active episode is latched',()=>assert.equal(last('x-then-scale-sequential-corrections').metrics.oscillation_count,0));
test('Y remains measured but action mapping is deferred',()=>{const t={...DEFAULT_TARGET,y_exempt:false};const s=frame(0,.5,.35,true,.2);const i=rankIssues(s,computeDelta(s,t)).find(x=>x.kind==='Y_POSITION');assert.equal(i?.action,null);});
test('local recovery occurs after bounded terminal failures',()=>{const config={...CLOSED_LOOP_CONFIG,local_failure_limit:1};const e=new LocalClosedLoopEngine(DEFAULT_TARGET,config);e.armTrial(0);const out=CLOSED_LOOP_TRAJECTORIES['no-motion'].map(s=>e.update(s));assert.equal(out.at(-1)?.runtime_state,'LOCAL_RECOVERY_REQUIRED');assert.equal(out.at(-1)?.metrics.recovery_count,1);});
test('scalar trace contains no raw media or landmarks',()=>{const states=CLOSED_LOOP_TRAJECTORIES['correct-gradual-x'];const outputs=replayScalarStates(states);const r=new ScalarTraceRecorder();states.forEach((s,i)=>r.append(s,outputs[i]));const json=r.json();assert.doesNotMatch(json,/landmark|image|video|frame/i);});
test('scalar replay is deterministic',()=>{const states=CLOSED_LOOP_TRAJECTORIES['correct-gradual-x'];assert.deepEqual(replayScalarStates(states),replayScalarStates(states));});
test('external hot-path counters remain zero',()=>{const m=last('correct-gradual-x').metrics;assert.deepEqual([m.provider_calls,m.backend_per_frame_calls,m.luna_calls,m.raw_video_upload],[0,0,0,0]);});

test('servo correct move stops inside deadband',()=>assert.equal(terminal('servo-correct-inside-deadband'),'SUCCESS'));
test('servo halfway stop remains outside axis target',()=>assert.equal(terminal('servo-stops-halfway'),'NO_EFFECT'));
test('servo overshoot is diagnosed',()=>assert.equal(last('servo-correct-overshoot').episode?.no_effect_subtype,'OVERSHOOT'));
test('fast overshoot receives one predictive STOP',()=>assert.equal(run('servo-fast-overshoot').filter(o=>o.instruction?.action==='STOP_HERE').length,1));
test('slow overshoot receives one corridor STOP',()=>assert.equal(run('servo-slow-overshoot').filter(o=>o.instruction?.action==='STOP_HERE').length,1));
test('servo no motion remains NO_EFFECT',()=>assert.equal(terminal('servo-no-motion'),'NO_EFFECT'));
test('late motion is retained as diagnostic',()=>assert.equal(last('servo-late-motion').episode?.no_effect_subtype,'LATE_RESPONSE'));
test('jitter-only remains safe NO_EFFECT',()=>assert.equal(terminal('servo-jitter-only'),'NO_EFFECT'));
test('true wrong direction remains hard WRONG_DIRECTION',()=>assert.equal(terminal('servo-true-wrong'),'WRONG_DIRECTION'));
test('intended axis stays latched during coupled movement',()=>{const out=run('servo-axis-coupled');assert.ok(out.filter(o=>o.episode&&!o.episode.terminal_outcome).every(o=>o.episode?.issue==='X_POSITION'));});
test('enter braking corridor emits STOP then succeeds',()=>{const out=run('servo-stop-success');assert.ok(out.some(o=>o.instruction?.action==='STOP_HERE'));assert.equal(terminal('servo-stop-success'),'SUCCESS');});
test('STOP is issued only once per episode',()=>assert.equal(run('servo-stop-once').filter(o=>o.instruction?.action==='STOP_HERE').length,1));
test('STOP does not count as ordinary instruction',()=>{const o=last('servo-stop-not-ordinary');assert.equal(o.metrics.stop_cue_count,1);assert.equal(o.metrics.ordinary_instruction_count,1);});
test('STOP hysteresis prevents spam',()=>assert.equal(run('servo-stop-hysteresis').filter(o=>o.instruction?.action==='STOP_HERE').length,1));
test('wrong terminal plus satisfied geometry enters pending confirmation',()=>assert.ok(run('servo-wrong-then-satisfied').some(o=>o.runtime_state==='SATISFIED_PENDING_CONFIRMATION')));
test('pending confirmation becomes READY without rewriting WRONG',()=>{const o=last('servo-pending-to-ready');assert.equal(o.ready,true);assert.equal(o.ready_source,'PASSIVE_CONFIRMATION');assert.equal(o.metrics.wrong_direction_count,1);});
test('broken pending confirmation resumes correction',()=>{const out=run('servo-pending-breaks');const pending=out.findIndex(o=>o.runtime_state==='SATISFIED_PENDING_CONFIRMATION');assert.ok(pending>=0);assert.ok(out.slice(pending+1).some(o=>o.runtime_state!=='SATISFIED_PENDING_CONFIRMATION'&&!o.ready));});
test('SUCCESS retains normal READY causality',()=>assert.equal(last('servo-success-normal-ready').ready_source,'EPISODE_SUCCESS'));
test('HOLD remains distinct from STOP',()=>{const actions=run('servo-hold-distinct-stop').flatMap(o=>o.instruction?[o.instruction.action]:[]);assert.ok(actions.includes('STOP_HERE'));assert.ok(actions.includes('HOLD'));});
test('partial progress permits legal same-direction refinement',()=>{const actions=run('servo-partial-refinement').flatMap(o=>o.instruction&&o.instruction.action!=='STOP_HERE'&&o.instruction.action!=='HOLD'?[o.instruction.action]:[]);assert.deepEqual(actions.slice(0,2),['MOVE_LEFT','MOVE_LEFT']);});
test('READY source telemetry is explicit',()=>assert.equal(last('servo-ready-source').ready_source,'EPISODE_SUCCESS'));
test('high velocity target crossing does not become true wrong',()=>assert.notEqual(terminal('servo-high-velocity-crossing'),'WRONG_DIRECTION'));
test('low velocity target crossing does not become true wrong',()=>assert.notEqual(terminal('servo-low-velocity-crossing'),'WRONG_DIRECTION'));
test('axis issue switches only after active episode terminal',()=>{const out=run('servo-axis-switch-after-terminal');const scaleIndex=out.findIndex(o=>o.instruction?.action==='MOVE_CLOSER');assert.ok(scaleIndex>0);assert.ok(out.slice(0,scaleIndex).filter(o=>o.episode&&!o.episode.terminal_outcome).every(o=>o.episode?.issue==='X_POSITION'));});
test('local recovery resumes without resetting accepted metrics',()=>{const config={...CLOSED_LOOP_CONFIG,local_failure_limit:1};const e=new LocalClosedLoopEngine(DEFAULT_TARGET,config);e.armTrial(0);const before=CLOSED_LOOP_TRAJECTORIES['no-motion'].map(s=>e.update(s)).at(-1)!;assert.equal(before.runtime_state,'LOCAL_RECOVERY_REQUIRED');assert.equal(e.resumeAfterLocalRecovery(1800),true);const after=[frame(1900,.2,DEFAULT_TARGET.height_ratio),frame(2200,.2,DEFAULT_TARGET.height_ratio)].map(s=>e.update(s)).at(-1)!;assert.equal(after.metrics.terminal_episode_count,1);assert.equal(after.episode?.episode_id,2);});
test('resume is rejected outside local recovery',()=>assert.equal(new LocalClosedLoopEngine().resumeAfterLocalRecovery(0),false));
test('stable local recovery resumes automatically after bounded window',()=>{const config={...CLOSED_LOOP_CONFIG,local_failure_limit:1};const e=new LocalClosedLoopEngine(DEFAULT_TARGET,config);e.armTrial(0);CLOSED_LOOP_TRAJECTORIES['no-motion'].forEach(s=>e.update(s));const out=[frame(1800,.2,DEFAULT_TARGET.height_ratio,true),frame(2500,.2,DEFAULT_TARGET.height_ratio,true),frame(3000,.2,DEFAULT_TARGET.height_ratio,true),frame(3300,.2,DEFAULT_TARGET.height_ratio,true)].map(s=>e.update(s));assert.equal(out[0].runtime_state,'LOCAL_RECOVERY_REQUIRED');assert.equal(out[0].local_recovery_remaining_ms,1100);assert.equal(out.at(-1)?.runtime_state,'INSTRUCTING');assert.equal(out.at(-1)?.episode?.episode_id,2);});
test('motion resets automatic recovery countdown',()=>{const config={...CLOSED_LOOP_CONFIG,local_failure_limit:1};const e=new LocalClosedLoopEngine(DEFAULT_TARGET,config);e.armTrial(0);CLOSED_LOOP_TRAJECTORIES['no-motion'].forEach(s=>e.update(s));const out=[frame(1800,.2,DEFAULT_TARGET.height_ratio,true),frame(2200,.2,DEFAULT_TARGET.height_ratio,false),frame(2900,.2,DEFAULT_TARGET.height_ratio,true),frame(3500,.2,DEFAULT_TARGET.height_ratio,true)].map(s=>e.update(s));assert.equal(out.at(-1)?.runtime_state,'LOCAL_RECOVERY_REQUIRED');assert.equal(out.at(-1)?.local_recovery_remaining_ms,600);});
