import assert from 'node:assert/strict';
import test from 'node:test';
import { DEFAULT_TARGET } from '../closed-loop/config.js';
import { HumanStepServoV3 } from '../control-v3/controller.js';
import { classifyTrace, replayTraceV3, type TraceLikeRow } from '../control-v3/replay.js';
import type { LiveMeasurementV3, V3FramingRelation, V3XRelation } from '../control-v3/types.js';

const measurement=(timestamp_ms:number,state_version:number,framing_relation:V3FramingRelation,x_relation:V3XRelation,stable=true,framingError:number|null=framing_relation==='IN_RANGE'?0:2,xError:number|null=x_relation==='IN_RANGE'?0:2):LiveMeasurementV3=>Object.freeze({timestamp_ms,subject_state:'PRESENT',measurement_quality:stable?'GOOD':'MARGINAL',fresh:true,stable,framing_relation,x_relation,framing_motion:stable?'STILL':framing_relation==='TOO_CLOSE'?'FARTHER':'CLOSER',x_motion:stable?'STILL':x_relation==='TOO_LEFT'?'RIGHT':'LEFT',state_version,measurement_age_ms:0,diagnostics_ref:Object.freeze({measurement_id:`m${state_version}`,framing_error_normalized:framingError,x_error_normalized:xError,framing_position:framing_relation==='TOO_CLOSE'?1.2:framing_relation==='TOO_FAR'?.3:.52,x_position:x_relation==='TOO_LEFT'?.3:x_relation==='TOO_RIGHT'?.7:.5,framing_comparison_key:'FRAMING_V3:center-medium',x_comparison_key:'X_V3:center-medium',internal_body_mode:'UPPER_BODY',internal_scale_metric_type:'UPPER_BODY_SCALE',validity_reason:'TEST'})});
const driveSettled=(controller:HumanStepServoV3,start:number,version:number,framing:V3FramingRelation,x:V3XRelation,endFraming:V3FramingRelation,endX:V3XRelation,endFramingError:number|null=0,endXError:number|null=0)=>{
  const initial=controller.update(measurement(start,version,framing,x));
  const second=controller.update(measurement(start+300,version+1,framing,x));
  const issued=initial.action?initial:second;
  controller.update(measurement(start+500,version+2,endFraming,endX,false,endFramingError,endXError));
  controller.update(measurement(start+900,version+3,endFraming,endX,true,endFramingError,endXError));
  const evaluated=controller.update(measurement(start+1300,version+4,endFraming,endX,true,endFramingError,endXError));
  return {issued,evaluated};
};

test('V3 freezes combined order as FRAMING then ALIGN_X',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const framing=driveSettled(c,0,1,'TOO_CLOSE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2);assert.equal(framing.issued.action,'MOVE_FARTHER_SMALL');assert.equal(framing.evaluated.outcome,'TARGET_REACHED');const x=driveSettled(c,1600,6,'IN_RANGE','TOO_LEFT','IN_RANGE','IN_RANGE',0,0);assert.equal(x.issued.action,'MOVE_LEFT_SMALL');assert.equal(x.evaluated.outcome,'TARGET_REACHED');assert.deepEqual([framing.issued.episode?.stage,x.issued.episode?.stage],['FRAMING','ALIGN_X']);});
test('V3 human step has no predictive STOP or braking state',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const {issued,evaluated}=driveSettled(c,0,1,'IN_RANGE','TOO_RIGHT','IN_RANGE','IN_RANGE',0,0);assert.equal(issued.action,'MOVE_RIGHT_SMALL');assert.equal(evaluated.outcome,'TARGET_REACHED');assert.ok(!['BRAKING','WAITING_FOR_MOTION','TRACKING_MOTION'].includes(evaluated.stage));});
test('V3 material improvement is terminal without requiring deadband entry',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,1.4);assert.equal(result.evaluated.outcome,'IMPROVED');assert.equal(result.evaluated.metrics.action_effectiveness,1);});
test('V3 tiny jitter is NO_EFFECT rather than IMPROVED',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,1.9);assert.equal(result.evaluated.outcome,'NO_EFFECT');});
test('V3 wrong direction uses the immutable start error',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2.5);assert.equal(result.evaluated.outcome,'WRONG_DIRECTION');assert.equal(result.evaluated.episode?.start_error,2);assert.equal(result.evaluated.episode?.settled_error,2.5);});
test('V3 invalidates a lost causal response without counting a failed action',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);c.update(measurement(0,1,'IN_RANGE','TOO_LEFT'));c.update(measurement(300,2,'IN_RANGE','TOO_LEFT'));const lost={...measurement(500,3,'UNKNOWN','UNKNOWN',false,null,null),subject_state:'LOST',measurement_quality:'INVALID',fresh:false} as const;const result=c.update(lost);assert.equal(result.outcome,'INVALIDATED');assert.equal(result.metrics.action_effectiveness,null);assert.equal(result.metrics.invalidated_count,1);});
test('V3 READY has one path and latches post-ready output at zero',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);c.update(measurement(0,1,'IN_RANGE','IN_RANGE'));c.update(measurement(600,2,'IN_RANGE','IN_RANGE'));const ready=c.update(measurement(700,3,'IN_RANGE','IN_RANGE'));assert.equal(ready.ready,true);assert.equal(ready.stage,'READY_LATCHED');for(let i=0;i<5;i+=1)c.update(measurement(900+i*100,4+i,'TOO_CLOSE','TOO_LEFT'));const final=c.update(measurement(1500,10,'TOO_CLOSE','TOO_LEFT'));assert.equal(final.metrics.post_ready_ordinary,0);assert.equal(final.metrics.ordinary_action_count,0);});
test('V3 pauses after three consecutive valid failures and resumes on stable fresh input',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);let t=0;let v=1;for(let i=0;i<3;i+=1){const r=driveSettled(c,t,v,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2);t+=1600;v+=5;if(i===2)assert.equal(r.evaluated.stage,'PAUSED');}c.update(measurement(t,v,'IN_RANGE','TOO_LEFT'));const resumed=c.update(measurement(t+1200,v+1,'IN_RANGE','TOO_LEFT'));assert.equal(resumed.stage,'ALIGN_X');});
test('trace replay classification never fabricates missing semantic evidence',()=>{const legacy:TraceLikeRow[]=[0,400,900].map((timestamp,index)=>({timestamp,sequence:index+1,subject_present:true,center_x:.3,height_ratio:.35,velocity_x:0,velocity_scale:0,stable:index>0,target_x:.5,target_height:.35,delta_x:.2,delta_scale:0}));assert.equal(classifyTrace(legacy),'STRUCTURAL_ONLY');const replay=replayTraceV3(legacy,DEFAULT_TARGET);assert.equal(replay.summary.classification,'STRUCTURAL_ONLY');assert.equal(replay.summary.v3_stage_sequence.includes('ALIGN_X'),true);});
