import assert from 'node:assert/strict';import test from 'node:test';
import { resolveLiveConstraintsV01 } from '../control-v4/constraints.js';
import { HumanTargetRelativeServoV04 } from '../control-v4/controller.js';
import { V4_BROWSER_MATRIX, runV4BrowserScenario } from '../control-v4/browser-scenarios.js';
import { LIVE_TARGET_FIXTURES_V02 } from '../control-v4/targets.js';
import { v4ObservationFixture } from '../fixtures/control-v4/human-observations.js';
import { HumanObservationV02Projector } from '../control-v4/observation.js';
import { V4ScalarTraceRecorder } from '../control-v4/trace.js';
import type { StructuredPerceptionState } from '../perception/types.js';
import type { FramingMeasurement, LandmarkGroupEvidence, SemanticGroupName } from '../semantic-framing/types.js';

const upper=(t:number,v:number,overrides:Partial<Parameters<typeof v4ObservationFixture>[0]>={})=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'UPPER_BODY',scale_metric:'HEAD_TO_HIP',...overrides});
test('V4 HumanObservation has no target-relative judgments',()=>{const json=JSON.stringify(upper(0,1));assert.doesNotMatch(json,/TOO_LEFT|TOO_RIGHT|TOO_CLOSE|TOO_FAR|target_anchor|target_scale/);});
test('V4 target-relative X accepts left-third without fixed-center authority',()=>{const o=upper(0,1,{x:.33});assert.equal(resolveLiveConstraintsV01(o,LIVE_TARGET_FIXTURES_V02.LEFT_THIRD_UPPER_BODY).x_relation,'IN_RANGE');assert.equal(resolveLiveConstraintsV01(o,LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY).x_relation,'TOO_LOW');assert.equal(resolveLiveConstraintsV01(o,LIVE_TARGET_FIXTURES_V02.RIGHT_THIRD_UPPER_BODY).x_relation,'TOO_LOW');});
test('V4 same observation produces different target-relative scale states',()=>{const o=upper(0,1,{scale:.42});const near={...LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY,target_scale:.42} as const;const far={...near,target_scale:.62} as const;assert.equal(resolveLiveConstraintsV01(o,near).scale_relation,'IN_RANGE');assert.equal(resolveLiveConstraintsV01(o,far).scale_relation,'TOO_LOW');});
test('V4 required body uses explicit graph and BodyMode is summary only',()=>{const head=upper(0,1,{coverage:'HEAD_ONLY'});const c=resolveLiveConstraintsV01(head,LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);assert.equal(c.stage,'ACQUIRE_REQUIRED_BODY');assert.ok(c.missing_body_parts.includes('HIPS'));});
test('V4 899/901/long no-response never evaluates or reissues',()=>{const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);c.update(upper(0,1,{x:.3}));const issued=c.update(upper(300,2,{x:.3}));assert.equal(issued.action,'MOVE_RIGHT_SMALL');for(const [t,v] of [[1199,3],[1201,4],[5000,5]] as const){const s=c.update(upper(t,v,{x:.3}));assert.equal(s.active_episode?.response_observed,false);assert.equal(s.active_episode?.state,'WAIT_FOR_RESPONSE');assert.equal(s.active_episode?.outcome,null);assert.equal(s.metrics.causally_evaluable_actions,0);assert.equal(s.metrics.issued_actions,1);assert.equal(s.metrics.no_response_reissue_count,0);}const end=c.update(upper(6000,6,{x:.3}));assert.equal(end.metrics.no_response_actions,1);assert.equal(end.metrics.no_response_outcome_count,0);});
test('V4 passive drift is diagnostic-only and cannot reach target',()=>{const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);c.update(upper(0,1,{x:.3}));c.update(upper(300,2,{x:.3}));const drift=c.update(upper(700,3,{x:.5,x_motion:'STILL'}));assert.equal(drift.active_episode?.passive_relation_change,true);assert.equal(drift.active_episode?.response_observed,false);assert.equal(drift.active_episode?.outcome,null);assert.equal(drift.metrics.target_reached_count,0);});
test('V4 late response then settle is the only evaluable path',()=>{const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);c.update(upper(0,1,{x:.3}));c.update(upper(300,2,{x:.3}));c.update(upper(5000,3,{x:.3}));const moving=c.update(upper(5200,4,{x:.42,x_motion:'POSITIVE',stable:false}));assert.equal(moving.active_episode?.response_observed,true);c.update(upper(5500,5,{x:.5}));const done=c.update(upper(5900,6,{x:.5}));assert.equal(done.last_episode?.state,'EVALUATED');assert.equal(done.last_episode?.outcome,'TARGET_REACHED');assert.equal(done.metrics.responded_actions,1);assert.equal(done.metrics.causally_evaluable_actions,1);});
test('V4 response classifications require response and settled evidence',()=>{for(const [name,endX,expected] of [['IMPROVED',.4,'IMPROVED'],['NO_EFFECT',.305,'NO_EFFECT'],['WRONG',.2,'WRONG_DIRECTION']] as const){const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);c.update(upper(0,1,{x:.3}));c.update(upper(300,2,{x:.3}));c.update(upper(500,3,{x:endX,x_motion:'POSITIVE',stable:false}));c.update(upper(800,4,{x:endX}));const done=c.update(upper(1200,5,{x:endX}));assert.equal(done.last_episode?.outcome,expected,name);}});
test('V4 invalid measurement cancels but never invents an outcome',()=>{const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);c.update(upper(0,1,{x:.3}));c.update(upper(300,2,{x:.3}));const cancelled=c.update(upper(500,3,{present:false}));assert.equal(cancelled.last_episode?.state,'CANCELLED');assert.equal(cancelled.last_episode?.outcome,null);assert.equal(cancelled.metrics.invalidated_actions,1);assert.equal(cancelled.metrics.causally_evaluable_actions,0);});
test('V4 browser matrix covers six target/coverage combinations through ready',()=>{assert.equal(V4_BROWSER_MATRIX.length,6);for(const id of V4_BROWSER_MATRIX){const rows=runV4BrowserScenario(id);const stages=new Set(rows.map(r=>r.stage));assert.ok(stages.has('ACQUIRE_SUBJECT'),id);assert.ok(stages.has('ACQUIRE_REQUIRED_BODY'),id);assert.ok(stages.has('ADJUST_SCALE'),id);assert.ok(stages.has('ALIGN_PRIMARY_ANCHOR'),id);assert.equal(rows.at(-1)?.ready,true,id);assert.equal(rows.at(-1)?.metrics.no_response_reissue_count,0,id);}});

const evidence=(x:number,y:number,valid=true):LandmarkGroupEvidence=>({valid,bilateral_valid:valid,confidence:valid?.95:0,visible_count:valid?2:0,pair_center:valid?{x,y}:null,pair_width:valid?.15:null});
const semanticState=(timestamp_ms:number,sequence:number,present=true,reacquisition_count=0,bottomCrop=false):StructuredPerceptionState=>{const groups=Object.fromEntries((['HEAD_CORE','SHOULDERS','ELBOWS','WRISTS','HIPS','KNEES','ANKLES'] as SemanticGroupName[]).map(name=>[name,evidence(.33,{HEAD_CORE:.12,SHOULDERS:.24,ELBOWS:.34,WRISTS:.42,HIPS:.5,KNEES:.7,ANKLES:.91}[name])])) as FramingMeasurement['groups'];const framing={timestamp_ms,state_version:sequence,body_mode:'FULL_BODY',body_mode_confidence:.95,body_visibility:{mode:'FULL_BODY',confidence:.95,visible_groups:{head:true,shoulders:true,hips:true,knees:true,ankles:true},bilateral_groups:{shoulders:true,hips:true,knees:true,ankles:true},cropped_edges:{top:false,bottom:bottomCrop,left:false,right:false},candidate_mode:'FULL_BODY',candidate_since_ms:0,stable_mode_since_ms:0,body_mode_transition_count:0,body_mode_flicker_count:0},groups,anchor_x:.33,anchor_x_source:'SHOULDER_HIP_FUSION',scale:.8,scale_metric_type:'FULL_BODY_SCALE',scale_components:{},confidence:.95,uncertainty_x:.01,uncertainty_scale:.02,uncertainty_scale_components:{landmark_confidence:.05,component_disagreement:0,orientation_ambiguity:0,crop_ambiguity:bottomCrop?.3:0,temporal_variance:0},scale_validity_reason:'VALID',torso_orientation:'FRONTAL_OR_NEAR_FRONTAL',distance_proxy:{timestamp_ms,state_version:sequence,raw_value:.5,value:.5,source:'TORSO_COMPOSITE',confidence:.95,uncertainty:.02,valid:true,validity_reason:'VALID',velocity:0,filtered_velocity:0,body_mode:'FULL_BODY',measurement_age_ms:0},cropped_edges:{top:false,bottom:bottomCrop,left:false,right:false},measurement_age_ms:0,valid_for_precision_x:true,valid_for_precision_scale:true,velocity_x:0,velocity_scale:0,stable:true,filter_type:'ONE_EURO',display_box:null,raw_pose_box:null} as FramingMeasurement;return {timestamp_ms,sequence,coordinate_basis:'SENSOR_NORMALIZED_NON_MIRRORED',subject:{present,confidence:present?.95:0,center_x:present?.33:null,center_y:present?.5:null,width_ratio:present?.3:null,height_ratio:present?.8:null,velocity_x:0,velocity_y:0,velocity_scale:0,stable:true},measurement_age_ms:present?0:null,subject_loss_count:present?0:1,reacquisition_count,framing:present?framing:null};};
test('V4 observation projector locks, holds, loses, and reacquires without identity claims',()=>{const p=new HumanObservationV02Projector();assert.equal(p.project(semanticState(0,1)).subject_lock.state,'ACQUIRING');const locked=p.project(semanticState(400,2));assert.equal(locked.subject_lock.state,'LOCKED');assert.equal(locked.subject_lock.identity_claim,false);assert.equal(locked.subject_lock.multi_person_supported,false);assert.equal(p.project(semanticState(500,3,false)).subject_lock.state,'HELD');assert.equal(p.project(semanticState(1000,4,false)).subject_lock.state,'LOST');assert.equal(p.project(semanticState(1100,5,true,1)).subject_lock.state,'REACQUIRING');});
test('V4 observation projector emits semantic anchors and bounded crop evidence',()=>{const p=new HumanObservationV02Projector();p.project(semanticState(0,1));const normal=p.project(semanticState(400,2));assert.equal(normal.semantic_anchors.anchors.TORSO_CENTER?.x,.33);assert.equal(normal.semantic_anchors.coordinate_basis,'SENSOR_NORMALIZED_NON_MIRRORED');assert.equal(normal.semantic_anchors.mirror_applied_to_control,false);assert.equal(normal.body_visibility.feet_visible,true);const cropped=p.project(semanticState(800,3,true,0,true));assert.equal(cropped.body_visibility.feet_visible,false);assert.equal(cropped.body_visibility.feet_bottom_cropped,true);assert.ok(cropped.diagnostics.warnings.includes('BOTTOM_CROP_RISK'));});
test('V4 scalar trace is target-relative, observation-complete, and has no raw media or landmarks',()=>{const recorder=new V4ScalarTraceRecorder();const snapshots=runV4BrowserScenario('LEFT_THIRD_UPPER_BODY');snapshots.forEach(s=>recorder.append(s));const payload=JSON.parse(recorder.json({scenario:'fixture'}));assert.equal(payload.live_architecture,'V4');assert.equal(payload.raw_media,false);assert.equal(payload.rows.length,snapshots.length);assert.ok(payload.rows.some((r:{subject_lock:string})=>r.subject_lock==='LOST'));assert.ok(payload.rows.some((r:{required_body_satisfied:boolean})=>r.required_body_satisfied===false));assert.ok(payload.rows.some((r:{target_anchor_x:number})=>r.target_anchor_x===.33));assert.equal(payload.privacy.raw_video_upload,0);assert.doesNotMatch(JSON.stringify(payload),/raw_frame|image_data|landmark_data/i);});
