import assert from 'node:assert/strict';
import test from 'node:test';
import { DEFAULT_TARGET } from '../closed-loop/config.js';
import { HumanStepServoV3 } from '../control-v3/controller.js';
import { deriveLivePresentationStateV01 } from '../control-v3/presentation.js';
import { classifyTrace, replayTraceV3, type TraceLikeRow } from '../control-v3/replay.js';
import type { LiveMeasurementV3, V3FramingRelation, V3XRelation } from '../control-v3/types.js';
import { runV3BrowserScenario, V3_BROWSER_SCENARIOS } from '../control-v3/browser-scenarios.js';
import { V3HumanStepTraceRecorder } from '../control-v3/trace.js';
import { VisualGuidanceProjector } from '../visual-guidance/projector.js';
import { frame } from '../fixtures/closed-loop/trajectories.js';

const measurement=(timestamp_ms:number,state_version:number,framing_relation:V3FramingRelation,x_relation:V3XRelation,stable=true,framingError:number|null=framing_relation==='IN_RANGE'?0:2,xError:number|null=x_relation==='IN_RANGE'?0:2):LiveMeasurementV3=>Object.freeze({timestamp_ms,subject_state:'PRESENT',measurement_quality:stable?'GOOD':'MARGINAL',fresh:true,stable,framing_relation,x_relation,framing_motion:stable?'STILL':framing_relation==='TOO_CLOSE'?'FARTHER':'CLOSER',x_motion:stable?'STILL':x_relation==='TOO_LEFT'?'RIGHT':'LEFT',state_version,measurement_age_ms:0,diagnostics_ref:Object.freeze({measurement_id:`m${state_version}`,framing_error_normalized:framingError,x_error_normalized:xError,framing_position:framing_relation==='TOO_CLOSE'?1.2:framing_relation==='TOO_FAR'?.3:.52,x_position:x_relation==='TOO_LEFT'?.3:x_relation==='TOO_RIGHT'?.7:.5,framing_comparison_key:'FRAMING_V3:center-medium',x_comparison_key:'X_V3:center-medium',internal_body_mode:'UPPER_BODY',internal_scale_metric_type:'UPPER_BODY_SCALE',validity_reason:'TEST'})});
const driveSettled=(controller:HumanStepServoV3,start:number,version:number,framing:V3FramingRelation,x:V3XRelation,endFraming:V3FramingRelation,endX:V3XRelation,endFramingError:number|null=0,endXError:number|null=0)=>{
  const initial=controller.update(measurement(start,version,framing,x));
  const second=controller.update(measurement(start+300,version+1,framing,x));
  const issued=initial.action?initial:second;
  controller.update(measurement(start+500,version+2,endFraming,endX,false,endFramingError,endXError));
  controller.update(measurement(start+900,version+3,endFraming,endX,true,endFramingError,endXError));
  const evaluated=controller.update(measurement(start+1300,version+4,endFraming,endX,true,endFramingError,endXError));
  return {issued,evaluated};
};

test('V3 freezes combined order as FRAMING then ALIGN_X',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const framing=driveSettled(c,0,1,'TOO_CLOSE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2);assert.equal(framing.issued.action,'MOVE_FARTHER_SMALL');assert.equal(framing.evaluated.outcome,'TARGET_REACHED');const x=driveSettled(c,1600,6,'IN_RANGE','TOO_LEFT','IN_RANGE','IN_RANGE',0,0);assert.equal(x.issued.action,'MOVE_LEFT_SMALL');assert.equal(x.evaluated.outcome,'TARGET_REACHED');assert.deepEqual([framing.issued.episode?.stage,x.issued.episode?.stage],['FRAMING','ALIGN_X']);});
test('V3 human step has no predictive STOP or braking state',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const {issued,evaluated}=driveSettled(c,0,1,'IN_RANGE','TOO_RIGHT','IN_RANGE','IN_RANGE',0,0);assert.equal(issued.action,'MOVE_RIGHT_SMALL');assert.equal(evaluated.outcome,'TARGET_REACHED');assert.ok(!['BRAKING','WAITING_FOR_MOTION','TRACKING_MOTION'].includes(evaluated.stage));});
test('V3 material improvement is terminal without requiring deadband entry',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,1.4);assert.equal(result.evaluated.outcome,'IMPROVED');assert.equal(result.evaluated.metrics.action_effectiveness,1);});
test('V3 tiny jitter is NO_EFFECT rather than IMPROVED',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,1.9);assert.equal(result.evaluated.outcome,'NO_EFFECT');});
test('V3 wrong direction uses the immutable start error',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2.5);assert.equal(result.evaluated.outcome,'WRONG_DIRECTION');assert.equal(result.evaluated.episode?.start_error,2);assert.equal(result.evaluated.episode?.settled_error,2.5);});
test('V3 invalidates a lost causal response without counting a failed action',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);c.update(measurement(0,1,'IN_RANGE','TOO_LEFT'));c.update(measurement(300,2,'IN_RANGE','TOO_LEFT'));const lost={...measurement(500,3,'UNKNOWN','UNKNOWN',false,null,null),subject_state:'LOST',measurement_quality:'INVALID',fresh:false} as const;const result=c.update(lost);assert.equal(result.outcome,'INVALIDATED');assert.equal(result.metrics.action_effectiveness,null);assert.equal(result.metrics.invalidated_count,1);});
test('V3 READY has one path and latches post-ready output at zero',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);c.update(measurement(0,1,'IN_RANGE','IN_RANGE'));c.update(measurement(600,2,'IN_RANGE','IN_RANGE'));const ready=c.update(measurement(700,3,'IN_RANGE','IN_RANGE'));assert.equal(ready.ready,true);assert.equal(ready.stage,'READY_LATCHED');for(let i=0;i<5;i+=1)c.update(measurement(900+i*100,4+i,'TOO_CLOSE','TOO_LEFT'));const final=c.update(measurement(1500,10,'TOO_CLOSE','TOO_LEFT'));assert.equal(final.metrics.post_ready_ordinary,0);assert.equal(final.metrics.ordinary_action_count,0);});
test('V3 pauses after three distinct failed human responses and resumes on stable fresh input',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);let t=0;let v=1;for(let i=0;i<3;i+=1){const r=driveSettled(c,t,v,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2);if(i===2)assert.equal(r.evaluated.stage,'PAUSED');else c.update(measurement(t+1450,v+5,'IN_RANGE','TOO_LEFT',false,0,1.8));t+=1700;v+=6;}c.update(measurement(t,v,'IN_RANGE','TOO_LEFT'));const resumed=c.update(measurement(t+1200,v+1,'IN_RANGE','TOO_LEFT'));assert.equal(resumed.stage,'ALIGN_X');});
test('trace replay classification never fabricates missing semantic evidence',()=>{const legacy:TraceLikeRow[]=[0,400,900].map((timestamp,index)=>({timestamp,sequence:index+1,subject_present:true,center_x:.3,height_ratio:.35,velocity_x:0,velocity_scale:0,stable:index>0,target_x:.5,target_height:.35,delta_x:.2,delta_scale:0}));assert.equal(classifyTrace(legacy),'STRUCTURAL_ONLY');const replay=replayTraceV3(legacy,DEFAULT_TARGET);assert.equal(replay.summary.classification,'STRUCTURAL_ONLY');assert.equal(replay.summary.v3_stage_sequence.includes('ALIGN_X'),true);});
test('V3 deterministic browser gate covers every required route',()=>{assert.equal(V3_BROWSER_SCENARIOS.length,11);for(const name of V3_BROWSER_SCENARIOS)assert.ok(runV3BrowserScenario(name).length>0,name);});
test('V3 browser paths are fixed and READY is terminal',()=>{const framing=runV3BrowserScenario('FRAMING_ONLY_BAD');assert.equal(framing.find(s=>s.action)?.stage,'FRAMING');assert.equal(framing.at(-1)?.ready,true);const x=runV3BrowserScenario('X_ONLY_BAD');assert.equal(x.find(s=>s.action)?.stage,'ALIGN_X');assert.equal(x.at(-1)?.ready,true);const both=runV3BrowserScenario('BOTH_BAD');assert.deepEqual(both.filter(s=>s.action).map(s=>s.stage),['FRAMING','ALIGN_X']);assert.equal(both.at(-1)?.ready,true);const already=runV3BrowserScenario('ALREADY_SATISFIED');assert.equal(already.at(-1)?.ready,true);assert.equal(already.at(-1)?.metrics.ordinary_action_count,0);const post=runV3BrowserScenario('POST_READY_MOVEMENT').at(-1)!;assert.equal(post.metrics.post_ready_ordinary,0);assert.equal(post.metrics.ordinary_action_count,0);});
test('V3 browser gate exposes causal terminal variants',()=>{assert.equal(runV3BrowserScenario('NO_EFFECT').at(-1)?.outcome,'NO_EFFECT');assert.equal(runV3BrowserScenario('WRONG_DIRECTION').at(-1)?.outcome,'WRONG_DIRECTION');assert.equal(runV3BrowserScenario('MEASUREMENT_UNCERTAIN').at(-1)?.stage,'ACQUIRE');assert.equal(runV3BrowserScenario('SUBJECT_LOST').at(-1)?.outcome,'INVALIDATED');assert.equal(runV3BrowserScenario('REACQUIRE').at(-1)?.outcome,'TARGET_REACHED');assert.notEqual(deriveLivePresentationStateV01(runV3BrowserScenario('INVALIDATED_RECOVERY').at(-1)!).state,'ACQUIRING');});
test('V3 runtime trace is scalar-only and records human-step causal timestamps',()=>{const snapshots=runV3BrowserScenario('X_ONLY_BAD');const recorder=new V3HumanStepTraceRecorder();snapshots.forEach(s=>recorder.append(s));const payload=JSON.parse(recorder.json({scenario_label:'X_ONLY_BAD',generated_at_iso:'2026-08-27T00:00:00.000Z'}));assert.equal(payload.control_policy,'V3');assert.equal(payload.raw_media,false);assert.equal(payload.episodes.length,1);assert.equal(payload.episodes[0].stage,'ALIGN_X');assert.equal(payload.episodes[0].outcome,'TARGET_REACHED');assert.ok(payload.episodes[0].movement_started_at!==null);assert.ok(payload.episodes[0].settle_detected_at!==null);assert.equal(payload.privacy.raw_video_upload,0);assert.doesNotMatch(JSON.stringify(payload),/landmark|raw_frame|image_data/i);});
test('V3 NO_EFFECT retry uses newer stable evidence without uncommanded motion',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const result=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2);assert.equal(result.evaluated.outcome,'NO_EFFECT');const sameVersion=c.update(measurement(1600,5,'IN_RANGE','TOO_LEFT'));assert.equal(sameVersion.action,null);const unstable=c.update(measurement(1700,6,'IN_RANGE','TOO_LEFT',false,0,2));assert.equal(unstable.action,null);const reissued=c.update(measurement(1800,7,'IN_RANGE','TOO_LEFT',true,0,2));assert.equal(reissued.action,'MOVE_LEFT_SMALL');assert.equal(reissued.retry_action_candidate,'MOVE_LEFT_SMALL');assert.equal(reissued.active_action,'MOVE_LEFT_SMALL');});

test('V3 WRONG_DIRECTION retry derives direction from the current relation',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const first=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2.5);assert.equal(first.evaluated.outcome,'WRONG_DIRECTION');const retry=c.update(measurement(1600,6,'IN_RANGE','TOO_RIGHT',true,0,2.5));assert.equal(retry.action,'MOVE_RIGHT_SMALL');assert.equal(retry.retry_action_candidate,'MOVE_RIGHT_SMALL');assert.notEqual(retry.action,first.issued.action);});

test('V3 presentation matrix is driven by current controller truth',()=>{
  const disarmed=new HumanStepServoV3(DEFAULT_TARGET).update(measurement(0,1,'UNKNOWN','UNKNOWN',false,null,null));assert.equal(deriveLivePresentationStateV01(disarmed).state,'DISARMED');
  const acquireController=new HumanStepServoV3(DEFAULT_TARGET);acquireController.arm(0);const lost={...measurement(0,1,'UNKNOWN','UNKNOWN',false,null,null),subject_state:'LOST',measurement_quality:'INVALID',fresh:false} as const;assert.equal(deriveLivePresentationStateV01(acquireController.update(lost)).state,'ACQUIRING');
  const framingController=new HumanStepServoV3(DEFAULT_TARGET);framingController.arm(0);framingController.update(measurement(0,1,'TOO_CLOSE','IN_RANGE'));const framingIssued=framingController.update(measurement(300,2,'TOO_CLOSE','IN_RANGE'));assert.equal(deriveLivePresentationStateV01(framingIssued).state,'ACTION_REQUIRED');const waiting=framingController.update(measurement(400,3,'TOO_CLOSE','IN_RANGE'));assert.equal(deriveLivePresentationStateV01(waiting).state,'WAITING_FOR_RESPONSE');const moving=framingController.update(measurement(500,4,'TOO_CLOSE','IN_RANGE',false,1.7,0));assert.equal(deriveLivePresentationStateV01(moving).state,'WAITING_FOR_SETTLE');
  const transitionController=new HumanStepServoV3(DEFAULT_TARGET);transitionController.arm(0);const transition=driveSettled(transitionController,0,1,'TOO_CLOSE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2).evaluated;const transitionPresentation=deriveLivePresentationStateV01(transition);assert.equal(transitionPresentation.state,'STAGE_TRANSITION');assert.match(transitionPresentation.primary_copy_zh,/距离合适/);
  const improvedController=new HumanStepServoV3(DEFAULT_TARGET);improvedController.arm(0);const improved=driveSettled(improvedController,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,1.4).evaluated;assert.equal(deriveLivePresentationStateV01(improved).state,'EVALUATING');
  const verifyController=new HumanStepServoV3(DEFAULT_TARGET);verifyController.arm(0);const verifying=verifyController.update(measurement(0,1,'IN_RANGE','IN_RANGE'));assert.equal(deriveLivePresentationStateV01(verifying).state,'VERIFYING_READY');const ready=verifyController.update(measurement(600,2,'IN_RANGE','IN_RANGE'));assert.equal(deriveLivePresentationStateV01(ready).state,'READY');
});

test('V3 PAUSED presentation is explicit and contains no corrective action',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);let evaluated;let t=0;let v=1;for(let i=0;i<3;i+=1){evaluated=driveSettled(c,t,v,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2).evaluated;if(i<2)c.update(measurement(t+1600,v+5,'IN_RANGE','TOO_LEFT'));t+=1900;v+=6;}const p=deriveLivePresentationStateV01(evaluated!);assert.equal(p.state,'PAUSED');assert.equal(p.action,null);assert.match(p.primary_copy_zh,/站稳/);});

test('V3 presentation suppresses sticky outcomes and historical actions',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const evaluated=driveSettled(c,0,1,'TOO_CLOSE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2).evaluated;const p=deriveLivePresentationStateV01(evaluated);assert.equal(p.state,'STAGE_TRANSITION');assert.doesNotMatch(p.primary_copy_zh,/TARGET_REACHED|IMPROVED|NO_EFFECT|WRONG_DIRECTION|INVALIDATED/);assert.doesNotMatch(p.primary_copy_zh,/退后|靠近/);const recovered=c.update(measurement(1600,6,'IN_RANGE','TOO_LEFT'));const recoveredP=deriveLivePresentationStateV01(recovered);assert.doesNotMatch(recoveredP.primary_copy_zh,/INVALIDATED|TARGET_REACHED|退后|靠近/);});

test('V3 retry presentation requires a newly issued ControlEpoch',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const evaluated=driveSettled(c,0,1,'IN_RANGE','TOO_LEFT','IN_RANGE','TOO_LEFT',0,2).evaluated;const before=deriveLivePresentationStateV01(evaluated);assert.equal(before.state,'EVALUATING');assert.equal(evaluated.active_action,null);const retry=c.update(measurement(1600,6,'IN_RANGE','TOO_LEFT'));const p=deriveLivePresentationStateV01(retry);assert.equal(p.state,'RETRY_REQUIRED');assert.equal(retry.active_action,'MOVE_LEFT_SMALL');assert.equal(retry.episode?.control_epoch.state_version,6);assert.match(p.primary_copy_zh,/左侧/);});

test('V3 normal user copy never exposes internal Episode outcomes',()=>{for(const name of V3_BROWSER_SCENARIOS){for(const snapshot of runV3BrowserScenario(name)){const p=deriveLivePresentationStateV01(snapshot);assert.doesNotMatch(p.primary_copy_zh,/TARGET_REACHED|IMPROVED|NO_EFFECT|WRONG_DIRECTION|INVALIDATED/,name);assert.doesNotMatch(p.overlay_copy_zh,/TARGET_REACHED|IMPROVED|NO_EFFECT|WRONG_DIRECTION|INVALIDATED/,name);}}});
test('V3 visual projection keeps subject, target, and acceptable boxes',()=>{const c=new HumanStepServoV3(DEFAULT_TARGET);c.arm(0);const snapshot=c.update(measurement(0,1,'IN_RANGE','TOO_LEFT'));const state=frame(0,.3,.35,true);const visual=new VisualGuidanceProjector().updateV3(state,snapshot,DEFAULT_TARGET);assert.ok(visual.tracked_subject_box);assert.ok(visual.target_box);assert.ok(visual.acceptable_zone);assert.equal(visual.braking,false);});
