import assert from 'node:assert/strict';
import test from 'node:test';
import { HumanTargetRelativeServoV04 } from '../control-v4/controller.js';
import { deriveV4Presentation, type V4Presentation } from '../control-v4/presentation.js';
import { LIVE_TARGET_FIXTURES_V02, V4_FRAMING_TARGET_FIXTURES_V01 } from '../control-v4/targets.js';
import { VoiceCueEngineV01 } from '../control-v4/voice-engine.js';
import { FakeVoiceOutputAdapterV01 } from '../control-v4/voice-fake-adapter.js';
import { BrowserSpeechSynthesisVoiceAdapterV01 } from '../control-v4/voice-browser-adapter.js';
import { runVoiceBrowserSmokeV01 } from '../control-v4/voice-browser-scenarios.js';
import { v4ObservationFixture } from '../fixtures/control-v4/human-observations.js';
import type { VoiceCueContextV01, VoicePresentationCueV01, VoiceSemanticIdV01 } from '../control-v4/voice-types.js';

let now = 1000;
const context = (overrides: Partial<VoiceCueContextV01> = {}): VoiceCueContextV01 => ({ now, session_revision: 1, armed: true, target_id: 'CENTER_UPPER_BODY', current_framing_ready: false, trial_success_latched: false, ...overrides });
const cue = (semantic: VoiceSemanticIdV01, phrase: string, epoch: string | null = null, priority: 1|2|3|4 = 2): Readonly<VoicePresentationCueV01> => Object.freeze({ enabled:true, cue_id:`voice:${semantic}`, semantic_id:semantic, phrase_key:semantic, phrase_text:phrase, priority, interrupt_policy:priority===1?'INTERRUPT_LOWER':'REPLACE_STALE', repeat_policy:epoch?'ONCE_PER_CONTROL_EPOCH':'ONCE_PER_SEMANTIC_ENTRY', control_epoch_id:epoch, expires_at:now+1800 });
const model = (voice: Readonly<VoicePresentationCueV01>|null, state: V4Presentation['state']='ACTION_REQUIRED', action: V4Presentation['action']=null, ready=false, trial=false): Readonly<V4Presentation> => Object.freeze({ presentation_version:'LivePresentationModelV03', state, primary_copy_zh:voice?.phrase_text??'silent', overlay_copy_zh:voice?.phrase_text??'silent', voice_copy_zh:voice?.phrase_text??null, voice, action, display_axis_sign:0, current_framing_ready:ready, trial_success_latched:trial });
const engine = (available=true) => { const adapter=new FakeVoiceOutputAdapterV01(available,()=>now); const scheduler=new VoiceCueEngineV01(adapter,{cooldown_ms:0}); scheduler.prepareFromUserGesture(); return {adapter,scheduler}; };

test('05I acquire phrase derives only after armed subject acquisition',()=>{const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);const p=deriveV4Presentation(c.update(v4ObservationFixture({timestamp_ms:0,state_version:1,present:false})));assert.equal(p.voice?.semantic_id,'ACQUIRE_SUBJECT');assert.equal(p.voice?.phrase_text,'站到画面里');});

test('05I subject left and right voice follow existing physical mapper, not preview mirror',()=>{for(const [x,expected,phrase] of [[.7,'SUBJECT_RIGHT_SMALL','往你自己的右边一点'],[.3,'SUBJECT_LEFT_SMALL','往你自己的左边一点']] as const){const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);const input=(t:number,v:number)=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'UPPER_BODY',scale_metric:'HEAD_TO_HIP',x});c.update(input(0,1),{camera_facing:'FRONT',preview_mirror_state:'MIRRORED',shooting_relation:'SUBJECT_FACING_CAMERA'});const p=deriveV4Presentation(c.update(input(300,2),{camera_facing:'FRONT',preview_mirror_state:'MIRRORED',shooting_relation:'SUBJECT_FACING_CAMERA'}));assert.equal(p.voice?.semantic_id,expected);assert.equal(p.voice?.phrase_text,phrase);}});

test('05I closer and farther phrases are not swapped',()=>{for(const [scale,semantic,phrase] of [[.2,'MOVE_CLOSER_SMALL','靠近一点'],[.62,'MOVE_FARTHER_SMALL','退后一点']] as const){const c=new HumanTargetRelativeServoV04(LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY);c.arm(0);const input=(t:number,v:number)=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'UPPER_BODY',scale_metric:'HEAD_TO_HIP',scale});c.update(input(0,1));const p=deriveV4Presentation(c.update(input(300,2)));assert.equal(p.voice?.semantic_id,semantic);assert.equal(p.voice?.phrase_text,phrase);}});

test('05I ordinary cue emits at most once per ControlEpoch and WAIT_FOR_RESPONSE is silent',()=>{const {adapter,scheduler}=engine();const ordinary=model(cue('SUBJECT_LEFT_SMALL','往你自己的左边一点','1:1'), 'ACTION_REQUIRED','MOVE_LEFT_SMALL');scheduler.update(ordinary,context());scheduler.update(ordinary,context());assert.equal(adapter.spoken.length,1);assert.equal(scheduler.snapshot().voice_cue_requested,1);scheduler.update(model(null,'WAITING_FOR_RESPONSE','MOVE_LEFT_SMALL'),context());assert.equal(adapter.spoken.length,1);});

test('05I response does not reissue direction and settle cancels stale movement',()=>{const {adapter,scheduler}=engine();scheduler.update(model(cue('SUBJECT_RIGHT_SMALL','往你自己的右边一点','1:2'),'ACTION_REQUIRED','MOVE_RIGHT_SMALL'),context());scheduler.update(model(null,'WAITING_FOR_RESPONSE','MOVE_RIGHT_SMALL'),context());now+=100;scheduler.update(model(cue('HOLD_STILL','好，站定',null,1),'WAITING_FOR_SETTLE'),context());assert.equal(adapter.spoken.map(item=>item.cue.semantic_id).join(','),'SUBJECT_RIGHT_SMALL,HOLD_STILL');assert.ok(adapter.cancelled.some(id=>id.includes('SUBJECT_RIGHT_SMALL')));});

test('05I VERIFY speaks once per semantic entry',()=>{const {adapter,scheduler}=engine();const verify=model(cue('VERIFY','很好，保持一下',null,3),'VERIFYING_READY');scheduler.update(verify,context());scheduler.update(verify,context());scheduler.update(model(null,'WAITING_FOR_RESPONSE'),context());scheduler.update(verify,context());assert.equal(adapter.spoken.filter(item=>item.cue.semantic_id==='VERIFY').length,2);});

test('05I READY speaks once only from current READY transition',()=>{const {adapter,scheduler}=engine();const ready=model(cue('CURRENT_READY_ENTER','好，就这里，可以拍了',null,1),'READY',null,true,true);scheduler.update(ready,context({current_framing_ready:true,trial_success_latched:true}));scheduler.update(ready,context({current_framing_ready:true,trial_success_latched:true}));assert.equal(adapter.spoken.length,1);const historicalOnly=model(null,'ACQUIRING',null,false,true);scheduler.update(historicalOnly,context({current_framing_ready:false,trial_success_latched:true}));assert.equal(adapter.spoken.length,1);assert.ok(adapter.cancelled.some(id=>id.includes('CURRENT_READY_ENTER')));});

test('05I stale READY is cancelled and no ordinary action is emitted while READY remains true',()=>{const {adapter,scheduler}=engine();scheduler.update(model(cue('CURRENT_READY_ENTER','好，就这里，可以拍了',null,1),'READY',null,true,true),context({current_framing_ready:true,trial_success_latched:true}));scheduler.update(model(null,'READY',null,true,true),context({current_framing_ready:true,trial_success_latched:true}));assert.equal(adapter.spoken.length,1);scheduler.update(model(null,'ACQUIRING',null,false,true),context({current_framing_ready:false,trial_success_latched:true}));assert.equal(scheduler.snapshot().voice_suppression_reason,'STALE_READY');});

test('05I target rearm, new session and disarm cancel stale cues',()=>{const {adapter,scheduler}=engine();const ordinary=model(cue('MOVE_CLOSER_SMALL','靠近一点','1:1'),'ACTION_REQUIRED','MOVE_CLOSER_SMALL');scheduler.update(ordinary,context());scheduler.update(ordinary,context({session_revision:2}));scheduler.update(ordinary,context({session_revision:2,target_id:'LEFT_THIRD_UPPER_BODY'}));scheduler.update(model(null,'DISARMED'),context({session_revision:2,target_id:'LEFT_THIRD_UPPER_BODY',armed:false}));assert.ok(adapter.cancelled.length>=1);assert.equal(scheduler.snapshot().voice_new_control_epochs,0);});

test('05I Voice OFF cancels audio without mutating presentation',()=>{const {adapter,scheduler}=engine();const presentation=model(cue('MOVE_FARTHER_SMALL','退后一点','1:9'),'ACTION_REQUIRED','MOVE_FARTHER_SMALL');scheduler.update(presentation,context());scheduler.setEnabled(false);scheduler.update(presentation,context());assert.equal(adapter.spoken.length,1);assert.equal(scheduler.snapshot().voice_enabled,false);assert.equal(presentation.action,'MOVE_FARTHER_SMALL');assert.equal(presentation.primary_copy_zh,'退后一点');});

test('05I unavailable adapter preserves graceful silent fallback',()=>{const {adapter,scheduler}=engine(false);scheduler.update(model(cue('ACQUIRE_SUBJECT','站到画面里',null,3),'ACQUIRING'),context());assert.equal(adapter.spoken.length,0);assert.equal(scheduler.snapshot().voice_available,false);assert.equal(scheduler.snapshot().voice_state,'UNAVAILABLE');});

test('05I telemetry is scalar-only and all control/provider mutation counters remain zero',()=>{const {scheduler}=engine();scheduler.update(model(cue('SUBJECT_LEFT_SMALL','往你自己的左边一点','1:1'),'ACTION_REQUIRED','MOVE_LEFT_SMALL'),context());const telemetry=scheduler.snapshot();assert.equal(telemetry.voice_provider_calls,0);assert.equal(telemetry.voice_audio_upload,0);assert.equal(telemetry.voice_audio_recording,0);assert.equal(telemetry.voice_new_control_epochs,0);assert.equal(telemetry.voice_outcome_mutations,0);assert.equal(telemetry.voice_response_gate_mutations,0);assert.equal(telemetry.voice_ready_mutations,0);assert.doesNotMatch(JSON.stringify(telemetry),/audio_data|raw_audio|recording_blob/);});

test('05I browser adapter reports unavailable without browser speech APIs',()=>{const adapter=new BrowserSpeechSynthesisVoiceAdapterV01({speechSynthesis:undefined,SpeechSynthesisUtterance:undefined,now:()=>0});assert.equal(adapter.isAvailable(),false);adapter.prepareFromUserGesture();adapter.setEnabled(false);adapter.dispose();});

test('05I 05G framing READY semantics remain controller-owned',()=>{const lastTarget=V4_FRAMING_TARGET_FIXTURES_V01.HEAD_SHOULDERS_CENTER;const c=new HumanTargetRelativeServoV04(lastTarget);c.arm(0);const input=(t:number,v:number)=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'HEAD_SHOULDERS',scale_metric:'HEAD_SHOULDER_SCALE',scale:lastTarget.target_scale,x:lastTarget.target_anchor_x,head_y:(lastTarget.target_anchor_y??.5)-.12});c.update(input(0,1));c.update(input(300,2));c.update(input(600,3));const ready=c.update(input(900,4));assert.equal(ready.current_framing_ready,true);assert.equal(deriveV4Presentation(ready).voice?.semantic_id,'CURRENT_READY_ENTER');});
test('05I deterministic browser smoke covers cue order, stale cancellation and Voice OFF',()=>{const result=runVoiceBrowserSmokeV01();assert.equal(result.pass,true);assert.deepEqual(result.cue_sequence,['SUBJECT_LEFT_SMALL','HOLD_STILL','CURRENT_READY_ENTER']);assert.equal(result.provider_calls,0);});
