import {strict as assert} from 'node:assert'
import {test} from 'node:test'
import {advanceConfirmedCaptureToFinal,advanceNewSessionToShoot,fallbackVisible,userVisibleStage} from '../src/product/simplifiedFlow'
import {DEFAULT_USER_PREFERENCES,effectivePreferences,loadPreferences,resetSessionOverride,savePreferences} from '../src/product/userPreferences'

const session=(stage:string,candidates:Array<any>=[])=>({session_id:'session-test',workflow_stage:stage,candidates})

test('preferences save and reload through the frontend-only storage port',async()=>{let stored:unknown;const storage={read:async()=>stored,write:async(value:unknown)=>{stored=value}};const saved=await savePreferences(storage,{...DEFAULT_USER_PREFERENCES,voice_guidance_enabled:false});assert.equal(saved.voice_guidance_enabled,false);assert.equal((await loadPreferences(storage)).voice_guidance_enabled,false)})
test('session override resets and does not leak to a new session',()=>{const changed=effectivePreferences(DEFAULT_USER_PREFERENCES,{camera_facing_default:'user',haptic_enabled:false});assert.equal(changed.camera_facing_default,'user');assert.deepEqual(resetSessionOverride(),{});assert.equal(effectivePreferences(DEFAULT_USER_PREFERENCES,resetSessionOverride()).camera_facing_default,'environment')})
test('quick settings override only presentation preferences',()=>{const changed=effectivePreferences(DEFAULT_USER_PREFERENCES,{composition_grid_enabled:false});assert.equal(changed.composition_grid_enabled,false);assert.equal(changed.shooting_relation_default,'FRIEND')})
test('four user-visible stages preserve the internal workflow',()=>{assert.equal(userVisibleStage('ENTRY'),'START');assert.equal(userVisibleStage('REALITY'),'SHOOT');assert.equal(userVisibleStage('QA'),'REVIEW');assert.equal(userVisibleStage('FINAL'),'FINAL')})
test('conditional import fallback appears only after need or request',()=>{assert.equal(fallbackVisible(false,false),false);assert.equal(fallbackVisible(true,false),true);assert.equal(fallbackVisible(false,true),true)})
test('new session auto advance calls existing actions in legal order',async()=>{const order:string[]=[];const stages=['SHOOTING_RELATION_DEVICE_MODE','REALITY','TARGET','TARGET','SHOT','LIVE','CAPTURE'];let index=0;const run=async(action:string)=>{order.push(action);const next=stages[index++];return session(next,next==='TARGET'&&index===4?[{kind:'TARGET',candidate_id:'target-cinematic'}]:[])};const result=await advanceNewSessionToShoot(session('ENTRY'),DEFAULT_USER_PREFERENCES,run);assert.equal(result.status,'READY');assert.equal(result.session.workflow_stage,'CAPTURE');assert.deepEqual(order,['SELECT_SHOOTING_RELATION','CONFIRM_DEVICE_MODE','ACCEPT_REALITY','GENERATE_TARGETS','SELECT_TARGET','ACCEPT_SHOT_DIRECTION','ENTER_CAPTURE_WINDOW'])})
test('auto advance stops at the last committed stage and exposes failure recovery',async()=>{let calls=0;const result=await advanceNewSessionToShoot(session('ENTRY'),DEFAULT_USER_PREFERENCES,async()=>{calls+=1;if(calls===2)throw new Error('NETWORK');return session('SHOOTING_RELATION_DEVICE_MODE')});assert.equal(result.status,'STOPPED');assert.equal(result.session.workflow_stage,'SHOOTING_RELATION_DEVICE_MODE');assert.deepEqual(result.actions,['SELECT_SHOOTING_RELATION'])})
test('confirmed capture enters Fine Tune by default before Final actions',async()=>{const order:string[]=[];const run=async(action:string)=>{order.push(action);return session(action==='ACCEPT'?'REALITY_PLUS':'FINE_TUNE')};const result=await advanceConfirmedCaptureToFinal(session('QA'),DEFAULT_USER_PREFERENCES,run);assert.equal(result.session.workflow_stage,'FINE_TUNE');assert.deepEqual(order,['ACCEPT','ACCEPT_REALITY_PLUS'])})
test('auto processing can be disabled without mutating workflow',async()=>{let called=false;const result=await advanceConfirmedCaptureToFinal(session('QA'),{...DEFAULT_USER_PREFERENCES,auto_processing_enabled:false},async()=>{called=true;return session('FINAL')});assert.equal(called,false);assert.equal(result.session.workflow_stage,'QA')})
