import { OneEuroFilter } from './filters.js';
import type { BodyMode, BodyVisibilityState, DistanceProxyMeasurement, FramingMeasurement, ScaleValidityReason, SemanticRawMeasurement } from './types.js';

const variance=(values:readonly number[]):number=>{if(values.length<2)return 0;const mean=values.reduce((s,v)=>s+v,0)/values.length;return values.reduce((s,v)=>s+(v-mean)**2,0)/(values.length-1);};
const clamp=(value:number,min=0,max=1):number=>Math.min(max,Math.max(min,value));

export class SemanticFramingTracker {
  private committed:BodyMode='PARTIAL_OR_AMBIGUOUS'; private candidate:BodyMode='PARTIAL_OR_AMBIGUOUS'; private candidateSince=0; private stableModeSince=0; private transitions=0; private flickers=0;
  private anchorFilter=new OneEuroFilter(); private scaleFilter=new OneEuroFilter(); private distanceFilter=new OneEuroFilter(.35,4,1); private lastTimestamp:number|null=null; private lastAnchor:number|null=null; private lastScale:number|null=null; private lastDistance:number|null=null; private lastRawDistance:number|null=null; private lastMovementAt:number|null=null; private last:FramingMeasurement|null=null; private anchorHistory:number[]=[]; private scaleHistory:number[]=[];
  constructor(private readonly persistenceMs=400,private readonly lossHoldMs=250){}
  reset():void{this.committed=this.candidate='PARTIAL_OR_AMBIGUOUS';this.candidateSince=this.stableModeSince=this.transitions=this.flickers=0;this.anchorFilter.reset();this.scaleFilter.reset();this.distanceFilter.reset();this.lastTimestamp=this.lastMovementAt=null;this.lastAnchor=this.lastScale=this.lastDistance=this.lastRawDistance=null;this.last=null;this.anchorHistory=[];this.scaleHistory=[];}
  update(raw:SemanticRawMeasurement|null,timestampMs:number,stateVersion:number):FramingMeasurement|null {
    if(!raw){if(this.last&&timestampMs-this.last.timestamp_ms<=this.lossHoldMs)return {...this.last,state_version:stateVersion,measurement_age_ms:timestampMs-this.last.timestamp_ms,valid_for_precision_x:false,valid_for_precision_scale:false,scale_validity_reason:'REACQUISITION_BARRIER',distance_proxy:{...this.last.distance_proxy,state_version:stateVersion,measurement_age_ms:timestampMs-this.last.timestamp_ms,valid:false,validity_reason:'REACQUISITION_BARRIER'},stable:false};return null;}
    this.updateMode(raw.candidate_mode,timestampMs); const scaleRaw=raw.scale_by_mode[this.committed]??null; const modeChanged=this.last?.body_mode!==undefined&&this.last.body_mode!==this.committed;
    if(modeChanged){this.scaleFilter.reset(scaleRaw?.value??undefined,timestampMs);this.lastScale=scaleRaw?.value??null;}
    const anchor=raw.anchor_x===null?null:this.anchorFilter.filter(raw.anchor_x,timestampMs); const scale=scaleRaw?.value===null||scaleRaw?.value===undefined?null:this.scaleFilter.filter(scaleRaw.value,timestampMs);const distanceRaw=raw.distance_proxy.value;const distance=distanceRaw===null?null:this.distanceFilter.filter(distanceRaw,timestampMs);
    const dt=this.lastTimestamp===null?.125:Math.max((timestampMs-this.lastTimestamp)/1000,.001); const vx=anchor===null||this.lastAnchor===null?0:(anchor-this.lastAnchor)/dt; const vs=scale===null||this.lastScale===null||modeChanged?0:(scale-this.lastScale)/dt;const rawDistanceVelocity=distanceRaw===null||this.lastRawDistance===null?0:(distanceRaw-this.lastRawDistance)/dt;const filteredDistanceVelocity=distance===null||this.lastDistance===null?0:(distance-this.lastDistance)/dt;
    this.lastTimestamp=timestampMs;if(anchor!==null)this.lastAnchor=anchor;if(scale!==null)this.lastScale=scale;if(distance!==null)this.lastDistance=distance;if(distanceRaw!==null)this.lastRawDistance=distanceRaw; if(anchor!==null){this.anchorHistory.push(anchor);if(this.anchorHistory.length>8)this.anchorHistory.shift();} if(scale!==null){this.scaleHistory.push(scale);if(this.scaleHistory.length>8)this.scaleHistory.shift();}
    const moving=Math.abs(vx)>.08||Math.abs(vs)>.08;if(moving||this.lastMovementAt===null)this.lastMovementAt=timestampMs;const stable=!moving&&timestampMs-(this.lastMovementAt??timestampMs)>=400;
    const ux=clamp(raw.anchor_x_uncertainty+Math.sqrt(variance(this.anchorHistory)));const temporalScale=clamp(Math.sqrt(variance(this.scaleHistory))*4);const scaleComponents={landmark_confidence:scaleRaw?.uncertainty_components.landmark_confidence??1,component_disagreement:scaleRaw?.uncertainty_components.component_disagreement??1,orientation_ambiguity:scaleRaw?.uncertainty_components.orientation_ambiguity??1,crop_ambiguity:scaleRaw?.uncertainty_components.crop_ambiguity??0,temporal_variance:temporalScale};const us=clamp(scaleComponents.landmark_confidence*.35+scaleComponents.component_disagreement*.15+scaleComponents.orientation_ambiguity*.3+scaleComponents.crop_ambiguity*.1+temporalScale*.1); const compatibleMode=!['HEAD_ONLY','PARTIAL_OR_AMBIGUOUS'].includes(this.committed);
    let scaleValidityReason:ScaleValidityReason='VALID';if(!compatibleMode)scaleValidityReason='BODY_MODE_INCOMPATIBLE';else if(scale===null||!scaleRaw?.metric_type)scaleValidityReason='METRIC_FAMILY_UNAVAILABLE';else if(us>.45)scaleValidityReason='UNCERTAINTY_TOO_HIGH';
    const validScale=scaleValidityReason==='VALID';const distanceProxy:DistanceProxyMeasurement={timestamp_ms:timestampMs,state_version:stateVersion,raw_value:distanceRaw,value:distance,source:raw.distance_proxy.source,confidence:raw.distance_proxy.confidence,uncertainty:raw.distance_proxy.uncertainty,valid:raw.distance_proxy.valid&&distance!==null,validity_reason:raw.distance_proxy.validity_reason,velocity:rawDistanceVelocity,filtered_velocity:filteredDistanceVelocity,body_mode:this.committed,measurement_age_ms:0};
    const visibility:BodyVisibilityState={mode:this.committed,confidence:raw.candidate_mode===this.committed?raw.candidate_confidence:Math.max(0,raw.candidate_confidence*.75),visible_groups:{head:raw.groups.HEAD_CORE.valid,shoulders:raw.groups.SHOULDERS.valid,hips:raw.groups.HIPS.valid,knees:raw.groups.KNEES.valid,ankles:raw.groups.ANKLES.valid},bilateral_groups:{shoulders:raw.groups.SHOULDERS.bilateral_valid,hips:raw.groups.HIPS.bilateral_valid,knees:raw.groups.KNEES.bilateral_valid,ankles:raw.groups.ANKLES.bilateral_valid},cropped_edges:raw.cropped_edges,candidate_mode:this.candidate,candidate_since_ms:this.candidateSince,stable_mode_since_ms:this.stableModeSince,body_mode_transition_count:this.transitions,body_mode_flicker_count:this.flickers};
    const output:FramingMeasurement={timestamp_ms:timestampMs,state_version:stateVersion,body_mode:this.committed,body_mode_confidence:visibility.confidence,body_visibility:visibility,groups:raw.groups,anchor_x:anchor,anchor_x_source:raw.anchor_x_source,scale,scale_metric_type:scaleRaw?.metric_type??null,scale_components:scaleRaw?.component_values??{},confidence:Math.min(visibility.confidence,1-Math.min(ux,us)),uncertainty_x:ux,uncertainty_scale:us,uncertainty_scale_components:Object.freeze(scaleComponents),scale_validity_reason:scaleValidityReason,torso_orientation:raw.torso_orientation,distance_proxy:distanceProxy,cropped_edges:raw.cropped_edges,measurement_age_ms:0,valid_for_precision_x:compatibleMode&&anchor!==null&&ux<=.10,valid_for_precision_scale:validScale,velocity_x:vx,velocity_scale:vs,stable,filter_type:'ONE_EURO',display_box:raw.display_box,raw_pose_box:raw.raw_pose_box};this.last=output;return output;
  }
  private updateMode(next:BodyMode,now:number):void {
    if(next!==this.candidate){if(this.candidate!==this.committed&&now-this.candidateSince<this.persistenceMs)this.flickers+=1;this.candidate=next;this.candidateSince=now;}
    if(next!==this.committed&&now-this.candidateSince>=this.persistenceMs){this.committed=next;this.stableModeSince=now;this.transitions+=1;}
    if(next===this.committed&&this.stableModeSince===0)this.stableModeSince=now;
  }
}
