import '../src/style.css';
import { CameraRuntime } from '../camera/camera-runtime.js';
import { DeviceOrientationProvider } from '../motion/device-orientation-provider.js';
import type { FrameMetrics, SweepMode } from '../sweep/types.js';
import { metricsFromImageData } from '../sweep/quality-gate.js';
import { SceneSweepRuntime } from '../sweep/sweep-runtime.js';
import { canonicalManifestJson } from '../spatial/scene-sweep-manifest.js';
import { SweepTelemetry } from '../telemetry/telemetry.js';

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const video = $<HTMLVideoElement>('preview'), camera = new CameraRuntime(video), orientation = new DeviceOrientationProvider(), telemetry = new SweepTelemetry();
const canvas = document.createElement('canvas'), ctx = canvas.getContext('2d', { willReadFrequently: true })!; let runtime: SceneSweepRuntime | null = null, latestYaw = 0, candidateTimer = 0, fixtureTimer = 0;
const modeTarget = () => ({ QUICK_SWEEP: 110, WIDE_SWEEP: 180, FULL_SWEEP: 360 }[$<HTMLSelectElement>('mode').value as SweepMode]);
const setText = (id: string, text: string) => { $(id).textContent = text; };
const render = () => { if (!runtime) return; const coverage = runtime.coverage.snapshot().span_deg, totalRejected = Object.values(runtime.sampler.rejections).reduce((a,b)=>a+b,0), snapshot = camera.snapshot(), t = telemetry.snapshot(performance.now(), snapshot.fps, [snapshot.width,snapshot.height], 0); setText('status',runtime.session.status);setText('yaw',`${latestYaw.toFixed(1)}°`);setText('coverage',`${coverage.toFixed(1)}° / ${modeTarget()}°`);setText('keyframes',String(runtime.sampler.keyframes.length));setText('rejections',String(totalRejected));setText('fps',t.preview_fps.toFixed(1));setText('hz',t.orientation_hz.toFixed(1));setText('quality',t.quality_eval_ms_p50===null?'—':`${t.quality_eval_ms_p50.toFixed(1)} / ${t.quality_eval_ms_p95?.toFixed(1)}`);$('arc-fill').style.width=`${Math.min(100,coverage/modeTarget()*100)}%`;setText('hero',runtime.session.status==='COMPLETE'?'看完了':'慢慢转动手机');if(runtime.session.status==='COMPLETE') stopAcquisition(); };
const sampleFrame = () => { if (!runtime || runtime.session.status !== 'SWEEPING' || !video.videoWidth) return; const started=performance.now();canvas.width=160;canvas.height=Math.max(1,Math.round(160*video.videoHeight/video.videoWidth));ctx.drawImage(video,0,0,canvas.width,canvas.height);const selected=runtime.observeFrame(metricsFromImageData(ctx.getImageData(0,0,canvas.width,canvas.height),performance.now(),latestYaw));telemetry.candidate(performance.now()-started,selected);render(); };
const stopAcquisition = () => { clearInterval(candidateTimer); clearInterval(fixtureTimer); orientation.stop(); $('finish').toggleAttribute('disabled',runtime?.session.status==='COMPLETE'); $('download').toggleAttribute('disabled',runtime?.session.status!=='COMPLETE'); };

$('start').addEventListener('click', async () => { const mode=$<HTMLSelectElement>('mode').value as SweepMode; runtime=new SceneSweepRuntime(mode,`sweep-${Date.now()}`,Date.now());telemetry.start(performance.now());orientation.resetBaseline();setText('message','正在请求相机与方向权限…');const [cameraState,orientationState]=await Promise.all([camera.start(),orientation.requestPermission()]);if(cameraState.state!=='ACTIVE'){setText('message',cameraState.message??'相机不可用');return;}$('empty').style.display='none';$('finish').toggleAttribute('disabled',false);$('cancel').toggleAttribute('disabled',false);orientation.start((sample)=>{latestYaw=sample.relative_yaw_deg;telemetry.orientation();runtime?.observeOrientation(sample);render();});candidateTimer=window.setInterval(sampleFrame,125);setText('message',orientationState==='ACTIVE'?'方向传感器已启用；图像仅本机处理。':'相机可用，但方向传感器不可用。');render(); });
$('fixture').addEventListener('click',()=>{clearInterval(fixtureTimer);const mode=$<HTMLSelectElement>('mode').value as SweepMode,target=modeTarget();runtime=new SceneSweepRuntime(mode,`fixture-${mode.toLowerCase()}`,0);telemetry.start(performance.now());$('empty').style.display='none';$('finish').toggleAttribute('disabled',false);$('cancel').toggleAttribute('disabled',false);setText('message','确定性 Fixture：无相机、无网络、无 Provider。');let yaw=0;const tick=()=>{if(!runtime||runtime.session.status==='COMPLETE'){stopAcquisition();return;}latestYaw=yaw;telemetry.orientation();runtime.observeOrientation({timestamp_ms:yaw*10,relative_yaw_deg:yaw,raw_heading_deg:yaw,confidence:'HIGH',status:'ACTIVE',screen_orientation:'PORTRAIT_PRIMARY',source:'CONTROLLED_FIXTURE'});const f:FrameMetrics={timestamp_ms:yaw*10,yaw_deg:yaw,width:640,height:480,blur_score:30,exposure_mean:128,highlight_clipping_ratio:0,shadow_clipping_ratio:0,fingerprint:[(yaw%24)/24,1-(yaw%24)/24]};const started=performance.now(),selected=runtime.observeFrame(f);telemetry.candidate(performance.now()-started,selected);yaw+=6;render();if(yaw>target+12)stopAcquisition();};tick();fixtureTimer=window.setInterval(tick,35);});
$('finish').addEventListener('click',()=>{runtime?.finish(Date.now());stopAcquisition();render();});$('cancel').addEventListener('click',()=>{runtime?.cancel(Date.now());stopAcquisition();camera.stop();render();setText('hero','已取消');});$('download').addEventListener('click',()=>{if(!runtime)return;const blob=new Blob([canonicalManifestJson(runtime.manifest())],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${runtime.session.sweep_id}.json`;link.click();setText('message',`Manifest 已导出：${link.download}`);setTimeout(()=>URL.revokeObjectURL(link.href),0);});window.addEventListener('pagehide',()=>{orientation.stop();camera.stop();});
