import {Button,Image,Text,View} from '@tarojs/components'
import Taro,{useLoad,useUnload} from '@tarojs/taro'
import {useEffect,useRef,useState} from 'react'
import {api,RuntimeReadiness,Session,SessionSummary,UploadedAsset} from '../../api/client'
import {H5StillCamera,LocalCaptureCandidate,platformRegistry} from '../../platform/runtime'
import {confirmationKey,publicRuntimeMayStart} from '../../product/capturePolicy'
import {advanceConfirmedCaptureToFinal,advanceNewSessionToShoot,fallbackVisible,userVisibleStage} from '../../product/simplifiedFlow'
import {DEFAULT_USER_PREFERENCES,effectivePreferences,loadPreferences,PreferenceStorage,resetSessionOverride,savePreferences,SessionUIOverride,UserPreferences} from '../../product/userPreferences'
import {sessionStorage} from '../../platform/sessionStorage'
import {FineTuneEditor} from '../../fineTune/FineTuneEditor'
import './index.css'
import './quick-settings.css'

type Surface='HOME'|'FLOW'|'WORKS'|'SETTINGS'
const PREFERENCES_KEY='xfx-user-preferences-v1'
const preferenceStorage:PreferenceStorage={read:()=>Taro.getStorage({key:PREFERENCES_KEY}).then(value=>value.data).catch(()=>undefined),write:value=>Taro.setStorage({key:PREFERENCES_KEY,data:value}).then(()=>undefined)}
const visibleStages=['START','SHOOT','REVIEW','FINAL'] as const
const stageMeta={
 SHOOT:{eyebrow:'SHOOT · 拍摄',title:'跟随镜头，拍下真实照片',copy:'内部准备会自动完成；相机权限只会在你点击“打开相机”后请求。'},
 REVIEW:{eyebrow:'REVIEW · 确认',title:'确认照片，再自动完成处理',copy:'照片确认前只在本机；“使用这张”是唯一保留的上传确认。'},
 FINAL:{eyebrow:'FINAL · 成片',title:'照片已经准备好',copy:'保存、分享、查看作品，或开始下一次拍摄。'}
}

const friendlyError=(error:unknown)=>{const raw=error instanceof Error?error.message:String(error);if(raw.includes('PERMISSION_DENIED'))return '未获得相机权限。你仍可以从设备选择照片。';if(raw.includes('NETWORK_UNAVAILABLE'))return '当前网络不可用。照片仍保留在本机，请联网后重试。';if(raw.includes('INVALID_ASSET'))return '这张图片无法使用，请选择 JPG、PNG 或 WebP 图片。';if(raw.includes('USER_CANCELLED'))return '已取消选择，尚未上传任何照片。';if(raw.includes('PLATFORM_UNSUPPORTED')||raw.includes('CAMERA_FAILURE'))return '当前设备无法打开相机，可改用照片导入。';if(raw.includes('STORAGE_FAILURE'))return '照片暂时无法保存，请稍后重试。';return '暂时无法完成操作，当前进度已保留，请重试。'}

export default function Index(){
 const [surface,setSurface]=useState<Surface>('HOME');const [session,setSession]=useState<Session|null>(null);const [active,setActive]=useState<SessionSummary[]>([]);const [completed,setCompleted]=useState<SessionSummary[]>([]);const [readiness,setReadiness]=useState<RuntimeReadiness|null>(null)
 const [preferences,setPreferences]=useState<UserPreferences>(DEFAULT_USER_PREFERENCES);const [draftPreferences,setDraftPreferences]=useState<UserPreferences>(DEFAULT_USER_PREFERENCES);const [sessionOverride,setSessionOverride]=useState<SessionUIOverride>({})
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [candidate,setCandidate]=useState<LocalCaptureCandidate|null>(null);const [uploaded,setUploaded]=useState<UploadedAsset|null>(null);const [cameraOpen,setCameraOpen]=useState(false);const [cameraSwitching,setCameraSwitching]=useState(false);const [fallbackRequested,setFallbackRequested]=useState(false);const [cameraFailed,setCameraFailed]=useState(false)
 const camera=useRef(new H5StillCamera())
 const refreshHome=async()=>{const [runtime,sessions]=await Promise.all([api.readiness(__XFX_PRODUCT_MODE__),api.list()]);setReadiness(runtime);setActive(sessions.filter(item=>item.status==='ACTIVE'));setCompleted(sessions.filter(item=>item.status==='COMPLETED'))}
 useLoad(()=>{Promise.all([refreshHome(),loadPreferences(preferenceStorage).then(value=>{setPreferences(value);setDraftPreferences(value)})]).catch(e=>setError(friendlyError(e)))})
 useUnload(()=>camera.current.close());useEffect(()=>()=>camera.current.close(),[])
 const disposeCandidate=()=>{if(candidate?.previewUrl.startsWith('blob:'))URL.revokeObjectURL(candidate.previewUrl);setCandidate(null);setUploaded(null)}
 const effective=effectivePreferences(preferences,sessionOverride)
 const actionFor=(sessionId:string)=>(action:string,payload:Record<string,any>={})=>api.action(sessionId,action,payload)
 const prepareToShoot=async(value:Session)=>{setSessionOverride(resetSessionOverride());setFallbackRequested(false);setCameraFailed(false);setSession(value);setSurface('FLOW');const result=await advanceNewSessionToShoot(value,preferences,actionFor(value.session_id));setSession(result.session as Session);if(result.status==='STOPPED')setError(`拍摄准备暂停在 ${result.session.workflow_stage}，可以安全重试。`)}
 const openSession=async(item:SessionSummary)=>{setBusy(true);setError('');try{const value=await api.get(item.session_id);await sessionStorage.write(value.session_id);if(value.workflow_stage==='FINAL'){setSession(value);setSurface('FLOW')}else await prepareToShoot(value)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 const start=async()=>{if(!publicRuntimeMayStart(__XFX_PRODUCT_MODE__,Boolean(readiness?.ready))){setError('当前版本尚未达到公开生产就绪标准，已停止创建拍摄会话。');return}setBusy(true);setError('');setNotice('正在准备拍摄…');try{const value=await api.create();await sessionStorage.write(value.session_id);await prepareToShoot(value);setNotice('拍摄已准备好。')}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 const run=async(action:string,payload:Record<string,any>={})=>{if(!session)return null;setBusy(true);setError('');try{const value=await api.action(session.session_id,action,payload);setSession(value);return value}catch(e){setError(friendlyError(e));return null}finally{setBusy(false)}}
 const retryPreparation=async()=>{if(!session)return;setBusy(true);setError('');try{await prepareToShoot(await api.get(session.session_id))}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 const openCamera=async()=>{setError('');setNotice('');setCameraFailed(false);camera.current.setFacingMode(effective.camera_facing_default);if(platformRegistry.platform==='WECHAT'){const result=await platformRegistry.chooseCandidate('camera');if(result.ok&&result.value)setCandidate(result.value);else{setCameraFailed(true);setError(friendlyError(new Error(result.code)))}return}setCameraOpen(true);await new Promise(resolve=>setTimeout(resolve,0));const result=await camera.current.open('camera-preview');if(!result.ok){setCameraOpen(false);setCameraFailed(true);setError(friendlyError(new Error(result.code)));return}setNotice(`已打开${effective.camera_facing_default==='environment'?'后置':'前置'}镜头。`);if(effective.voice_guidance_enabled)await platformRegistry.voice('保持画面稳定，准备好就按下快门')}
 const switchCamera=async()=>{if(cameraSwitching)return false;setCameraSwitching(true);setError('');setNotice('正在切换镜头…');try{const result=await camera.current.switch('camera-preview');if(result.ok&&result.value){const actual=result.value.facingMode==='user'?'user':'environment';setSessionOverride(current=>({...current,camera_facing_default:actual}));setNotice(`已切换到${actual==='environment'?'后置':'前置'}镜头。`);return true}if(result.message==='CAMERA_SWITCH_FAILED_RESTORED'){setNotice('镜头切换失败，已恢复原镜头；可以重试或继续拍摄。');return false}setCameraOpen(false);setCameraFailed(true);setError('镜头切换失败，且原镜头未能恢复。可重试打开相机或改用照片导入。');return false}finally{setCameraSwitching(false)}}
 const toggleQuickCamera=async()=>{if(cameraSwitching)return;if(cameraOpen){await switchCamera();return}const next=effective.camera_facing_default==='environment'?'user':'environment';camera.current.setFacingMode(next);setSessionOverride(current=>({...current,camera_facing_default:next}));setNotice(`下次打开相机将使用${next==='environment'?'后置':'前置'}镜头。`)}
 const toggleQuickGrid=()=>{const next=!effective.composition_grid_enabled;setSessionOverride(current=>({...current,composition_grid_enabled:next}));setNotice(`构图网格已${next?'开启':'关闭'}。`)}
 const toggleQuickVoice=async()=>{const next=!effective.voice_guidance_enabled;if(next){const result=await platformRegistry.voice('语音提示已开启');if(!result.ok){setNotice('当前浏览器不支持语音提示。');return}}else if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();setSessionOverride(current=>({...current,voice_guidance_enabled:next}));setNotice(`语音提示已${next?'开启':'关闭'}。`)}
 const toggleQuickHaptic=async()=>{const next=!effective.haptic_enabled;if(next){const result=await platformRegistry.haptic('READY');if(!result.ok){setNotice('当前设备不支持触感反馈。');return}}setSessionOverride(current=>({...current,haptic_enabled:next}));setNotice(`触感反馈已${next?'开启':'关闭'}。`)}
 const takeStill=async()=>{const result=await camera.current.capture();if(result.ok&&result.value){camera.current.close();setCameraOpen(false);setCandidate(result.value);if(effective.haptic_enabled)await platformRegistry.haptic('CAPTURE')}else{camera.current.close();setCameraOpen(false);setCameraFailed(true);setError(friendlyError(new Error(result.code)))}}
 const closeCamera=()=>{camera.current.close();setCameraOpen(false);setNotice('相机已关闭，未上传照片。')}
 const importPhoto=async()=>{setError('');const result=await platformRegistry.chooseCandidate('album');if(result.ok&&result.value){disposeCandidate();setCandidate(result.value);setNotice('照片仅在本机等待确认。')}else if(result.code!=='USER_CANCELLED')setError(friendlyError(new Error(result.code)))}
 const retake=()=>{disposeCandidate();setNotice('已丢弃本机预览，服务器上传数和工作流均未改变。')}
 const confirmCapture=async()=>{if(!session||!candidate)return;setBusy(true);setError('');setNotice('正在保存你确认的照片…');try{const network=await platformRegistry.networkStatus();if(!network.ok)throw new Error(network.code);let accepted=uploaded;if(!accepted){const result=await platformRegistry.uploadCandidate(candidate);if(!result.ok||!result.value)throw new Error(result.code);accepted=result.value;setUploaded(accepted)}const value=await api.action(session.session_id,'CREATE_CAPTURE',{uploaded_asset_id:accepted.asset_id},confirmationKey(candidate.id));disposeCandidate();const advanced=await advanceConfirmedCaptureToFinal(value,preferences,actionFor(session.session_id));setSession(advanced.session as Session);if(advanced.status==='STOPPED'){setNotice('照片已确认，自动处理暂停；当前状态已保留。');setError('自动处理未完成，请安全重试。')}else setNotice(preferences.open_fine_tune_after_processing?'照片已完成；微调入口将在成片页显示。':'照片已确认并完成处理。')}catch(e){setError(friendlyError(e));setNotice('照片仍保留在本机，可直接重试。')}finally{setBusy(false)}}
 const finishReview=async()=>{if(!session)return;setBusy(true);setError('');try{let value=session;if(value.workflow_stage==='QA')value=await api.action(value.session_id,'ACCEPT');const result=await advanceConfirmedCaptureToFinal(value,{...preferences,auto_processing_enabled:true},actionFor(value.session_id));setSession(result.session as Session);if(result.status==='STOPPED')setError('处理暂停，当前状态已保留。')}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 const openFineTune=async()=>{if(!session)return;const value=await run('ACCEPT_REALITY_PLUS');if(value)setNotice('微调只在本机计算；拖动滑杆不会发起网络请求。')}
 const skipFineTune=async()=>{if(!session)return;const value=await run('SKIP_FINE_TUNE');if(value)setNotice('成片已保存。')}
 const retakeFromReview=async()=>{const value=await run('RETAKE_MICRO');if(value){setBusy(true);try{await prepareToShoot(value)}finally{setBusy(false)}}}
 const finalDownload=async()=>{if(!session)return;const result=await platformRegistry.download(api.finalDownloadUrl(session.session_id));setNotice(result.ok?'下载已开始。':'当前无法下载，请稍后重试。')}
 const finalShare=async()=>{if(!session)return;const result=await platformRegistry.share(api.finalDownloadUrl(session.session_id));setNotice(result.ok?'已打开系统分享。':'当前环境不支持直接分享，你仍可以先下载照片。')}
 const backHome=async()=>{camera.current.close();setCameraOpen(false);disposeCandidate();setSessionOverride(resetSessionOverride());setSession(null);setSurface('HOME');await refreshHome().catch(e=>setError(friendlyError(e)))}
 const goWorks=async()=>{camera.current.close();setCameraOpen(false);disposeCandidate();setSessionOverride(resetSessionOverride());setSession(null);await refreshHome().catch(e=>setError(friendlyError(e)));setSurface('WORKS')}
 const openSettings=()=>{setDraftPreferences(preferences);setSurface('SETTINGS')}
 const saveSettings=async()=>{setBusy(true);try{const saved=await savePreferences(preferenceStorage,draftPreferences);setPreferences(saved);setNotice('设置已保存，将应用于新的拍摄。');setSurface('HOME')}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}

 if(surface==='HOME')return <View className='shell home'><View className='top'><Text className='brand'>向风行</Text>{__XFX_PRODUCT_MODE__==='INTERNAL_DEMO'&&<Text className='demoBadge'>内部演示</Text>}</View><View className='visual'><Text className='marker'>START · 开始</Text><Text className='hero'>把眼前真实，拍成你的照片</Text><Text className='copy'>从开始到相机只保留必要选择；未完成的拍摄由你明确决定是否继续。</Text></View>{__XFX_PRODUCT_MODE__==='PRODUCTION'&&!readiness?.ready&&<View className='error'>当前版本尚未达到公开生产就绪标准，虚拟 AI 能力不会以真实能力对外提供。</View>}{active.length>0&&<View className='section'><Text className='sectionTitle'>继续上次拍摄</Text>{active.map(item=><Button className='sessionCard' key={item.session_id} disabled={busy} onClick={()=>openSession(item)}>继续 · {userVisibleStage(item.workflow_stage)}</Button>)}</View>}<Button className='primary' disabled={busy} onClick={start}>{busy?'正在准备…':'开始拍摄'}</Button><Button className='secondary' onClick={()=>setSurface('WORKS')}>我的作品（{completed.length}）</Button><Button className='secondary' onClick={openSettings}>设置</Button>{notice&&<View className='notice'>{notice}</View>}{error&&<View className='error'>{error}</View>}</View>
 if(surface==='SETTINGS')return <View className='shell'><View className='top'><Text className='brand'>设置</Text><Text className='link' onClick={()=>setSurface('HOME')}>取消</Text></View><Text className='copy'>设置只影响前端体验，不修改 Workflow 或 Session Authority。</Text><View className='settingsList'><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,shooting_relation_default:value.shooting_relation_default==='FRIEND'?'SOLO':'FRIEND'}))}>默认拍摄关系 · {draftPreferences.shooting_relation_default==='FRIEND'?'朋友帮拍':'自己拍'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,device_mode_default:value.device_mode_default==='SINGLE'?'SOLO_FIXED':'SINGLE'}))}>默认设备 · {draftPreferences.device_mode_default==='SINGLE'?'单设备':'固定机位'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,camera_facing_default:value.camera_facing_default==='environment'?'user':'environment'}))}>默认镜头 · {draftPreferences.camera_facing_default==='environment'?'后置':'前置'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,voice_guidance_enabled:!value.voice_guidance_enabled}))}>语音指导 · {draftPreferences.voice_guidance_enabled?'开':'关'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,haptic_enabled:!value.haptic_enabled}))}>触感反馈 · {draftPreferences.haptic_enabled?'开':'关'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,composition_grid_enabled:!value.composition_grid_enabled}))}>构图网格 · {draftPreferences.composition_grid_enabled?'开':'关'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,auto_processing_enabled:!value.auto_processing_enabled}))}>确认后自动处理 · {draftPreferences.auto_processing_enabled?'开':'关'}</Button><Button className='settingRow' onClick={()=>setDraftPreferences(value=>({...value,open_fine_tune_after_processing:!value.open_fine_tune_after_processing}))}>完成后显示微调 · {draftPreferences.open_fine_tune_after_processing?'开':'关'}</Button></View><Button className='primary' disabled={busy} onClick={saveSettings}>保存设置</Button></View>
 if(surface==='WORKS')return <View className='shell'><View className='top'><Text className='brand'>我的作品</Text><Text className='link' onClick={()=>setSurface('HOME')}>返回</Text></View>{completed.length===0?<Text className='copy'>完成一次拍摄后，作品会出现在这里。</Text>:completed.map(item=><View className='workCard' key={item.session_id}>{item.thumbnail_asset_id&&<Image className='workThumb' mode='aspectFill' src={api.assetContentUrl(item.thumbnail_asset_id)}/>}<Text>完成于 {new Date(item.updated_at).toLocaleString()}</Text><Button className='secondary compact' onClick={()=>openSession(item)}>打开作品</Button></View>)}</View>
 const workflowStage=session?.workflow_stage||'ENTRY';const visibleStage=userVisibleStage(workflowStage);const meta=stageMeta[visibleStage==='START'?'SHOOT':visibleStage];const progress=(visibleStages.indexOf(visibleStage)+1)/visibleStages.length*100
 return <View className='shell'><View className='top'><Text className='brand'>向风行</Text><Text className='link' onClick={backHome}>稍后继续</Text></View>{__XFX_PRODUCT_MODE__==='INTERNAL_DEMO'&&<Text className='demoBadge'>内部演示 · QA 为确定性替身</Text>}<View className='progress'><View className='progressFill' style={{width:`${progress}%`}}/></View><View className='stageDots'>{visibleStages.map(item=><Text key={item} className={item===visibleStage?'stageDot active':'stageDot'}>{item}</Text>)}</View><View className='visual flowVisual'><Text className='marker'>{meta.eyebrow}</Text><Text className='hero'>{meta.title}</Text><Text className='copy'>{meta.copy}</Text></View>{error&&<View className='error'>{error}{!['CAPTURE','QA','REALITY_PLUS','FINE_TUNE','FINAL'].includes(workflowStage)&&<Text className='retry' onClick={retryPreparation}>继续准备</Text>}</View>}{notice&&<View className='notice'>{notice}</View>}
  {workflowStage==='CAPTURE'&&<View className='capturePanel'><View className='quickSettings'><Text className='sectionTitle'>快速设置</Text><View className='quickRow'><Button className='chip' disabled={cameraSwitching} onClick={toggleQuickCamera}>{cameraSwitching?'镜头 · 切换中':'镜头 · '+(effective.camera_facing_default==='environment'?'后置':'前置')}</Button><Button className='chip' onClick={toggleQuickGrid}>网格 · {effective.composition_grid_enabled?'开':'关'}</Button><Button className='chip' onClick={toggleQuickVoice}>语音 · {effective.voice_guidance_enabled?'开':'关'}</Button><Button className='chip' onClick={toggleQuickHaptic}>触感 · {effective.haptic_enabled?'开':'关'}</Button></View></View>{cameraOpen&&<><View id='camera-preview' className={effective.composition_grid_enabled?'cameraPreview grid':'cameraPreview'}/><Text className='guidance'>保持画面稳定，准备好就按下快门</Text><View className='inlineActions'><Button className='secondary compact' disabled={cameraSwitching} onClick={switchCamera}>{cameraSwitching?'切换中…':'切换镜头'}</Button><Button className='secondary compact' disabled={cameraSwitching} onClick={closeCamera}>关闭</Button></View><Button className='shutter' aria-label='按下快门' disabled={cameraSwitching} onClick={takeStill}>●</Button></>}{!cameraOpen&&!candidate&&<><Button className='primary' onClick={openCamera}>打开相机</Button>{!fallbackVisible(cameraFailed,fallbackRequested)&&<Text className='fallbackLink' onClick={()=>setFallbackRequested(true)}>无法使用相机？</Text>}{fallbackVisible(cameraFailed,fallbackRequested)&&<Button className='secondary' onClick={importPhoto}>从设备选择照片</Button>}</>}{candidate&&<><Image className='candidatePreview' mode='aspectFit' src={candidate.previewUrl}/><Text className='privacyNote'>这张照片尚未上传。确认前可安全重拍或返回。</Text><View className='inlineActions'><Button className='secondary compact' disabled={busy} onClick={retake}>重拍</Button><Button className='primary compact' disabled={busy} onClick={confirmCapture}>{busy?'保存中…':'使用这张'}</Button></View></>}</View>}
  {workflowStage==='QA'&&<View className='actions'><Button className='primary' disabled={busy} onClick={finishReview}>{busy?'处理中…':'继续完成'}</Button><Button className='secondary' disabled={busy} onClick={retakeFromReview}>局部重拍</Button></View>}
  {workflowStage==='REALITY_PLUS'&&<View className='actions'><Button className='primary' disabled={busy} onClick={skipFineTune}>保存成片</Button><Button className='secondary' disabled={busy} onClick={openFineTune}>微调</Button></View>}
  {workflowStage==='FINE_TUNE'&&session&&<FineTuneEditor session={session} onComplete={value=>{setSession(value);setNotice('微调成片已写入我的作品。')}} onError={message=>setError(friendlyError(new Error(message)))}/>}
  {workflowStage==='FINAL'&&<View className='final'>{session?.state?.final?.source_upload_asset_id&&<Image className='finalImage' mode='aspectFit' src={api.finalDownloadUrl(session.session_id)}/>}<Button className='primary' onClick={finalDownload}>保存照片</Button><Button className='secondary' onClick={finalShare}>分享照片</Button><Button className='secondary' onClick={goWorks}>我的作品</Button><Button className='secondary' onClick={start}>再拍一张</Button></View>}</View>
}
