import { HumanTargetRelativeServoV04 } from './controller.js';
import { deriveV4Presentation } from './presentation.js';
import { LIVE_TARGET_FIXTURES_V02, V4_FRAMING_TARGET_FIXTURES_V01 } from './targets.js';
import { v4ObservationFixture } from '../fixtures/control-v4/human-observations.js';

export interface CanonicalBrowserCaseV01 {id:string;pass:boolean;detail:string}
export interface CanonicalBrowserMatrixV01 {matrix_version:'CanonicalBrowserMatrixV01';candidate:'CANONICAL_TARGET_06';pass:boolean;cases:readonly Readonly<CanonicalBrowserCaseV01>[];provider_calls:0;luna_calls:0;raw_video_upload:0}
const item=(id:string,pass:boolean,detail:string):Readonly<CanonicalBrowserCaseV01>=>Object.freeze({id,pass,detail});

export function runCanonicalGuidanceBrowserMatrixV01():Readonly<CanonicalBrowserMatrixV01>{
  const cases:CanonicalBrowserCaseV01[]=[];
  const center=LIVE_TARGET_FIXTURES_V02.CENTER_UPPER_BODY;
  const base=(t:number,v:number,overrides:Partial<Parameters<typeof v4ObservationFixture>[0]>={})=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'UPPER_BODY',scale_metric:'HEAD_TO_HIP',...overrides});
  const locked=new HumanTargetRelativeServoV04(center);locked.arm(0);const lockSnapshot=locked.update(base(0,1));cases.push(item('TARGET_LOCKED',lockSnapshot.canonical_guidance.canonical_target.status==='LOCKED'&&lockSnapshot.canonical_guidance.canonical_target.target_id===center.id,'single immutable target identity'));
  const missing=new HumanTargetRelativeServoV04(center);missing.arm(0);const missingSnapshot=missing.update(base(0,1,{present:false}));cases.push(item('MISSING_SUBJECT',missingSnapshot.stage==='ACQUIRE_SUBJECT'&&!missingSnapshot.canonical_guidance.error_vector.all_hard_constraints_pass,'observation blocks command'));
  const wrongExtent=new HumanTargetRelativeServoV04(center);wrongExtent.arm(0);const extentSnapshot=wrongExtent.update(v4ObservationFixture({timestamp_ms:0,state_version:1,coverage:'HEAD_SHOULDERS'}));cases.push(item('WRONG_EXTENT',extentSnapshot.stage==='ACQUIRE_REQUIRED_BODY','extent remains distinct from scale'));
  for(const [id,scale,expected] of [['SCALE_TOO_SMALL',.2,'MOVE_CLOSER_SMALL'],['SCALE_TOO_LARGE',.65,'MOVE_FARTHER_SMALL']] as const){const c=new HumanTargetRelativeServoV04(center);c.arm(0);c.update(base(0,1,{scale}));const snapshot=c.update(base(300,2,{scale}));cases.push(item(id,snapshot.action===expected,`${snapshot.action}`));}
  for(const [id,x,expected] of [['X_LEFT',.25,'MOVE_LEFT_SMALL'],['X_RIGHT',.75,'MOVE_RIGHT_SMALL']] as const){const c=new HumanTargetRelativeServoV04(center);c.arm(0);c.update(base(0,1,{x}));const snapshot=c.update(base(300,2,{x}));cases.push(item(id,snapshot.action===expected,`${snapshot.action}`));}
  const yTarget=V4_FRAMING_TARGET_FIXTURES_V01.HEAD_SHOULDERS_LEFT_TOP,y=new HumanTargetRelativeServoV04(yTarget),yInput=(t:number,v:number)=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'HEAD_SHOULDERS',scale_metric:'HEAD_SHOULDER_SCALE',scale:yTarget.target_scale,x:yTarget.target_anchor_x,head_y:.5});y.arm(0);y.update(yInput(0,1));const ySnapshot=y.update(yInput(300,2));cases.push(item('Y_CAMERA_OWNER',ySnapshot.canonical_guidance.command?.owner==='CAMERA_OPERATOR'&&ySnapshot.canonical_guidance.command.dimension==='Y',`${ySnapshot.action}`));
  const moving=new HumanTargetRelativeServoV04(center);moving.arm(0);moving.update(base(0,1,{x:.75}));moving.update(base(300,2,{x:.75}));const movingSnapshot=moving.update(base(450,3,{x:.68,x_motion:'NEGATIVE',stable:false})),movingPresentation=deriveV4Presentation(movingSnapshot);cases.push(item('MOVEMENT_NOT_TARGET_REACHED',movingSnapshot.canonical_guidance.command?.lifecycle==='MOVING_TOWARD_TARGET'&&!movingSnapshot.canonical_guidance.verification.target_reached&&!/好，站定/.test(JSON.stringify(movingPresentation)),'movement only advances command progress'));
  const reverse=new HumanTargetRelativeServoV04(center);reverse.arm(0);reverse.update(base(0,1,{x:.75}));reverse.update(base(300,2,{x:.75}));reverse.update(base(450,3,{x:.58,x_motion:'NEGATIVE',stable:false}));reverse.update(base(600,4,{x:.35,x_motion:'NEGATIVE',stable:false}));const invalidated=reverse.update(base(1150,5,{x:.35,x_motion:'STILL',stable:true})),opposite=reverse.update(base(1200,6,{x:.35,x_motion:'STILL',stable:true}));cases.push(item('DIRECTION_REVERSAL',invalidated.canonical_guidance.voice_event==='DIRECTION_REVERSED'&&invalidated.canonical_guidance.command?.lifecycle==='INVALIDATED'&&opposite.action==='MOVE_LEFT_SMALL'&&opposite.canonical_guidance.command?.replaces_command_id===invalidated.canonical_guidance.command?.command_id,'persistent opposite error replaces stale command'));
  const noResponse=new HumanTargetRelativeServoV04(center);noResponse.arm(0);noResponse.update(base(0,1,{x:.75}));noResponse.update(base(300,2,{x:.75}));const noResponseSnapshot=noResponse.update(base(5000,3,{x:.75}));cases.push(item('LONG_NO_RESPONSE',noResponseSnapshot.canonical_guidance.voice_event==='LONG_NO_RESPONSE_REPROMPT'&&noResponseSnapshot.canonical_guidance.command?.lifecycle==='ACTIVE','same command conservative reprompt'));
  const readyTarget=V4_FRAMING_TARGET_FIXTURES_V01.HEAD_SHOULDERS_CENTER,ready=new HumanTargetRelativeServoV04(readyTarget),readyInput=(t:number,v:number,x=readyTarget.target_anchor_x)=>v4ObservationFixture({timestamp_ms:t,state_version:v,coverage:'HEAD_SHOULDERS',scale_metric:'HEAD_SHOULDER_SCALE',scale:readyTarget.target_scale,x,head_y:(readyTarget.target_anchor_y??.5)-.12});ready.arm(0);const reached=ready.update(readyInput(0,1));ready.update(readyInput(300,2));const readySnapshot=ready.update(readyInput(600,3));cases.push(item('TARGET_REACHED_THEN_READY',reached.canonical_guidance.voice_event==='TARGET_REACHED'&&readySnapshot.ready&&readySnapshot.canonical_guidance.verification.verified,'rolling verification after target reached'));
  ready.update(readyInput(800,4,.85));const revoked=ready.update(readyInput(1400,5,.85));cases.push(item('READY_REVOKE',!revoked.ready&&revoked.trial_success_latched&&revoked.ready_exit_reason==='X_EXITED','current READY separate from trial success'));
  const oldRevision=readySnapshot.canonical_guidance.canonical_target.target_revision;ready.setTarget(V4_FRAMING_TARGET_FIXTURES_V01.HEAD_SHOULDERS_LEFT_TOP);const switched=ready.update(readyInput(1500,6));cases.push(item('TARGET_SWITCH_INVALIDATES',!switched.armed&&switched.canonical_guidance.command===null&&switched.canonical_guidance.canonical_target.target_revision>oldRevision,'old target command removed'));
  const pass=cases.every(entry=>entry.pass);return Object.freeze({matrix_version:'CanonicalBrowserMatrixV01',candidate:'CANONICAL_TARGET_06',pass,cases:Object.freeze(cases),provider_calls:0,luna_calls:0,raw_video_upload:0});
}
