import type { ConstraintRelationV01, HumanObservationV02, LiveConstraintStateV01, LiveTargetV02, V4Stage } from './types.js';

const relation=(current:number|null,target:number,tolerance:number):ConstraintRelationV01=>current===null||!Number.isFinite(current)?'UNKNOWN':current<target-tolerance?'TOO_LOW':current>target+tolerance?'TOO_HIGH':'IN_RANGE';
const error=(current:number|null,target:number,tolerance:number):number|null=>current===null||!Number.isFinite(current)?null:Math.abs(current-target)/tolerance;
export function resolveLiveConstraintsV01(observation:HumanObservationV02,target:LiveTargetV02):Readonly<LiveConstraintStateV01>{
  const subject=observation.subject_lock.state==='LOCKED'||observation.subject_lock.state==='REACQUIRING';const missing=target.required_body_parts.filter(part=>!observation.body_visibility.regions[part].visible);const coverage=missing.length===0;const anchor=observation.semantic_anchors.anchors[target.primary_anchor]??null;const scale=observation.scale_evidence[target.scale_metric];const scaleCapability=observation.measurement_capability[target.scale_metric];const anchorCapability=observation.measurement_capability.TORSO_CENTER;const blocking:string[]=[];if(scaleCapability!=='GOOD')blocking.push(`${target.scale_metric}_${scaleCapability}`);if(anchorCapability!=='GOOD')blocking.push(`TORSO_CENTER_${anchorCapability}`);const measurementReady=blocking.length===0;const sr=relation(measurementReady&&scale.valid?scale.value:null,target.target_scale,target.tolerance_scale);const xr=relation(measurementReady?anchor?.x??null:null,target.target_anchor_x,target.tolerance_x);const yr=target.target_anchor_y===null?'IN_RANGE':relation(measurementReady?anchor?.y??null:null,target.target_anchor_y,target.tolerance_y??.05);
  let stage:V4Stage=!subject?'ACQUIRE_SUBJECT':!measurementReady?'ACQUIRE_REQUIRED_BODY':sr!=='IN_RANGE'?'ADJUST_SCALE':xr!=='IN_RANGE'?'ALIGN_PRIMARY_ANCHOR':yr!=='IN_RANGE'?'ALIGN_SECONDARY_CONSTRAINT':'VERIFY';
  return Object.freeze({constraint_version:'LiveConstraintStateV01',stage,subject_satisfied:subject,coverage_satisfied:coverage,measurement_ready:measurementReady,required_body_satisfied:measurementReady,missing_body_parts:Object.freeze(missing),blocking_measurements:Object.freeze(blocking),scale_relation:sr,scale_error_normalized:error(measurementReady&&scale.valid?scale.value:null,target.target_scale,target.tolerance_scale),x_relation:xr,x_error_normalized:error(measurementReady?anchor?.x??null:null,target.target_anchor_x,target.tolerance_x),y_relation:yr,y_error_normalized:target.target_anchor_y===null?0:error(measurementReady?anchor?.y??null:null,target.target_anchor_y,target.tolerance_y??.05),all_satisfied:subject&&measurementReady&&sr==='IN_RANGE'&&xr==='IN_RANGE'&&yr==='IN_RANGE',control_actor:target.control_actor,target_id:target.id,observation_state_version:observation.state_version});
}
