export type SubjectLockStateV01='UNKNOWN'|'ACQUIRING'|'LOCKED'|'HELD'|'REACQUIRING'|'LOST';
export type BodyRegionV01='HEAD'|'SHOULDERS'|'UPPER_TORSO'|'HIPS'|'KNEES'|'ANKLES'|'FEET';
export type SemanticAnchorNameV01='HEAD_CENTER'|'SHOULDER_CENTER'|'TORSO_CENTER'|'HIP_CENTER'|'KNEE_CENTER'|'ANKLE_CENTER'|'BODY_CENTER';
export type ObservationQualityV02='GOOD'|'MARGINAL'|'INVALID';
export type AxisMotionV01='NEGATIVE'|'POSITIVE'|'STILL'|'UNKNOWN';
export type MeasurementReadinessV01='GOOD'|'MARGINAL'|'INVALID';
export type MeasurementTypeV01='HEAD_TO_HIP'|'TORSO_CENTER'|'HEAD_TO_KNEE'|'HEAD_TO_ANKLE';
export type LandmarkEvidenceStatusV01='BILATERAL_VALID'|'UNILATERAL_PARTIAL'|'LOW_CONFIDENCE'|'VALID'|'EDGE_CROPPED'|'UNKNOWN';
export type SemanticGroupTypeV01='MULTI_POINT'|'BILATERAL_PAIR'|'SINGLE_POINT';
export type ObservedBodyCoverageV01='HEAD_ONLY'|'HEAD_SHOULDERS'|'UPPER_BODY'|'THREE_QUARTER'|'FULL_BODY'|'PARTIAL_OR_AMBIGUOUS'|'UNKNOWN';
export type ObservedRegionStateV01='VALID'|'PARTIAL'|'LOW_CONFIDENCE'|'EDGE_CROPPED'|'NOT_OBSERVED'|'UNKNOWN';

export interface SubjectLockObservationV01 {state:SubjectLockStateV01;confidence:number;tracked_subject_count:0|1;lock_age_ms:number;identity_claim:false;multi_person_supported:false}
export interface SubjectRecognitionStateV01 {recognition_version:'SubjectRecognitionStateV01';detected:boolean;lock_state:SubjectLockStateV01;confidence:number;subject_region:Readonly<{center_x:number;center_y:number;width:number;height:number}>|null;fresh:boolean;continuity_ms:number}
export interface BodyRegionEvidenceV01 {state:ObservedRegionStateV01;visible:boolean;bilateral:boolean;confidence:number;crop_risk:'NONE'|'TOP'|'BOTTOM'|'SIDE'|'UNKNOWN'}
export interface BodyVisibilityGraphV01 {regions:Readonly<Record<BodyRegionV01,Readonly<BodyRegionEvidenceV01>>>;summary_mode:ObservedBodyCoverageV01;summary_only:true;global_bottom_cropped:boolean;upper_torso_basis:'DERIVED'|'INVALID';hips_evidence_status:LandmarkEvidenceStatusV01;feet_visible:boolean;feet_bottom_cropped:boolean;partial_landmarks:boolean}
export interface LandmarkBasisScalarV01 {status:LandmarkEvidenceStatusV01;confidence:number;visible_count:number;center_x:number|null;center_y:number|null;left:Readonly<{visible:boolean;confidence:number;x:number|null;y:number|null}>|null;right:Readonly<{visible:boolean;confidence:number;x:number|null;y:number|null}>|null;edge_proximity:'NONE'|'TOP'|'BOTTOM'|'SIDE'|'UNKNOWN';fresh:boolean;stable:boolean}
export interface MeasurementCapabilityV01 {capability_version:'MeasurementCapabilityV01';HEAD_TO_HIP:MeasurementReadinessV01;TORSO_CENTER:MeasurementReadinessV01;HEAD_TO_KNEE:MeasurementReadinessV01;HEAD_TO_ANKLE:MeasurementReadinessV01}
export interface MeasurementDefinitionV01 {measurement_type:MeasurementTypeV01;required_anchors:readonly SemanticAnchorNameV01[];required_regions:readonly BodyRegionV01[];crop_dependencies:readonly ('HEAD'|'SHOULDERS'|'HIPS'|'KNEES'|'ANKLES')[]}
export interface SemanticAnchorV01 {name:SemanticAnchorNameV01;x:number;y:number;confidence:number;source:string}
export interface SemanticAnchorSetV01 {anchors:Readonly<Partial<Record<SemanticAnchorNameV01,Readonly<SemanticAnchorV01>>>>;coordinate_basis:'SENSOR_NORMALIZED_NON_MIRRORED';mirror_applied_to_control:false}
export type ScaleMetricV02='HEAD_TO_HIP'|'HEAD_TO_KNEE'|'HEAD_TO_ANKLE';
export interface ScaleEvidenceV02 {metric:ScaleMetricV02;value:number|null;valid:boolean;confidence:number}
export interface HumanMotionEvidenceV02 {x_motion:AxisMotionV01;scale_motion:AxisMotionV01;velocity_x:number|null;velocity_scale:number|null;distance_proxy:number|null;distance_proxy_role:'RESPONSE_EVIDENCE_ONLY'}
export interface ObservedBodyStateV01 {observed_body_version:'ObservedBodyStateV01';state_version:number;coverage:ObservedBodyCoverageV01;regions:Readonly<Record<BodyRegionV01,Readonly<BodyRegionEvidenceV01>>>;landmark_group_types:Readonly<Record<'HEAD_CORE'|'SHOULDERS'|'HIPS'|'KNEES'|'ANKLES',SemanticGroupTypeV01>>;landmark_basis:Readonly<Record<'HEAD'|'SHOULDERS'|'HIPS'|'KNEES'|'ANKLES',Readonly<LandmarkBasisScalarV01>>>;semantic_anchors:Readonly<SemanticAnchorSetV01>;measurement_capability:Readonly<MeasurementCapabilityV01>;scale_evidence:Readonly<Record<ScaleMetricV02,Readonly<ScaleEvidenceV02>>>;global_crop:Readonly<{top:boolean;bottom:boolean;left:boolean;right:boolean}>;fresh:boolean;stable:boolean;confidence:number;measurement_age_ms:number}
export interface HumanObservationV02 {observation_version:'HumanObservationV02';timestamp_ms:number;state_version:number;measurement_age_ms:number;fresh:boolean;stable:boolean;quality:ObservationQualityV02;subject_recognition:Readonly<SubjectRecognitionStateV01>;observed_body:Readonly<ObservedBodyStateV01>;subject_lock:Readonly<SubjectLockObservationV01>;body_visibility:Readonly<BodyVisibilityGraphV01>;landmark_basis:ObservedBodyStateV01['landmark_basis'];measurement_capability:Readonly<MeasurementCapabilityV01>;semantic_anchors:Readonly<SemanticAnchorSetV01>;scale_evidence:ObservedBodyStateV01['scale_evidence'];motion_evidence:Readonly<HumanMotionEvidenceV02>;diagnostics:Readonly<{source_body_mode_summary:string|null;reacquisition_barrier:boolean;warnings:readonly string[]}>}

export type ControlActorV02='SUBJECT'|'CAMERA_OPERATOR'|'EITHER';
export type CameraFacingV04='FRONT'|'REAR'|'UNKNOWN';
export type PreviewMirrorStateV04='MIRRORED'|'NON_MIRRORED'|'UNKNOWN';
export type ShootingRelationV01='SUBJECT_FACING_CAMERA'|'SUBJECT_BACK_TO_CAMERA'|'UNKNOWN';
export type SensorXDeltaSignV01='NEGATIVE'|'POSITIVE'|'ZERO'|'UNKNOWN';
export type PhysicalXActionV01='SUBJECT_LEFT'|'SUBJECT_RIGHT'|'CAMERA_LEFT'|'CAMERA_RIGHT'|'UNSUPPORTED';
export interface V4DirectionContextV01 {camera_facing:CameraFacingV04;preview_mirror_state:PreviewMirrorStateV04;shooting_relation:ShootingRelationV01}
export interface SubjectPhysicalDirectionDecisionV01 {mapper_version:'SubjectPhysicalDirectionMapperV01';desired_sensor_delta_sign:SensorXDeltaSignV01;control_actor:ControlActorV02;shooting_relation:ShootingRelationV01;camera_facing:CameraFacingV04;preview_mirror_state:PreviewMirrorStateV04;physical_action:PhysicalXActionV01;display_axis_sign:-1|0|1;supported:boolean}
export type TargetFixtureIdV02='CENTER_UPPER_BODY'|'LEFT_THIRD_UPPER_BODY'|'RIGHT_THIRD_UPPER_BODY'|'CENTER_THREE_QUARTER'|'LEFT_THIRD_FULL_BODY'|'RIGHT_THIRD_FULL_BODY';
export interface LiveTargetV02 {target_version:'LiveTargetV02';id:TargetFixtureIdV02;source:'FIXTURE';label:string;required_body_parts:readonly BodyRegionV01[];primary_anchor:SemanticAnchorNameV01;target_anchor_x:number;tolerance_x:number;target_anchor_y:number|null;tolerance_y:number|null;scale_metric:ScaleMetricV02;target_scale:number;tolerance_scale:number;control_actor:ControlActorV02;ready_stable_ms:number}
export interface TargetMeasurementRequirementV01 {requirement_version:'TargetMeasurementRequirementV01';target_id:TargetFixtureIdV02;coverage_expectation:readonly BodyRegionV01[];required_anchors:readonly SemanticAnchorNameV01[];required_measurements:readonly MeasurementTypeV01[];scale_constraint:Readonly<{metric:ScaleMetricV02;target:number;tolerance:number}>;primary_anchor_constraint:Readonly<{anchor:SemanticAnchorNameV01;target_x:number;tolerance_x:number}>;secondary_constraint:Readonly<{target_y:number|null;tolerance_y:number|null}>;control_actor:ControlActorV02}
export type GapBlockingReasonV01='REGION_NOT_OBSERVED'|'REGION_EDGE_CROPPED'|'LOW_CONFIDENCE'|'INSUFFICIENT_BILATERAL_EVIDENCE'|'LANDMARK_REDUCTION_INVALID'|'STALE_EVIDENCE'|'NON_FINITE_GEOMETRY'|'UNKNOWN';
export type GapActionabilityV01='USER_FIXABLE'|'WAIT_FOR_STABLE_EVIDENCE'|'SYSTEM_MEASUREMENT_DEFECT'|'UNKNOWN';
export interface TargetGapBlockerV01 {requirement:MeasurementTypeV01;region:BodyRegionV01|null;reason:GapBlockingReasonV01;actionability:GapActionabilityV01}
export interface TargetObservationGapV01 {gap_version:'TargetObservationGapV01';target_id:TargetFixtureIdV02;ready:boolean;satisfied_requirements:readonly MeasurementTypeV01[];missing_requirements:readonly MeasurementTypeV01[];blocking_reasons:readonly Readonly<TargetGapBlockerV01>[];actionability:GapActionabilityV01;observation_state_version:number}

export type ConstraintRelationV01='TOO_LOW'|'IN_RANGE'|'TOO_HIGH'|'UNKNOWN';
export type V4Stage='ACQUIRE_SUBJECT'|'ACQUIRE_REQUIRED_BODY'|'ADJUST_SCALE'|'ALIGN_PRIMARY_ANCHOR'|'ALIGN_SECONDARY_CONSTRAINT'|'VERIFY'|'READY_LATCHED';
export interface LiveConstraintStateV01 {constraint_version:'LiveConstraintStateV01';stage:V4Stage;subject_satisfied:boolean;coverage_satisfied:boolean;measurement_ready:boolean;required_body_satisfied:boolean;missing_body_parts:readonly BodyRegionV01[];blocking_measurements:readonly string[];scale_relation:ConstraintRelationV01;scale_error_normalized:number|null;x_relation:ConstraintRelationV01;x_error_normalized:number|null;y_relation:ConstraintRelationV01;y_error_normalized:number|null;all_satisfied:boolean;control_actor:ControlActorV02;target_id:TargetFixtureIdV02;observation_state_version:number}

export type V4Action='MOVE_LEFT_SMALL'|'MOVE_RIGHT_SMALL'|'MOVE_CAMERA_LEFT_SMALL'|'MOVE_CAMERA_RIGHT_SMALL'|'MOVE_CLOSER_SMALL'|'MOVE_FARTHER_SMALL';
export type V4EpisodeState='ISSUED'|'WAIT_FOR_RESPONSE'|'WAIT_FOR_SETTLE'|'EVALUATED'|'CANCELLED';
export type V4Outcome='TARGET_REACHED'|'IMPROVED'|'NO_EFFECT'|'WRONG_DIRECTION';
export interface ControlEpochV04 {trial_id:number;episode_id:number;issued_at:number;stage:'ADJUST_SCALE'|'ALIGN_PRIMARY_ANCHOR';action:V4Action;actor:ControlActorV02;target_snapshot:Readonly<LiveTargetV02>;constraint_snapshot:Readonly<LiveConstraintStateV01>;observation_state_version:number;coordinate_basis:'SENSOR_NORMALIZED_NON_MIRRORED';direction_decision:Readonly<SubjectPhysicalDirectionDecisionV01>|null}
export interface V4Episode {trial_id:number;episode_id:number;state:V4EpisodeState;stage:'ADJUST_SCALE'|'ALIGN_PRIMARY_ANCHOR';action:V4Action;issued_at:number;response_observed:boolean;response_observed_at:number|null;movement_started_at:number|null;settle_started_at:number|null;settled_at:number|null;evaluated_at:number|null;cancelled_at:number|null;start_error:number;settled_error:number|null;outcome:V4Outcome|null;reminder_emitted:boolean;no_response_recorded:boolean;passive_relation_change:boolean;control_epoch:Readonly<ControlEpochV04>}
export interface V4Metrics {issued_actions:number;responded_actions:number;no_response_actions:number;causally_evaluable_actions:number;invalidated_actions:number;target_reached_count:number;improved_count:number;no_effect_count:number;wrong_direction_count:number;no_response_outcome_count:0;no_response_reissue_count:0;passive_relation_change_count:number;post_ready_ordinary:0;action_effectiveness:number|null;provider_calls:0;luna_calls:0;backend_per_frame_calls:0;raw_video_upload:0}
export interface V4Snapshot {timestamp_ms:number;armed:boolean;trial_id:number|null;stage:V4Stage;observation:Readonly<HumanObservationV02>;target:Readonly<LiveTargetV02>;target_requirement:Readonly<TargetMeasurementRequirementV01>;target_gap:Readonly<TargetObservationGapV01>;constraints:Readonly<LiveConstraintStateV01>;action:V4Action|null;direction_decision:Readonly<SubjectPhysicalDirectionDecisionV01>|null;instruction_copy_zh:string|null;acquisition_copy_zh:string|null;active_episode:Readonly<V4Episode>|null;last_episode:Readonly<V4Episode>|null;ready:boolean;ready_hold_elapsed_ms:number;reminder_due:boolean;metrics:Readonly<V4Metrics>}
