import type { TargetState } from '../closed-loop/types.js';
import { HumanStepServoV3 } from './controller.js';
import type { LiveMeasurementV3, V3FramingRelation, V3MeasurementQuality, V3Snapshot, V3XRelation } from './types.js';

export type V3ReplayClass='EXACT_COUNTERFACTUAL'|'STRUCTURAL_ONLY'|'NOT_RECONSTRUCTABLE';
export interface TraceLikeRow {timestamp:number;sequence:number;subject_present:boolean;center_x:number|null;height_ratio:number|null;velocity_x:number|null;velocity_scale:number|null;stable:boolean;target_x:number;target_height:number;delta_x:number|null;delta_scale:number|null;control_fresh?:boolean;measurement_age_ms?:number;framing_compatibility?:string|null;instruction_event?:{action:string}|null;episode_id?:number|null;episode_state?:string|null;verification?:string;ready?:boolean;semantic_framing?:{body_mode:string;scale_metric_type:string|null;anchor_x:number|null;scale:number|null;valid_for_precision_x:boolean;valid_for_precision_scale:boolean;distance_proxy:number|null;distance_proxy_velocity:number|null;distance_proxy_valid:boolean};}
export interface V3ReplaySummary {classification:V3ReplayClass;rows:number;v2_ordinary_actions:number;v2_stop_count:number;v2_target_reached:number;v2_no_effect:number;v2_wrong_direction:number;v2_post_ready_ordinary:number;v3_ordinary_actions:number;v3_stage_sequence:string[];v3_direction_reversals:number;v3_target_reached:number;v3_improved:number;v3_no_effect:number;v3_wrong_direction:number;v3_invalidated:number;v3_post_ready_ordinary:number;v3_ready:boolean;v3_corrections_to_ready:number|null;v3_action_effectiveness:number|null;}
const relationX=(x:number|null,target:TargetState):V3XRelation=>x===null?'UNKNOWN':x<target.center_x-target.tolerance_x?'TOO_LEFT':x>target.center_x+target.tolerance_x?'TOO_RIGHT':'IN_RANGE';
const framingRelation=(row:TraceLikeRow,target:TargetState):V3FramingRelation=>row.framing_compatibility==='TOO_TIGHT'?'TOO_CLOSE':row.framing_compatibility==='TOO_WIDE'?'TOO_FAR':row.framing_compatibility==='UNCERTAIN'?'UNKNOWN':row.delta_scale===null?'UNKNOWN':Math.abs(row.delta_scale)<=target.tolerance_height?'IN_RANGE':row.delta_scale>0?'TOO_FAR':'TOO_CLOSE';
export function measurementFromTraceRow(row:TraceLikeRow,target:TargetState):LiveMeasurementV3{
  const semantic=row.semantic_framing;const framing=framingRelation(row,target);const x=semantic?.valid_for_precision_x?semantic.anchor_x:row.delta_x===null?null:row.center_x;const xr=relationX(x??null,target);const usable=row.subject_present&&framing!=='UNKNOWN';const quality:V3MeasurementQuality=!usable?'INVALID':row.stable&&row.control_fresh!==false&&(framing!=='IN_RANGE'||xr!=='UNKNOWN')?'GOOD':'MARGINAL';
  return Object.freeze({timestamp_ms:row.timestamp,subject_state:row.subject_present?'PRESENT':'LOST',measurement_quality:quality,fresh:row.control_fresh!==false,stable:row.stable,framing_relation:framing,x_relation:xr,framing_motion:row.velocity_scale===null?'UNKNOWN':row.velocity_scale<-.08?'FARTHER':row.velocity_scale>.08?'CLOSER':'STILL',x_motion:row.velocity_x===null?'UNKNOWN':row.velocity_x<-.08?'LEFT':row.velocity_x>.08?'RIGHT':'STILL',state_version:row.sequence,measurement_age_ms:row.measurement_age_ms??0,diagnostics_ref:Object.freeze({measurement_id:`trace:${row.sequence}`,framing_error_normalized:row.delta_scale===null?null:Math.abs(row.delta_scale)/target.tolerance_height,x_error_normalized:row.delta_x===null?null:Math.abs(row.delta_x)/target.tolerance_x,framing_position:semantic?.distance_proxy??semantic?.scale??row.height_ratio,x_position:x??null,framing_comparison_key:usable?`FRAMING_V3:${target.id}`:null,x_comparison_key:xr!=='UNKNOWN'?`X_V3:${target.id}`:null,internal_body_mode:semantic?.body_mode??null,internal_scale_metric_type:semantic?.scale_metric_type??null,validity_reason:semantic?'TRACE_SEMANTIC':'TRACE_LEGACY'})});
}
export function classifyTrace(rows:readonly TraceLikeRow[]):V3ReplayClass{if(rows.length<3||!rows.some(r=>r.stable)||!rows.some(r=>r.subject_present))return 'NOT_RECONSTRUCTABLE';const present=rows.filter(r=>r.subject_present);const semanticRatio=present.filter(r=>r.semantic_framing).length/Math.max(1,present.length);const causal=rows.filter(r=>r.instruction_event||r.episode_state==='TERMINAL');return semanticRatio>=.8&&present.every(r=>typeof r.control_fresh==='boolean')&&causal.every(r=>r.semantic_framing)?'EXACT_COUNTERFACTUAL':'STRUCTURAL_ONLY';}
export function replayTraceV3(rows:readonly TraceLikeRow[],target:TargetState):{summary:V3ReplaySummary;snapshots:V3Snapshot[]}{
  const controller=new HumanStepServoV3(target);controller.arm(rows[0]?.timestamp??0);const snapshots=rows.map(row=>controller.update(measurementFromTraceRow(row,target)));const events=snapshots.filter(s=>s.action).map(s=>s.action!);const stages=snapshots.map(s=>s.stage).filter((v,i,a)=>i===0||a[i-1]!==v);let reversals=0;for(let i=1;i<events.length;i+=1){if((events[i-1].includes('LEFT')&&events[i].includes('RIGHT'))||(events[i-1].includes('RIGHT')&&events[i].includes('LEFT'))||(events[i-1].includes('CLOSER')&&events[i].includes('FARTHER'))||(events[i-1].includes('FARTHER')&&events[i].includes('CLOSER')))reversals+=1;}
  const final=snapshots.at(-1);const v2Events=rows.map(r=>r.instruction_event?.action).filter(Boolean) as string[];const readyIndex=rows.findIndex(r=>r.ready);const ordinary=(a:string)=>a.startsWith('MOVE_');const v2Ordinary=v2Events.filter(ordinary);const base=(action:string)=>action.replace('_SMALL','');let classification=classifyTrace(rows);let cursor=0;for(const event of events){while(cursor<v2Ordinary.length&&v2Ordinary[cursor]!==base(event))cursor+=1;if(cursor>=v2Ordinary.length){classification=classification==='NOT_RECONSTRUCTABLE'?classification:'STRUCTURAL_ONLY';break;}cursor+=1;}const terminalByEpisode=new Map<number|string,TraceLikeRow>();for(const row of rows)if(row.episode_state==='TERMINAL')terminalByEpisode.set(row.episode_id??`sequence:${row.sequence}`,row);const terminal=[...terminalByEpisode.values()];return {snapshots,summary:{classification,rows:rows.length,v2_ordinary_actions:v2Ordinary.length,v2_stop_count:v2Events.filter(a=>a==='STOP_HERE').length,v2_target_reached:terminal.filter(r=>r.verification==='SUCCESS').length,v2_no_effect:terminal.filter(r=>r.verification==='NO_EFFECT').length,v2_wrong_direction:terminal.filter(r=>r.verification==='WRONG_DIRECTION').length,v2_post_ready_ordinary:readyIndex<0?0:rows.slice(readyIndex+1).filter(r=>r.instruction_event?.action&&ordinary(r.instruction_event.action)).length,v3_ordinary_actions:final?.metrics.ordinary_action_count??0,v3_stage_sequence:stages,v3_direction_reversals:reversals,v3_target_reached:final?.metrics.target_reached_count??0,v3_improved:final?.metrics.improved_count??0,v3_no_effect:final?.metrics.no_effect_count??0,v3_wrong_direction:final?.metrics.wrong_direction_count??0,v3_invalidated:final?.metrics.invalidated_count??0,v3_post_ready_ordinary:final?.metrics.post_ready_ordinary??0,v3_ready:final?.ready??false,v3_corrections_to_ready:final?.metrics.corrections_to_ready??null,v3_action_effectiveness:final?.metrics.action_effectiveness??null}};
}
