import {Button,Image,Slider,Text,View} from '@tarojs/components'
import {useEffect,useRef,useState} from 'react'
import {api,type Session} from '../api/client'
import {platformRegistry} from '../platform/runtime'
import {MAX_LOCAL_REGIONS,PARAMETERS,clamp,cloneRecipe,createRecipe,defaultRegion,setAdjustment,type AdjustmentParameter,type AdjustmentRecipe,type AdjustmentScope} from './core'
import {MainFineTuneRuntime,RUNTIME_VERSION,type FineTuneSession} from './runtime'
import './FineTuneEditor.css'

const labels:Record<AdjustmentParameter,string>={BRIGHTNESS:'亮度',WARMTH:'色温',SATURATION:'饱和度',SOFTNESS:'柔和',BLUR:'背景虚化'}
export function FineTuneEditor({session,onComplete,onError}:{session:Session;onComplete:(value:Session)=>void;onError:(message:string)=>void}){
 const [recipe,setRecipe]=useState<AdjustmentRecipe|null>(null),[scope,setScope]=useState<AdjustmentScope>('ALL'),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('正在读取原始成片…');const runtime=useRef<FineTuneSession|null>(null),history=useRef<AdjustmentRecipe[]>([]),cursor=useRef(0),regions=useRef([defaultRegion(0)])
 useEffect(()=>{let cancelled=false;(async()=>{const source=await api.fineTuneSource(session.session_id);const saved=await api.fineTuneRecipe<AdjustmentRecipe>(session.session_id);const initial=saved?.recipe||createRecipe(session.session_id,source.asset_id);const opened=await new MainFineTuneRuntime().open({source:{asset_id:source.asset_id,checksum:source.checksum,content_url:api.fineTuneSourceContentUrl(session.session_id)},recipe:initial,options:{preview_long_edge:640,jpeg_quality:.92}});if(cancelled){opened.close();return}runtime.current=opened;history.current=[cloneRecipe(initial)];cursor.current=0;setRecipe(initial);setStatus('人物与背景遮罩尚未接入；整体和局部可用。')})().catch(error=>onError(error instanceof Error?error.message:String(error)));return()=>{cancelled=true;runtime.current?.close();if(preview.startsWith('blob:'))URL.revokeObjectURL(preview)}},[])
 useEffect(()=>{if(!recipe||!runtime.current)return;let active=true;runtime.current.project(recipe).then(result=>{if(!active)return;const url=URL.createObjectURL(result.blob);setPreview(old=>{if(old.startsWith('blob:'))URL.revokeObjectURL(old);return url})}).catch(error=>onError(String(error)));return()=>{active=false}},[recipe])
 const commit=(next:AdjustmentRecipe)=>{history.current=history.current.slice(0,cursor.current+1);history.current.push(cloneRecipe(next));cursor.current=history.current.length-1;setRecipe(next)}
 const activeRegion=regions.current[regions.current.length-1]
 const valueFor=(parameter:AdjustmentParameter)=>recipe?.adjustments.find(item=>item.scope===scope&&item.parameter===parameter&&(scope!=='LOCAL_REGION'||item.region?.id===activeRegion.id))?.value||0
 const change=(parameter:AdjustmentParameter,value:number)=>{if(recipe)commit(setAdjustment(recipe,scope,parameter,value,scope==='LOCAL_REGION'?activeRegion:undefined))}
 const undo=()=>{if(cursor.current>0){cursor.current--;setRecipe(cloneRecipe(history.current[cursor.current]))}},redo=()=>{if(cursor.current<history.current.length-1){cursor.current++;setRecipe(cloneRecipe(history.current[cursor.current]))}},reset=()=>{if(recipe)commit({...recipe,adjustments:[]})}
 const addLocal=()=>{if(regions.current.length>=MAX_LOCAL_REGIONS){setStatus('最多创建 3 个局部区域。');return}regions.current=[...regions.current,defaultRegion(regions.current.length)];setScope('LOCAL_REGION');setStatus(`已选择局部区域 ${regions.current.length}。`)}
 const finalize=async()=>{if(!recipe||!runtime.current||busy)return;setBusy(true);setStatus('正在保存配方并生成全质量成片…');try{const key=`recipe-${recipe.recipe_id}-${JSON.stringify(recipe.adjustments)}`;const saved=await api.saveFineTuneRecipe(session.session_id,recipe,key);const finalKey=`${session.session_id}:${saved.recipe_hash}:${RUNTIME_VERSION}`;if(recipe.adjustments.length===0){const value=await api.action(session.session_id,'SAVE_ADJUSTMENT_RECIPE',{adjustment_recipe_id:recipe.recipe_id,runtime_version:RUNTIME_VERSION,neutral:true},`finalize-${finalKey}`);onComplete(value);return}let frameCount=0,maxFrameGap=0,lastFrame=performance.now(),frameHandle=0;const heartbeat=(now:number)=>{frameCount++;maxFrameGap=Math.max(maxFrameGap,now-lastFrame);lastFrame=now;frameHandle=requestAnimationFrame(heartbeat)};if(typeof requestAnimationFrame==='function')frameHandle=requestAnimationFrame(heartbeat);const artifact=await runtime.current.renderFinal(recipe,finalKey);if(frameHandle)cancelAnimationFrame(frameHandle);const upload=await platformRegistry.uploadDerived(session.session_id,artifact.blob,finalKey);if(!upload.ok||!upload.value)throw new Error(upload.code);const value=await api.action(session.session_id,'SAVE_ADJUSTMENT_RECIPE',{adjustment_recipe_id:recipe.recipe_id,derived_upload_asset_id:upload.value.asset_id,runtime_version:RUNTIME_VERSION,render_backend:artifact.backend,render_metrics:{decode_ms:artifact.decode_ms,render_ms:artifact.render_ms,encode_ms:artifact.encode_ms,total_ms:artifact.total_ms,width:artifact.width,height:artifact.height,ui_frame_count_during_render:frameCount,ui_max_frame_gap_ms:maxFrameGap,ui_responsive:artifact.backend==='WORKER_OFFSCREENCANVAS'&&frameCount>0},mask_identity:null},`finalize-${finalKey}`);onComplete(value)}catch(error){onError(error instanceof Error?error.message:String(error));setStatus('生成未完成，已保存的配方可在刷新后继续。')}finally{setBusy(false)}}
 if(!recipe)return <View className='fineTunePanel'><Text>{status}</Text></View>
 const parameters=scope==='BACKGROUND'?[...PARAMETERS,'BLUR' as const]:PARAMETERS
 return <View className='fineTunePanel'><Text className='sectionTitle'>微调</Text><Text className='fineTuneStatus'>{status}</Text>{preview&&<Image className='fineTunePreview' mode='aspectFit' src={preview}/>}<View className='scopeTabs'>{(['ALL','PERSON','BACKGROUND','LOCAL_REGION'] as AdjustmentScope[]).map(item=><Button key={item} className={scope===item?'chip activeChip':'chip'} disabled={item==='PERSON'||item==='BACKGROUND'} onClick={()=>setScope(item)}>{{ALL:'整体',PERSON:'人物',BACKGROUND:'背景',LOCAL_REGION:'局部'}[item]}</Button>)}</View>{scope==='LOCAL_REGION'&&<Button className='secondary compact' onClick={addLocal}>新增局部区域（{regions.current.length}/3）</Button>}{parameters.map(parameter=><View className='sliderRow' key={parameter}><Text>{labels[parameter]}</Text><View className='sliderControl'><Button className='stepButton' aria-label={`${labels[parameter]}减少`} onClick={()=>change(parameter,clamp(valueFor(parameter)-.1))}>−</Button><Slider min={-100} max={100} value={Math.round(valueFor(parameter)*100)} disabled={parameter==='BLUR'&&scope!=='BACKGROUND'} onChange={(event:any)=>change(parameter,event.detail.value/100)} activeColor='#e9b96e'/><Button className='stepButton' aria-label={`${labels[parameter]}增加`} onClick={()=>change(parameter,clamp(valueFor(parameter)+.1))}>＋</Button></View></View>)}<View className='inlineActions'><Button className='secondary compact' onClick={undo}>撤销</Button><Button className='secondary compact' onClick={redo}>重做</Button><Button className='secondary compact' onClick={reset}>重置</Button></View><Button className='secondary compact' onTouchStart={()=>setPreview(api.fineTuneSourceContentUrl(session.session_id))} onTouchEnd={()=>recipe&&runtime.current?.project(recipe).then(result=>setPreview(URL.createObjectURL(result.blob)))}>按住对比原图</Button><Button className='primary' disabled={busy} onClick={finalize}>{busy?'正在生成成片…':'完成微调'}</Button></View>
}
