import {RUNTIME_VERSION,renderPixels,validateRecipe,type AdjustmentRecipe,type OptionalMaskSet,type SourceImage} from './core'
export type SourceAssetRef={asset_id:string;checksum:{algorithm:'SHA256';value:string};content_url:string}
export type RuntimeOptions={preview_long_edge?:number;jpeg_quality?:number}
export type PreviewProjection={blob:Blob;width:number;height:number;render_ms:number}
export type FinalRenderArtifact={blob:Blob;width:number;height:number;render_ms:number;encode_ms:number;backend:'WORKER_OFFSCREENCANVAS'|'MAIN_THREAD_CANVAS2D'}
export type RenderMetrics={preview_count:number;final_count:number;last_render_ms:number;worker_used:boolean;network_calls_per_slider:0}
export interface FineTuneSession{project(recipe:AdjustmentRecipe):Promise<PreviewProjection>;renderFinal(recipe:AdjustmentRecipe,idempotencyKey:string):Promise<FinalRenderArtifact>;metrics():RenderMetrics;warnings():string[];close():void}
export interface FineTuneRuntime{open(input:{source:SourceAssetRef;recipe:AdjustmentRecipe;masks?:OptionalMaskSet;options:RuntimeOptions}):Promise<FineTuneSession>}
const canvasBlob=(source:SourceImage,data:Uint8ClampedArray,quality:number)=>{const canvas=document.createElement('canvas');canvas.width=source.width;canvas.height=source.height;const context=canvas.getContext('2d',{alpha:false});if(!context)throw new Error('CANVAS2D_UNAVAILABLE');context.putImageData(new ImageData(new Uint8ClampedArray(data),source.width,source.height),0,0);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('JPEG_ENCODE_FAILED')),'image/jpeg',quality))}
const assertJpeg=async(blob:Blob)=>{const signature=new Uint8Array(await blob.slice(0,3).arrayBuffer());if(blob.type!=='image/jpeg'||signature[0]!==0xff||signature[1]!==0xd8||signature[2]!==0xff)throw new Error('INVALID_WORKER_JPEG')}
async function decode(url:string,assetId:string):Promise<SourceImage>{const response=await fetch(url);if(!response.ok)throw new Error('SOURCE_DECODE_FAILED');const bitmap=await createImageBitmap(await response.blob(),{imageOrientation:'from-image'});try{const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('CANVAS2D_UNAVAILABLE');context.drawImage(bitmap,0,0);return {width:bitmap.width,height:bitmap.height,data:new Uint8ClampedArray(context.getImageData(0,0,bitmap.width,bitmap.height).data),assetId}}finally{bitmap.close()}}
function downsample(source:SourceImage,longEdge:number):SourceImage{const scale=Math.min(1,longEdge/Math.max(source.width,source.height));if(scale===1)return {...source,data:new Uint8ClampedArray(source.data)};const width=Math.max(1,Math.round(source.width*scale)),height=Math.max(1,Math.round(source.height*scale));const input=document.createElement('canvas');input.width=source.width;input.height=source.height;input.getContext('2d')!.putImageData(new ImageData(new Uint8ClampedArray(source.data),source.width,source.height),0,0);const output=document.createElement('canvas');output.width=width;output.height=height;const context=output.getContext('2d',{willReadFrequently:true})!;context.drawImage(input,0,0,width,height);return {width,height,data:new Uint8ClampedArray(context.getImageData(0,0,width,height).data),assetId:source.assetId}}
class MainSession implements FineTuneSession{private stats:RenderMetrics={preview_count:0,final_count:0,last_render_ms:0,worker_used:false,network_calls_per_slider:0};private finalByKey=new Map<string,Promise<FinalRenderArtifact>>();private closed=false;constructor(private source:SourceImage,private preview:SourceImage,private masks:OptionalMaskSet|undefined,private options:RuntimeOptions){}async project(recipe:AdjustmentRecipe){this.assert(recipe);const result=renderPixels(this.preview,recipe,this.masks);const blob=await canvasBlob(this.preview,result.data,.86);this.stats.preview_count++;this.stats.last_render_ms=result.renderMs;return {blob,width:this.preview.width,height:this.preview.height,render_ms:result.renderMs}}renderFinal(recipe:AdjustmentRecipe,key:string){this.assert(recipe);const existing=this.finalByKey.get(key);if(existing)return existing;const operation=this.doFinal(recipe);this.finalByKey.set(key,operation);return operation}private async doFinal(recipe:AdjustmentRecipe):Promise<FinalRenderArtifact>{this.stats.final_count++;if(typeof Worker!=='undefined'&&typeof OffscreenCanvas!=='undefined'){try{
 // @ts-ignore Taro/Webpack consumes this worker URL while the repository typecheck target remains CommonJS.
 const worker=new Worker(new URL('./final.worker.ts',import.meta.url),{type:'module'});const artifact=await new Promise<FinalRenderArtifact>((resolve,reject)=>{const id=1;worker.onmessage=(event)=>event.data.ok?resolve(event.data.artifact):reject(new Error(event.data.error));worker.onerror=event=>reject(new Error(event.message));const source={...this.source,data:new Uint8ClampedArray(this.source.data)};worker.postMessage({id,source,recipe,masks:this.masks,quality:this.options.jpeg_quality||.92},[source.data.buffer])});worker.terminate();await assertJpeg(artifact.blob);this.stats.worker_used=true;this.stats.last_render_ms=artifact.render_ms;return artifact}catch{}}
 const rendered=renderPixels(this.source,recipe,this.masks),started=performance.now(),blob=await canvasBlob(this.source,rendered.data,this.options.jpeg_quality||.92);this.stats.last_render_ms=rendered.renderMs;return {blob,width:this.source.width,height:this.source.height,render_ms:rendered.renderMs,encode_ms:performance.now()-started,backend:'MAIN_THREAD_CANVAS2D'}}metrics(){return {...this.stats}}warnings(){const warnings:string[]=[];if(!this.stats.worker_used)warnings.push('WORKER_FALLBACK_AVAILABLE');if(!this.masks)warnings.push('AUTO_SEMANTIC_MASK_NOT_YET_PASS');return warnings}close(){this.closed=true;this.finalByKey.clear()}private assert(recipe:AdjustmentRecipe){if(this.closed)throw new Error('SESSION_CLOSED');if(recipe.source_asset_id!==this.source.assetId)throw new Error('SOURCE_RECIPE_MISMATCH');validateRecipe(recipe)}}
export class MainFineTuneRuntime implements FineTuneRuntime{async open({source,recipe,masks,options}:{source:SourceAssetRef;recipe:AdjustmentRecipe;masks?:OptionalMaskSet;options:RuntimeOptions}){if(source.asset_id!==recipe.source_asset_id)throw new Error('SOURCE_RECIPE_MISMATCH');const decoded=await decode(source.content_url,source.asset_id);return new MainSession(decoded,downsample(decoded,options.preview_long_edge||640),masks,options)}}
export {RUNTIME_VERSION}
