import {renderPixels,validateRecipe,type AdjustmentRecipe,type OptionalMaskSet,type SourceImage} from './core'
import type {FinalRenderArtifact,FineTuneRuntime,FineTuneSession,RenderMetrics,RuntimeOptions,SourceAssetRef} from './runtime'

type WxCanvas={width:number;height:number;getContext:(kind:'2d',options?:unknown)=>any;createImage:()=>any;toDataURL?:(type?:string,quality?:number)=>string}
type WxLike={downloadFile:(options:any)=>void;createOffscreenCanvas:(options:any)=>WxCanvas;getFileSystemManager:()=>any;env:{USER_DATA_PATH:string};base64ToArrayBuffer:(value:string)=>ArrayBuffer}
const wxApi=():WxLike=>{const value=(globalThis as any).wx;if(!value?.downloadFile||!value?.createOffscreenCanvas)throw new Error('WECHAT_CANVAS2D_UNAVAILABLE');return value}
const download=(url:string)=>new Promise<string>((resolve,reject)=>wxApi().downloadFile({url,success:(result:any)=>result.statusCode===200?resolve(result.tempFilePath):reject(new Error(`SOURCE_DOWNLOAD_HTTP_${result.statusCode}`)),fail:(error:any)=>reject(new Error(error?.errMsg||'SOURCE_DOWNLOAD_FAILED'))}))
const loadImage=(canvas:WxCanvas,path:string)=>new Promise<any>((resolve,reject)=>{const image=canvas.createImage();image.onload=()=>resolve(image);image.onerror=(error:any)=>reject(new Error(error?.errMsg||'SOURCE_DECODE_FAILED'));image.src=path})
const imageData=(context:any,data:Uint8ClampedArray,width:number,height:number)=>{const output=context.createImageData(width,height);output.data.set(data);return output}
const nearestDownsample=(source:SourceImage,longEdge:number):SourceImage=>{const scale=Math.min(1,longEdge/Math.max(source.width,source.height));if(scale===1)return {...source,data:new Uint8ClampedArray(source.data)};const width=Math.max(1,Math.round(source.width*scale)),height=Math.max(1,Math.round(source.height*scale)),data=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const sourceX=Math.min(source.width-1,Math.floor(x/scale)),sourceY=Math.min(source.height-1,Math.floor(y/scale)),from=(sourceY*source.width+sourceX)*4,to=(y*width+x)*4;data[to]=source.data[from];data[to+1]=source.data[from+1];data[to+2]=source.data[from+2];data[to+3]=source.data[from+3]}return {width,height,data,assetId:source.assetId}}
async function decode(source:SourceAssetRef){const started=Date.now(),wx=wxApi(),path=await download(source.content_url),canvas=wx.createOffscreenCanvas({type:'2d',width:1,height:1}),image=await loadImage(canvas,path);canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,image.width,image.height);const pixels=context.getImageData(0,0,image.width,image.height).data;return {source:{width:image.width,height:image.height,data:new Uint8ClampedArray(pixels),assetId:source.asset_id} as SourceImage,decodeMs:Date.now()-started}}

class WeChatFineTuneSession implements FineTuneSession{
 private closed=false
 private finalByKey=new Map<string,Promise<FinalRenderArtifact>>()
 private stats:RenderMetrics
 constructor(private source:SourceImage,private preview:SourceImage,private masks:OptionalMaskSet|undefined,private options:RuntimeOptions,private decodeMs:number){this.stats={preview_count:0,final_count:0,last_render_ms:0,worker_used:false,network_calls_per_slider:0,preview_jpeg_encode_count:0,preview_object_url_count:0,preview_width:preview.width,preview_height:preview.height}}
 async project(recipe:AdjustmentRecipe){this.assert(recipe);const result=renderPixels(this.preview,recipe,this.masks,{cacheSoftenedSource:true});this.stats.preview_count++;this.stats.last_render_ms=result.renderMs;return {data:result.data,width:this.preview.width,height:this.preview.height,render_ms:result.renderMs}}
 renderFinal(recipe:AdjustmentRecipe,key:string){this.assert(recipe);const existing=this.finalByKey.get(key);if(existing)return existing;const operation=this.doFinal(recipe,key);this.finalByKey.set(key,operation);return operation}
 private async doFinal(recipe:AdjustmentRecipe,key:string):Promise<FinalRenderArtifact>{this.stats.final_count++;const rendered=renderPixels(this.source,recipe,this.masks),encodeStarted=Date.now(),wx=wxApi(),canvas=wx.createOffscreenCanvas({type:'2d',width:this.source.width,height:this.source.height}),context=canvas.getContext('2d',{alpha:false});context.putImageData(imageData(context,rendered.data,this.source.width,this.source.height),0,0);if(!canvas.toDataURL)throw new Error('WECHAT_JPEG_ENCODE_UNAVAILABLE');const encoded=canvas.toDataURL('image/jpeg',this.options.jpeg_quality||.92),base64=encoded.split(',')[1];if(!base64)throw new Error('WECHAT_JPEG_ENCODE_FAILED');const bytes=wx.base64ToArrayBuffer(base64),filePath=`${wx.env.USER_DATA_PATH}/fine-tune-${key.replace(/[^a-zA-Z0-9_-]/g,'_')}.jpg`;await new Promise<void>((resolve,reject)=>wx.getFileSystemManager().writeFile({filePath,data:bytes,encoding:'binary',success:()=>resolve(),fail:(error:any)=>reject(new Error(error?.errMsg||'WECHAT_JPEG_WRITE_FAILED'))}));const encodeMs=Date.now()-encodeStarted;this.stats.last_render_ms=rendered.renderMs;return {filePath,bytes:bytes.byteLength,width:this.source.width,height:this.source.height,decode_ms:this.decodeMs,render_ms:rendered.renderMs,encode_ms:encodeMs,total_ms:this.decodeMs+rendered.renderMs+encodeMs,backend:'WECHAT_OFFSCREEN_CANVAS2D'}}
 metrics(){return {...this.stats}}
 warnings(){const result=['WECHAT_DEVICE_ACCEPTANCE_NOT_EXERCISED'];if(!this.masks)result.push('AUTO_SEMANTIC_MASK_NOT_YET_PASS');return result}
 close(){this.closed=true;this.finalByKey.clear()}
 private assert(recipe:AdjustmentRecipe){if(this.closed)throw new Error('SESSION_CLOSED');if(recipe.source_asset_id!==this.source.assetId)throw new Error('SOURCE_RECIPE_MISMATCH');validateRecipe(recipe)}
}
export class WeChatFineTuneRuntime implements FineTuneRuntime{async open({source,recipe,masks,options}:{source:SourceAssetRef;recipe:AdjustmentRecipe;masks?:OptionalMaskSet;options:RuntimeOptions}){if(source.asset_id!==recipe.source_asset_id)throw new Error('SOURCE_RECIPE_MISMATCH');const decoded=await decode(source);return new WeChatFineTuneSession(decoded.source,nearestDownsample(decoded.source,options.preview_long_edge||480),masks,options,decoded.decodeMs)}}
