import test from 'node:test';
import assert from 'node:assert/strict';
import { ControlledFixtureOrientationProvider } from '../motion/fixture-orientation-provider.js';
import { DeviceOrientationProvider } from '../motion/device-orientation-provider.js';
import { readScreenPosture, normalizeHeadingForScreen } from '../motion/orientation-normalization.js';
import { normalize360, shortestAngularDelta, YawUnwrapper } from '../motion/yaw-unwrapper.js';
import { CoverageTracker } from '../sweep/coverage-tracker.js';
import { evaluateQuality } from '../sweep/quality-gate.js';
import { fingerprintDistance, isDuplicate } from '../sweep/duplicate-gate.js';
import { KeyframeSampler } from '../sweep/keyframe-sampler.js';
import { configForMode, type FrameMetrics, type SceneSweepKeyframe } from '../sweep/types.js';
import { SceneSweepRuntime } from '../sweep/sweep-runtime.js';
import { canonicalManifestJson } from '../spatial/scene-sweep-manifest.js';
import { YawMap } from '../spatial/yaw-map.js';
import { replayFixtures } from '../fixtures/replay-fixtures.js';
import { runReplay } from '../replay/replay-runner.js';
import { SweepTelemetry } from '../telemetry/telemetry.js';

const frame = (yaw: number, overrides: Partial<FrameMetrics> = {}): FrameMetrics => ({ timestamp_ms: yaw * 10 + 1000, yaw_deg: yaw, width: 640, height: 480, blur_score: 30, exposure_mean: 128, highlight_clipping_ratio: 0, shadow_clipping_ratio: 0, fingerprint: [yaw / 360, 1 - yaw / 360], ...overrides });
const keyframe = (yaw: number, sequence: number): SceneSweepKeyframe => ({ ...frame(yaw), keyframe_id: `kf-${sequence}`, sequence, quality_status: 'ACCEPTED', selection_reason: sequence === 1 ? 'INITIAL' : 'ANGULAR_NOVELTY' });
const orientation = (yaw: number, t = 0) => ({ timestamp_ms: t, relative_yaw_deg: yaw, raw_heading_deg: normalize360(yaw), confidence: 'HIGH' as const, status: 'ACTIVE' as const, screen_orientation: 'PORTRAIT_PRIMARY' as const, source: 'CONTROLLED_FIXTURE' as const });

test('fixture permission starts uninitialized and becomes active only on request', async () => { const p = new ControlledFixtureOrientationProvider(); assert.equal(p.state, 'UNINITIALIZED'); assert.equal(await p.requestPermission(), 'ACTIVE'); });
test('device provider reports unavailable when browser orientation API is absent',()=>assert.equal(new DeviceOrientationProvider().state,'UNAVAILABLE'));
test('fixture emits only while started', async () => { const p = new ControlledFixtureOrientationProvider(); await p.requestPermission(); const values:number[]=[]; p.emit(1,0); p.start(s=>values.push(s.relative_yaw_deg));p.emit(2,1);p.stop();p.emit(3,2);assert.deepEqual(values,[2]); });
test('fixture reset does not fabricate new samples', async () => { const p = new ControlledFixtureOrientationProvider(); await p.requestPermission();const values:number[]=[];p.start(s=>values.push(s.relative_yaw_deg));p.resetBaseline();assert.deepEqual(values,[]); });
test('normalize360 handles negative values',()=>assert.equal(normalize360(-1),359));
test('normalize360 handles multiple rotations',()=>assert.equal(normalize360(721),1));
test('shortest delta crosses 359 to 0 forward',()=>assert.equal(shortestAngularDelta(359,0),1));
test('shortest delta crosses 0 to 359 backward',()=>assert.equal(shortestAngularDelta(0,359),-1));
test('yaw unwrap handles repeated forward wrap crossings',()=>{const u=new YawUnwrapper();assert.deepEqual([358,359,0,1,359,0].map(v=>u.push(v)),[358,359,360,361,359,360]);});
test('yaw unwrap reset establishes a new baseline stream',()=>{const u=new YawUnwrapper();u.push(350);u.push(0);u.reset();assert.equal(u.push(20),20);});
test('portrait screen posture recognizes zero and 180',()=>{assert.equal(readScreenPosture(0),'PORTRAIT_PRIMARY');assert.equal(readScreenPosture(180),'PORTRAIT_PRIMARY');});
test('landscape posture recognizes 90 and 270',()=>{assert.equal(readScreenPosture(90),'LANDSCAPE_PRIMARY');assert.equal(readScreenPosture(270),'LANDSCAPE_PRIMARY');});
test('screen compensation preserves normalized heading',()=>assert.equal(normalizeHeadingForScreen(350,'LANDSCAPE_PRIMARY',90),80));
test('unsupported posture refuses heading',()=>assert.equal(normalizeHeadingForScreen(10,'UNSUPPORTED'),null));
test('coverage reaches exact 120 degree span',()=>{const c=new CoverageTracker();for(let y=0;y<=120;y+=10)c.observe(y);assert.equal(c.snapshot().span_deg,120);});
test('coverage reversal does not double count traversed arc',()=>{const c=new CoverageTracker();[0,20,40,60,40,20,0].forEach(y=>c.observe(y));assert.equal(c.snapshot().span_deg,60);assert.equal(c.snapshot().direction,'MIXED');});
test('right-to-left direction is reported',()=>{const c=new CoverageTracker();[0,-10,-20,-30].forEach(y=>c.observe(y));assert.equal(c.snapshot().direction,'RIGHT_TO_LEFT');});
test('jitter below threshold does not create direction changes',()=>{const c=new CoverageTracker();[0,.2,-.1,.3].forEach(y=>c.observe(y));assert.equal(c.snapshot().direction,'UNDETERMINED');});
test('single sensor spike is rejected without false coverage',()=>{const c=new CoverageTracker(45);[0,10,20,170,30].forEach(y=>c.observe(y));assert.equal(c.snapshot().span_deg,30);assert.equal(c.snapshot().rejected_spikes,1);});
test('accepted point after rejected spike compares with last valid point',()=>{const c=new CoverageTracker(45);[0,10,200,20].forEach(y=>c.observe(y));assert.equal(c.snapshot().span_deg,20);});
test('persistent startup jump rebases without adding false coverage',()=>{const c=new CoverageTracker(45);[0,90,90.5,91,92,102].forEach(y=>c.observe(y));assert.equal(c.snapshot().span_deg,11);assert.equal(c.currentYaw(),11);assert.equal(c.snapshot().rejected_spikes,3);});
test('persistent negative startup jump recovers right-to-left tracking',()=>{const c=new CoverageTracker(45);[0,-90,-90.5,-91,-101,-111].forEach(y=>c.observe(y));assert.equal(c.snapshot().span_deg,20);assert.equal(c.snapshot().direction,'RIGHT_TO_LEFT');});
test('blur gate rejects severe blur',()=>assert.deepEqual(evaluateQuality(frame(0,{blur_score:2})),{accepted:false,reason:'BLUR'}));
test('device-calibrated edge score at threshold passes blur gate',()=>assert.deepEqual(evaluateQuality(frame(0,{blur_score:3})),{accepted:true}));
test('underexposure mean is rejected',()=>assert.equal(evaluateQuality(frame(0,{exposure_mean:4})).reason,'UNDEREXPOSED'));
test('shadow clipping is rejected independently of mean',()=>assert.equal(evaluateQuality(frame(0,{shadow_clipping_ratio:.9})).reason,'UNDEREXPOSED'));
test('overexposure mean is rejected',()=>assert.equal(evaluateQuality(frame(0,{exposure_mean:250})).reason,'OVEREXPOSED'));
test('highlight clipping is rejected independently of mean',()=>assert.equal(evaluateQuality(frame(0,{highlight_clipping_ratio:.9})).reason,'OVEREXPOSED'));
test('ordinary sharp exposure passes quality gate',()=>assert.deepEqual(evaluateQuality(frame(0)),{accepted:true}));
test('fingerprint distance is deterministic L1 distance',()=>assert.ok(Math.abs(fingerprintDistance([.2,.8],[.3,.7])-.2)<1e-12));
test('missing fingerprints do not imply duplicate',()=>assert.equal(fingerprintDistance(undefined,[1]),Infinity));
test('same visual fingerprint at meaningful yaw is retained',()=>assert.equal(isDuplicate(frame(20,{fingerprint:[.5,.5]}),frame(0,{fingerprint:[.5,.5]})),false));
test('same view at nearly identical yaw is duplicate',()=>assert.equal(isDuplicate(frame(2,{fingerprint:[.5,.5]}),frame(0,{fingerprint:[.5,.5]})),true));
test('sampler accepts initial frame',()=>{const s=new KeyframeSampler();assert.equal(s.evaluate(frame(0))?.selection_reason,'INITIAL');});
test('sampler enforces angular novelty',()=>{const s=new KeyframeSampler(12);s.evaluate(frame(0));assert.equal(s.evaluate(frame(8)),null);assert.equal(s.rejections.ANGULAR_NOVELTY,1);});
test('sampler accepts configured angular step',()=>{const s=new KeyframeSampler(12);s.evaluate(frame(0));assert.ok(s.evaluate(frame(12)));});
test('sampler records duplicate before novelty rejection',()=>{const s=new KeyframeSampler(12);s.evaluate(frame(0,{fingerprint:[.5,.5]}));s.evaluate(frame(2,{fingerprint:[.5,.5]}));assert.equal(s.rejections.DUPLICATE,1);});
test('sampler bounds retained keyframes',()=>{const s=new KeyframeSampler(10,3);[0,10,20,30].forEach(y=>s.evaluate(frame(y)));assert.equal(s.keyframes.length,3);assert.equal(s.rejections.CAP,1);});
test('sampler reset clears frames and diagnostics',()=>{const s=new KeyframeSampler();s.evaluate(frame(0));s.evaluate(frame(1));s.reset();assert.equal(s.keyframes.length,0);assert.equal(s.rejections.ANGULAR_NOVELTY,0);});
test('sampler delays rather than permanently blocks an all-blurred scene',()=>{const s=new KeyframeSampler(12,12,12);let selected=null;for(let i=0;i<12;i++)selected=s.evaluate(frame(i*2,{blur_score:2}));assert.equal(selected?.selection_reason,'FALLBACK_IMPERFECT');assert.equal(s.rejections.BLUR,12);});
test('short fast-turn blur burst is not selected before fallback window',()=>{const s=new KeyframeSampler(12,12,12);for(let i=0;i<8;i++)assert.equal(s.evaluate(frame(i*2,{blur_score:2})),null);assert.equal(s.keyframes.length,0);});
test('quick runtime auto-completes at target',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','q',0);for(let y=0;y<=110;y+=10)r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'COMPLETE');});
test('quick runtime completes when displayed coverage rounds to target',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','rounded-target',0);for(const y of [0,40,80,109.6])r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'COMPLETE');});
test('quick runtime does not complete outside display tolerance',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','below-tolerance',0);for(const y of [0,40,80,109.4])r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'SWEEPING');});
test('runtime exposes continuity-corrected yaw after startup rebase',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','q',0);[0,90,90.5,91,101].forEach((y,i)=>r.observeOrientation(orientation(y,i)));assert.equal(r.currentYawDeg(),10);});
test('wide runtime remains sweeping below 180',()=>{const r=new SceneSweepRuntime('WIDE_SWEEP','w',0);for(let y=0;y<=170;y+=10)r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'SWEEPING');});
test('wide runtime completes within the documented six degree sensor tolerance',()=>{const r=new SceneSweepRuntime('WIDE_SWEEP','wide-near-target',0);for(const y of [0,30,60,90,120,150,174])r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'COMPLETE');assert.equal(r.manifest().coverage_deg,174);});
test('wide runtime remains active below its near-target tolerance',()=>{const r=new SceneSweepRuntime('WIDE_SWEEP','wide-below-tolerance',0);for(const y of [0,30,60,90,120,150,173.9])r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'SWEEPING');});
test('wide runtime completes after reversal reaches new coverage beyond start',()=>{const r=new SceneSweepRuntime('WIDE_SWEEP','wide-reversal',0);for(const y of [0,30,60,90,120,150,120,90,60,30,0,-30])r.observeOrientation(orientation(y,y));assert.equal(r.session.status,'COMPLETE');assert.equal(r.manifest().direction,'MIXED');assert.equal(r.manifest().coverage_deg,180);});
test('quick completion does not leak state into a reversed wide runtime',()=>{const q=new SceneSweepRuntime('QUICK_SWEEP','first-quick',0);for(const y of [0,30,60,90,110])q.observeOrientation(orientation(y,y));assert.equal(q.session.status,'COMPLETE');const w=new SceneSweepRuntime('WIDE_SWEEP','second-wide',1000);for(const y of [0,30,60,90,120,150,120,90,60,30,0,-30])w.observeOrientation(orientation(y,1000+y));assert.equal(w.session.status,'COMPLETE');assert.equal(w.manifest().coverage_deg,180);});
test('cancel sweep blocks later orientation mutation',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','c',0);r.observeOrientation(orientation(0));r.cancel(4);assert.equal(r.observeOrientation(orientation(10,10)),false);assert.equal(r.coverage.snapshot().span_deg,0);});
test('new runtime starts without prior sweep state',()=>{const a=new SceneSweepRuntime('QUICK_SWEEP','a',0);a.observeOrientation(orientation(50));a.observeFrame(frame(50));const b=new SceneSweepRuntime('QUICK_SWEEP','b',1);assert.equal(b.coverage.snapshot().span_deg,0);assert.equal(b.sampler.keyframes.length,0);});
test('frame before orientation is rejected',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','x',0);assert.equal(r.observeFrame(frame(0)),false);});
test('camera source dimensions are not overwritten by evaluation canvas size',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','x',0);r.setCameraSourceDimensions(1920,1080);r.observeOrientation(orientation(0));r.observeFrame(frame(0,{width:160,height:90}));assert.deepEqual(r.manifest().camera,{facing:'environment',source_width:1920,source_height:1080});});
test('manifest strips transient frame references',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','x',0);r.observeOrientation(orientation(0));r.observeFrame(frame(0,{transient_frame_ref:'blob:secret'} as Partial<FrameMetrics>));assert.equal('transient_frame_ref' in r.manifest().ordered_keyframes[0]!,false);});
test('manifest privacy and network counters are hard zero',()=>{const m=new SceneSweepRuntime('QUICK_SWEEP','x',0).manifest();assert.deepEqual(m.privacy,{raw_video_uploaded:false,raw_frame_stream_uploaded:false,third_party_image_uploaded:false,committed_user_media:false});assert.deepEqual(m.network,{provider_calls:0,luna_calls:0,backend_per_frame_calls:0});});
test('manifest serialization is deterministic',()=>{const r=new SceneSweepRuntime('QUICK_SWEEP','fixed',10);r.observeOrientation(orientation(0,10));r.finish(20);assert.equal(canonicalManifestJson(r.manifest()),canonicalManifestJson(r.manifest()));});
test('yaw map orders keyframes spatially',()=>assert.deepEqual(new YawMap([keyframe(20,2),keyframe(-10,1)]).serialize().ordered_yaws_deg,[-10,20]));
test('yaw map returns nearest keyframe',()=>assert.equal(new YawMap([keyframe(-10,1),keyframe(20,2)]).nearest(12)?.yaw_deg,20));
test('yaw map reports material coverage gaps',()=>assert.deepEqual(new YawMap([keyframe(0,1),keyframe(30,2),keyframe(40,3)]).gaps(20),[{from_yaw_deg:0,to_yaw_deg:30,size_deg:30}]));
test('quick and wide configs have bounded memory policies',()=>{assert.equal(configForMode('QUICK_SWEEP').max_keyframes,12);assert.equal(configForMode('WIDE_SWEEP').max_keyframes,18);});
test('telemetry queue reports never above one',()=>{const t=new SweepTelemetry();t.start(0);assert.equal(t.snapshot(1000,30,[1920,1080],99).queue_length,1);});
test('telemetry quality percentiles are stable',()=>{const t=new SweepTelemetry();t.start(0);[1,2,3,100].forEach(v=>t.candidate(v,true));const s=t.snapshot(1000,30,[640,480],0);assert.equal(s.quality_eval_ms_p50,2);assert.equal(s.quality_eval_ms_p95,3);});
test('camera-independent steady replay reaches quick target without overscan dependency',async()=>{const span=(await runReplay(replayFixtures.steady120)).coverage.span_deg;assert.ok(span>=110&&span<=120);});
test('camera-independent reverse replay preserves right-to-left',async()=>assert.equal((await runReplay(replayFixtures.reverse120)).manifest.direction,'RIGHT_TO_LEFT'));
test('camera-independent wide replay completes wide mode',async()=>assert.equal((await runReplay(replayFixtures.wide180,'WIDE_SWEEP')).manifest.status,'COMPLETE'));
test('replay rejects imperfect quality candidates with reasons',async()=>{const r=await runReplay(replayFixtures.imperfect);assert.ok(r.rejections.BLUR>0);assert.ok(r.rejections.UNDEREXPOSED>0);assert.ok(r.rejections.OVEREXPOSED>0);});
test('replay records a same-view duplicate rejection',async()=>assert.equal((await runReplay(replayFixtures.duplicate)).rejections.DUPLICATE,1));
test('replay output is deterministic across independent runs',async()=>{const a=await runReplay(replayFixtures.steady120),b=await runReplay(replayFixtures.steady120);assert.deepEqual(a,b);});
