import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeSceneSweep, canonicalSceneSpatialContextJson, canonicalViewCandidatesJson, opportunityStabilityScore } from '../p1/analyze-scene-sweep.js';
import { DEFAULT_PHOTOGRAPHY_INTENT, framingRect, P1_RANKING_CONFIG } from '../p1/config.js';
import { segmentAngularRegions } from '../p1/angular-regions.js';
import { evaluatePlacementZones } from '../p1/placement.js';
import { p1ReplayFixtures, makeP1ReplayInput } from '../p1/replay-fixtures.js';
import { syntheticVisualFixtures } from '../p1/synthetic-fixtures.js';
import type { FramingProfile, KeyframeVisualDescriptor, PixelFrame, SubjectPlacementZone } from '../p1/types.js';
import { describeKeyframe, descriptorDistance } from '../p1/visual-descriptor.js';
import type { SceneSweepKeyframe } from '../sweep/types.js';

const keyframe = (id: string, yaw = 0, blur = 30): SceneSweepKeyframe => ({ keyframe_id: id, sequence: 1, timestamp_ms: 0, yaw_deg: yaw, width: 96, height: 72, blur_score: blur, exposure_mean: 128, highlight_clipping_ratio: 0, shadow_clipping_ratio: 0, fingerprint: [0, 1], quality_status: 'ACCEPTED', selection_reason: 'INITIAL' });
const describe = (visual: keyof typeof syntheticVisualFixtures, yaw = 0): KeyframeVisualDescriptor => describeKeyframe(keyframe(`kf-${visual}-${yaw}`, yaw, visual === 'blurred' ? 1 : 30), syntheticVisualFixtures[visual]);
const placementsFor = (descriptor: KeyframeVisualDescriptor, pixels: PixelFrame, profile: FramingProfile = 'ENVIRONMENTAL'): SubjectPlacementZone[] => evaluatePlacementZones(descriptor, pixels, profile);
const analyze = (fixture: (typeof p1ReplayFixtures)[keyof typeof p1ReplayFixtures]) => analyzeSceneSweep(fixture.manifest, fixture.yaw_map, fixture.transient_keyframes, fixture.intent);
const deterministicOutput = (result: ReturnType<typeof analyzeSceneSweep>) => ({ context: result.context, frame_set: result.frame_set, direction_map: result.direction_map, view_candidates: result.view_candidates, descriptors: result.descriptors });

test('P1 descriptor is exactly deterministic',()=>assert.deepEqual(describe('clean-balanced'),describe('clean-balanced')));
test('P1 descriptor version is 0.1',()=>assert.equal(describe('clean-balanced').descriptor_version,'0.1'));
test('busy fixture has more clutter than clean fixture',()=>assert.ok(describe('high-clutter').visual_clutter_score>describe('clean-balanced').visual_clutter_score));
test('busy fixture has more edge density than clean fixture',()=>assert.ok(describe('high-clutter').edge_density>describe('clean-balanced').edge_density));
test('overexposed descriptor records high luma',()=>assert.ok(describe('overexposed').exposure.mean_luma>225));
test('overexposed descriptor records highlight clipping',()=>assert.ok(describe('overexposed').exposure.highlight_clip_ratio>.5));
test('underexposed descriptor records low luma',()=>assert.ok(describe('underexposed').exposure.mean_luma<30));
test('underexposed descriptor records shadow clipping',()=>assert.ok(describe('underexposed').exposure.shadow_clip_ratio>.5));
test('balanced fixture beats severe overexposure score',()=>assert.ok(describe('clean-balanced').exposure.balanced_score>describe('overexposed').exposure.balanced_score));
test('sharp textured fixture beats blurred fixture quality',()=>assert.ok(describe('moderate-balanced').photography_frame_quality_score>describe('blurred').photography_frame_quality_score));
test('descriptor grid contains nine cells',()=>assert.equal(describe('clean-balanced').grid.length,9));
test('edge grid maps to 3x3',()=>assert.deepEqual(describe('clean-balanced').local_edge_density_grid.map(row=>row.length),[3,3,3]));
test('luma grid maps to 3x3',()=>assert.deepEqual(describe('clean-balanced').local_luma_grid.map(row=>row.length),[3,3,3]));
test('contrast grid maps to 3x3',()=>assert.deepEqual(describe('clean-balanced').local_contrast_grid.map(row=>row.length),[3,3,3]));
test('descriptor distance is zero for equal input',()=>{const a=describe('clean-balanced');assert.equal(descriptorDistance(a,a),0);});
test('descriptor distance detects visual discontinuity',()=>assert.ok(descriptorDistance(describe('clean-balanced'),describe('high-clutter'))>P1_RANKING_CONFIG.descriptor_boundary_threshold));
test('placement evaluates left center and right anchors',()=>assert.deepEqual(placementsFor(describe('clean-balanced'),syntheticVisualFixtures['clean-balanced']).map(zone=>zone.anchor).sort(),['CENTER','LEFT_THIRD','RIGHT_THIRD']));
test('clean-left fixture favors left placement',()=>assert.equal(placementsFor(describe('clean-left'),syntheticVisualFixtures['clean-left'])[0]?.anchor,'LEFT_THIRD'));
test('clean-right fixture favors right placement',()=>assert.equal(placementsFor(describe('clean-right'),syntheticVisualFixtures['clean-right'])[0]?.anchor,'RIGHT_THIRD'));
test('center edge conflict avoids center placement',()=>assert.notEqual(placementsFor(describe('center-edge'),syntheticVisualFixtures['center-edge'])[0]?.anchor,'CENTER'));
test('center edge fixture measures more center conflict than clean side',()=>{const zones=placementsFor(describe('center-edge'),syntheticVisualFixtures['center-edge']);const center=zones.find(zone=>zone.anchor==='CENTER')!,left=zones.find(zone=>zone.anchor==='LEFT_THIRD')!;assert.ok(center.edge_conflict_score>left.edge_conflict_score);});
for(const profile of ['CLOSE','MEDIUM','ENVIRONMENTAL','FULL_BODY'] as FramingProfile[]) test(`${profile} framing rectangles stay inside image bounds`,()=>{for(const anchor of ['LEFT_THIRD','CENTER','RIGHT_THIRD'] as const){const r=framingRect(profile,anchor);assert.ok(r.x>=0&&r.y>=0&&r.x+r.width<=1&&r.y+r.height<=1);}});
test('uniform neighboring descriptors form one angular region',()=>assert.equal(analyze(p1ReplayFixtures.uniform).context.angular_regions.length,1));
test('mixed wide fixture forms useful bounded regions',()=>{const count=analyze(p1ReplayFixtures.mixedWide).context.angular_regions.length;assert.ok(count>=3&&count<=8);});
test('angular regions are ordered by yaw',()=>{const regions=analyze(p1ReplayFixtures.mixedWide).context.angular_regions;assert.deepEqual(regions.map(r=>r.yaw_start_deg),[...regions].map(r=>r.yaw_start_deg).sort((a,b)=>a-b));});
test('descriptor discontinuity creates a region boundary',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).context.angular_regions.some(region=>region.boundary_reason==='DESCRIPTOR_DISCONTINUITY')));
test('every region representative belongs to that region',()=>{for(const region of analyze(p1ReplayFixtures.mixedWide).context.angular_regions)assert.ok(region.keyframe_ids.includes(region.representative_keyframe_id));});
test('region score is bounded',()=>{for(const region of analyze(p1ReplayFixtures.mixedWide).context.angular_regions)assert.ok(region.scene_region_score>=0&&region.scene_region_score<=1);});
test('context schema version is 0.1',()=>assert.equal(analyze(p1ReplayFixtures.mixedWide).context.schema_version,'0.1'));
test('context preserves manifest coverage',()=>{const f=p1ReplayFixtures.mixedWide;assert.equal(analyze(f).context.coverage.span_deg,f.manifest.coverage_deg);});
test('context descriptors match transient keyframes',()=>{const f=p1ReplayFixtures.mixedWide;assert.equal(analyze(f).descriptors.length,f.transient_keyframes.length);});
test('context privacy fixes all network counters to zero',()=>assert.deepEqual(analyze(p1ReplayFixtures.mixedWide).context.privacy,{raw_keyframes_transient:true,raw_media_persisted:false,raw_media_uploaded:false,provider_calls:0,backend_per_frame_calls:0,luna_calls:0}));
test('context limitations disclose no semantic understanding',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).context.limitations.includes('NO_SEMANTIC_OBJECT_LABELS')));
test('view candidate output contains at most three',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.length<=3));
test('mixed wide returns three diverse view candidates',()=>assert.equal(analyze(p1ReplayFixtures.mixedWide).view_candidates.length,3));
test('one uniform region still returns three view candidates',()=>{const result=analyze(p1ReplayFixtures.uniform);assert.equal(result.context.angular_regions.length,1);assert.equal(result.view_candidates.length,3);});
test('view candidates are explicitly candidates rather than authority',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.every(item=>item.evidence_class==='CANDIDATE'&&item.final_photography_decision==='NOT_P1_RESPONSIBILITY')));
test('every view exposes all three placement candidate anchors',()=>{for(const view of analyze(p1ReplayFixtures.mixedWide).view_candidates)assert.deepEqual(view.placement_candidates.map(item=>item.image_anchor).sort(),['CENTER','LEFT_THIRD','RIGHT_THIRD']);});
test('placement candidates keep physical position unknown',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.flatMap(item=>item.placement_candidates).every(item=>item.physical_position==='UNKNOWN')));
test('placement candidate safety remains user confirmed',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.flatMap(item=>item.placement_candidates).every(item=>item.safety==='UNKNOWN_REQUIRES_USER_CONFIRMATION')));
test('view candidate generation is exactly deterministic',()=>assert.deepEqual(deterministicOutput(analyze(p1ReplayFixtures.mixedWide)),deterministicOutput(analyze(p1ReplayFixtures.mixedWide))));
test('severe quality frames are not treated as an aesthetic winner',()=>assert.ok(analyze(p1ReplayFixtures.severeQuality).view_candidates.filter(item=>item.technical_reason_codes.some(code=>code.startsWith('PENALTY_'))).length<=1));
test('view candidates are selected in yaw order',()=>{const items=analyze(p1ReplayFixtures.mixedWide).view_candidates;assert.deepEqual(items.map(item=>item.relative_camera_yaw_deg),[...items].map(item=>item.relative_camera_yaw_deg).sort((a,b)=>a-b));});
test('view candidate selection basis is angular diversity plus technical usability',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.every(item=>assert.deepEqual(item.selection_basis,['ANGULAR_DIVERSITY','TECHNICAL_USABILITY'])===undefined)));
test('balanced candidate emits measured technical reason',()=>assert.ok(analyze(p1ReplayFixtures.severeQuality).view_candidates.some(item=>item.technical_reason_codes.includes('BALANCED_EXPOSURE'))));
test('view candidate region is metadata only',()=>{const result=analyze(p1ReplayFixtures.uniform);assert.equal(new Set(result.view_candidates.map(item=>item.region_id)).size,1);assert.equal(result.view_candidates.length,3);});
test('view candidate version is 0.1',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.every(item=>item.schema_version==='0.1')));
test('context canonical serialization is stable',()=>{const context=analyze(p1ReplayFixtures.mixedWide).context;assert.equal(canonicalSceneSpatialContextJson(context),canonicalSceneSpatialContextJson(context));});
test('view candidate canonical serialization is stable',()=>{const candidates=analyze(p1ReplayFixtures.mixedWide).view_candidates;assert.equal(canonicalViewCandidatesJson(candidates),canonicalViewCandidatesJson(candidates));});
test('P1 replay fixture inventory has five controlled scenes',()=>assert.equal(Object.keys(p1ReplayFixtures).length,5));
for(const [name,fixture] of Object.entries(p1ReplayFixtures)) test(`P1 replay ${name} is deterministic`,()=>assert.deepEqual(deterministicOutput(analyze(fixture)),deterministicOutput(analyze(fixture))));
test('identical replay opportunity stability is one',()=>{const result=analyze(p1ReplayFixtures.mixedWide);assert.equal(opportunityStabilityScore(result,result),1);});
test('minor yaw perturbation retains dominant opportunity stability',()=>{const original=analyze(p1ReplayFixtures.mixedWide);const perturbed=makeP1ReplayInput([{yaw:-88,visual:'clean-left'},{yaw:-69,visual:'clean-left'},{yaw:-43,visual:'high-clutter'},{yaw:-24,visual:'high-clutter'},{yaw:7,visual:'moderate-balanced'},{yaw:27,visual:'moderate-balanced'},{yaw:62,visual:'clean-right'},{yaw:92,visual:'clean-right'}]);assert.ok(opportunityStabilityScore(original,analyze(perturbed))>=2/3);});
test('serialized context contains no pixel arrays',()=>assert.equal(canonicalSceneSpatialContextJson(analyze(p1ReplayFixtures.mixedWide).context).includes('Uint8ClampedArray'),false));
test('default intent is single person environmental',()=>assert.deepEqual(DEFAULT_PHOTOGRAPHY_INTENT,{subject_type:'SINGLE_PERSON',preferred_framing:'ENVIRONMENTAL',composition_preference:'AUTO'}));
test('intent framing profile flows into placement candidates',()=>assert.ok(analyze(p1ReplayFixtures.mixedWide).view_candidates.flatMap(item=>item.placement_candidates).every(item=>item.framing_profile==='ENVIRONMENTAL')));
test('invalid pixel frames are rejected',()=>assert.throws(()=>describeKeyframe(keyframe('bad'),{width:4,height:4,data:new Uint8ClampedArray(3)}),/INVALID_PIXEL_FRAME/));
test('analysis truthfully returns empty candidates for no transient pixels',()=>{const f=p1ReplayFixtures.uniform,r=analyzeSceneSweep(f.manifest,f.yaw_map,[],f.intent);assert.equal(r.context.angular_regions.length,0);assert.equal(r.frame_set.frames.length,0);assert.equal(r.view_candidates.length,0);});
test('SceneFrameSet prepares every analyzed image without export bytes',()=>{const result=analyze(p1ReplayFixtures.uniform);assert.equal(result.frame_set.frames.length,result.descriptors.length);assert.equal(result.frame_set.image_bytes_in_export,false);assert.equal(result.frame_set.lifecycle,'TRANSIENT_BROWSER_MEMORY');});
test('SceneDirectionMap contains every prepared frame',()=>{const result=analyze(p1ReplayFixtures.mixedWide);assert.equal(result.direction_map.nodes.length,result.frame_set.frames.length);});
test('SceneDirectionMap arc positions are bounded and ordered',()=>{const nodes=analyze(p1ReplayFixtures.mixedWide).direction_map.nodes;assert.ok(nodes.every(item=>item.arc_position>=0&&item.arc_position<=1));assert.deepEqual(nodes.map(item=>item.arc_position),[...nodes].map(item=>item.arc_position).sort((a,b)=>a-b));});
test('SceneDirectionMap does not claim depth or metric geometry',()=>{const map=analyze(p1ReplayFixtures.mixedWide).direction_map;assert.equal(map.depth,'UNKNOWN');assert.equal(map.metric_geometry,'NOT_SUPPORTED');assert.equal(map.spatial_evidence_status,'NOT_EVALUATED_P1');});
test('serialized P1 V2 result contains no thumbnail or pixel arrays',()=>{const serialized=JSON.stringify(deterministicOutput(analyze(p1ReplayFixtures.mixedWide)));assert.equal(serialized.includes('thumbnail_url'),false);assert.equal(serialized.includes('Uint8ClampedArray'),false);});
test('P1 analysis preserves P0 manifest privacy regression',()=>{const p=p1ReplayFixtures.mixedWide.manifest.privacy;assert.deepEqual(p,{raw_video_uploaded:false,raw_frame_stream_uploaded:false,third_party_image_uploaded:false,committed_user_media:false});});
test('direct region segmentation handles empty descriptors',()=>assert.deepEqual(segmentAngularRegions([],new Map()),[]));
